### ISSUE TITLE
Can't debug in VS Code with code genereated by Ignite

### ISSUE THREAD

**Issue by Kimmen** [Microsoft/vscode-react-native#346] opened 2016-11-17 11:54 UTC
I've generated a react-native application with [Ignite](https://github.com/infinitered/ignite) and it app crashed when I try to debug using VS Code. Also tried to Attach to Packager, doesn't generate an error or crash but doesn't hit any breakpoints.

.babelrc  has been updated: changed the sourceMaps property from "inline" to true. 
Also, I'm running the emulator from the Android SDK. 

## Actual Behavior
1. In VS Code, run Debug Android
2. App crashes in Emulator causes the remote debugging to fail.

## Expected Behavior
1. In VS Code, run Debug Android
2. Able to debug the app in the emulator

## Software versions
- React-Native VS Code extension version: 0.2.2
- VSCode version: 1.7.1
- OS platform and version: Windows 10 (latest update)
- NodeJS version: 7.0.0 (installed via chocolatey if it matters)
- React Native version:  react-native-cli@1.2.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
DEBUG CONSOLE
[vscode-react-native] Attaching to running packager at port: 8081
[vscode-react-native] Prewarming bundle cache. This may take a while ...
[vscode-react-native] Building and running application.
[vscode-react-native] Executing command: react-native.cmd run-android
(node:6336) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
(node:6336) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
JS server already running.
Running C:\Users\joakimr\AppData\Local\Android\android-sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && gradlew.bat installDebug...
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-config:compileLint
:react-native-config:copyReleaseLint UP-TO-DATE
:react-native-config:preBuild UP-TO-DATE
:react-native-config:preReleaseBuild UP-TO-DATE
:react-native-config:checkReleaseManifest
:react-native-config:preDebugAndroidTestBuild UP-TO-DATE
:react-native-config:preDebugBuild UP-TO-DATE
:react-native-config:preDebugUnitTestBuild UP-TO-DATE
:react-native-config:preReleaseUnitTestBuild UP-TO-DATE
:react-native-config:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-config:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-config:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:react-native-config:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:react-native-config:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:react-native-config:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:react-native-config:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:react-native-config:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:react-native-config:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:react-native-config:prepareComFacebookReactReactNative0370Library UP-TO-DATE
:react-native-config:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:react-native-config:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-config:prepareReleaseDependencies
:react-native-config:compileReleaseRenderscript UP-TO-DATE
:react-native-config:generateReleaseBuildConfig UP-TO-DATE
:react-native-config:generateReleaseAssets UP-TO-DATE
:react-native-config:mergeReleaseAssets UP-TO-DATE
:react-native-config:generateReleaseResValues UP-TO-DATE
:react-native-config:generateReleaseResources UP-TO-DATE
:react-native-config:mergeReleaseResources UP-TO-DATE
:react-native-config:processReleaseManifest UP-TO-DATE
:react-native-config:processReleaseResources UP-TO-DATE
:react-native-config:generateReleaseSources UP-TO-DATE
:react-native-config:processReleaseJavaRes UP-TO-DATE
:react-native-config:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-config:extractReleaseAnnotations UP-TO-DATE
:react-native-config:mergeReleaseProguardFiles UP-TO-DATE
:react-native-config:packageReleaseJar UP-TO-DATE
:react-native-config:compileReleaseNdk UP-TO-DATE
:react-native-config:packageReleaseJniLibs UP-TO-DATE
:react-native-config:packageReleaseLocalJar UP-TO-DATE
:react-native-config:packageReleaseRenderscript UP-TO-DATE
:react-native-config:packageReleaseResources UP-TO-DATE
:react-native-config:bundleRelease UP-TO-DATE
:react-native-device-info:compileLint
:react-native-device-info:copyReleaseLint UP-TO-DATE
:react-native-device-info:preBuild UP-TO-DATE
:react-native-device-info:preReleaseBuild UP-TO-DATE
:react-native-device-info:checkReleaseManifest
:react-native-device-info:preDebugAndroidTestBuild UP-TO-DATE
:react-native-device-info:preDebugBuild UP-TO-DATE
:react-native-device-info:preDebugUnitTestBuild UP-TO-DATE
:react-native-device-info:preReleaseUnitTestBuild UP-TO-DATE
:react-native-device-info:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-device-info:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-device-info:prepareComAndroidSupportSupportV42400Library UP-TO-DATE
:react-native-device-info:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:react-native-device-info:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:react-native-device-info:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:react-native-device-info:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:react-native-device-info:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:react-native-device-info:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:react-native-device-info:prepareComFacebookReactReactNative0370Library UP-TO-DATE
:react-native-device-info:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:react-native-device-info:prepareComGoogleAndroidGmsPlayServicesBase980Library UP-TO-DATE
:react-native-device-info:prepareComGoogleAndroidGmsPlayServicesBasement980Library UP-TO-DATE
:react-native-device-info:prepareComGoogleAndroidGmsPlayServicesGcm980Library UP-TO-DATE
:react-native-device-info:prepareComGoogleAndroidGmsPlayServicesIid980Library UP-TO-DATE
:react-native-device-info:prepareComGoogleAndroidGmsPlayServicesTasks980Library UP-TO-DATE
:react-native-device-info:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-device-info:prepareReleaseDependencies
:react-native-device-info:compileReleaseAidl UP-TO-DATE
:react-native-device-info:compileReleaseRenderscript UP-TO-DATE
:react-native-device-info:generateReleaseBuildConfig UP-TO-DATE
:react-native-device-info:generateReleaseAssets UP-TO-DATE
:react-native-device-info:mergeReleaseAssets UP-TO-DATE
:react-native-device-info:generateReleaseResValues UP-TO-DATE
:react-native-device-info:generateReleaseResources UP-TO-DATE
:react-native-device-info:mergeReleaseResources UP-TO-DATE
:react-native-device-info:processReleaseManifest UP-TO-DATE
:react-native-device-info:processReleaseResources UP-TO-DATE
:react-native-device-info:generateReleaseSources UP-TO-DATE
:react-native-device-info:processReleaseJavaRes UP-TO-DATE
:react-native-device-info:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-device-info:extractReleaseAnnotations UP-TO-DATE
:react-native-maps:mergeReleaseProguardFiles UP-TO-DATE
:react-native-maps:packageReleaseJar UP-TO-DATE
:react-native-maps:compileReleaseNdk UP-TO-DATE
:react-native-maps:packageReleaseJniLibs UP-TO-DATE
:react-native-maps:packageReleaseLocalJar UP-TO-DATE
:react-native-maps:packageReleaseRenderscript UP-TO-DATE
:react-native-maps:packageReleaseResources UP-TO-DATE
:react-native-maps:bundleRelease UP-TO-DATE
:react-native-vector-icons:compileLint
:react-native-vector-icons:copyReleaseLint UP-TO-DATE
:react-native-vector-icons:preBuild UP-TO-DATE
:react-native-vector-icons:preReleaseBuild UP-TO-DATE
:react-native-vector-icons:checkReleaseManifest
:react-native-vector-icons:preDebugAndroidTestBuild UP-TO-DATE
:react-native-vector-icons:preDebugBuild UP-TO-DATE
:react-native-vector-icons:preDebugUnitTestBuild UP-TO-DATE
:react-native-vector-icons:preReleaseUnitTestBuild UP-TO-DATE
:react-native-vector-icons:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-vector-icons:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-vector-icons:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookReactReactNative0370Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:react-native-vector-icons:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-vector-icons:prepareReleaseDependencies
:react-native-vector-icons:compileReleaseAidl UP-TO-DATE
:react-native-vector-icons:compileReleaseRenderscript UP-TO-DATE
:react-native-vector-icons:generateReleaseBuildConfig UP-TO-DATE
:react-native-vector-icons:generateReleaseAssets UP-TO-DATE
:react-native-vector-icons:mergeReleaseAssets UP-TO-DATE
:react-native-vector-icons:generateReleaseResValues UP-TO-DATE
:react-native-vector-icons:generateReleaseResources UP-TO-DATE
:react-native-vector-icons:mergeReleaseResources UP-TO-DATE
:react-native-vector-icons:processReleaseManifest UP-TO-DATE
:react-native-vector-icons:processReleaseResources UP-TO-DATE
:react-native-vector-icons:generateReleaseSources UP-TO-DATE
:react-native-vector-icons:processReleaseJavaRes UP-TO-DATE
:react-native-vector-icons:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-vector-icons:extractReleaseAnnotations UP-TO-DATE
:react-native-vector-icons:mergeReleaseProguardFiles UP-TO-DATE
:react-native-vector-icons:packageReleaseJar UP-TO-DATE
:react-native-vector-icons:compileReleaseNdk UP-TO-DATE
:react-native-vector-icons:packageReleaseJniLibs UP-TO-DATE
:react-native-vector-icons:packageReleaseLocalJar UP-TO-DATE
:react-native-vector-icons:packageReleaseRenderscript UP-TO-DATE
:react-native-vector-icons:packageReleaseResources UP-TO-DATE
:react-native-vector-icons:bundleRelease UP-TO-DATE
:app:prepareBikexReactNativeConfigUnspecifiedLibrary UP-TO-DATE
:app:prepareBikexReactNativeDeviceInfoUnspecifiedLibrary UP-TO-DATE
:app:prepareBikexReactNativeI18nUnspecifiedLibrary UP-TO-DATE
:app:prepareBikexReactNativeMapsUnspecifiedLibrary UP-TO-DATE
:app:prepareBikexReactNativeVectorIconsUnspecifiedLibrary UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42400Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
app:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0370Library UP-TO-DATE
:app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBase961Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBasement961Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesGcm961Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesIid961Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesMaps961Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesTasks961Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:preDexDebug UP-TO-DATE
:app:dexDebug UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug UP-TO-DATE
:app:zipalignDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:installDebug
Installing APK 'app-debug.apk' on 'emulator-5554 - 7.1.1'
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 22.883 secs
Starting the app on emulator-5554 (C:\Users\joakimr\AppData\Local\Android\android-sdk/platform-tools/adb -s emulator-5554 shell am start -n com.bikex/.MainActivity)...
Starting: Intent { cmp=com.bikex/.MainActivity }
[vscode-react-native] Finished executing: react-native.cmd run-android
[vscode-react-native] Executing command: adb -s emulator-5554 shell am broadcast -a "com.bikex.RELOAD_APP_ACTION" --ez jsproxy true
[vscode-react-native] Broadcasting: Intent { act=com.bikex.RELOAD_APP_ACTION (has extras) }
Broadcast completed: result=0
[vscode-react-native] Finished executing: adb -s emulator-5554 shell am broadcast -a "com.bikex.RELOAD_APP_ACTION" --ez jsproxy true
node --debug-brk=30886 --nolazy launchReactNative.js 9090 
Debugger listening on 127.0.0.1:30886
[vscode-react-native] Downloaded debuggerWorker.js (Logic to run the React Native app) from the Packager.
[vscode-react-native] Starting debugger app worker.
[vscode-react-native] Established a connection with the Proxy (Packager) to the React Native application
[vscode-react-native] Debugging session started successfully.


```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
Getting exponent dependecy.
######### Checking react native is correctly setup. This may take a while... ##########
Checking if the correct react native is installed..
######### Starting Packager ##########
######### Executing command: react-native.cmd start --port 8081 ##########
(node:10252) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
(node:10252) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
Scanning 971 folders for symlinks in <project folder>\node_modules (47ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   <project folder> 

[Hot Module Replacement] Server listening on /hot

React packager ready.

######### Packager started. ##########
[2016-11-17 10:21:32] <START> Requesting bundle  url: /index.android.bundle?platform=android  
[2016-11-17 10:21:55] <START> Initializing Packager
[2016-11-17 10:21:55] <START> Building in-memory fs for JavaScript
[2016-11-17 10:21:55] <END>   Building in-memory fs for JavaScript (166ms)
[2016-11-17 10:21:55] <START> Building Haste Map
[2016-11-17 10:21:57] <END>   Building Haste Map (1383ms)
[2016-11-17 10:21:57] <END>   Initializing Packager (1628ms)
[2016-11-17 10:21:57] <START> Transforming modules
[2016-11-17 10:21:57] <END>   Transforming modules (587ms)
[2016-11-17 10:21:57] <END>   Requesting bundle  url: /index.android.bundle?platform=android   (25541ms)
######### The Bundle Cache was prewarmed. ##########
[2016-11-17 10:23:55] <START> Requesting bundle  url: /index.android.bundle?platform=android  
[2016-11-17 10:23:55] <END>   Requesting bundle  url: /index.android.bundle?platform=android   (37ms)
######### The Bundle Cache was prewarmed. ##########
Starting custom debugger by executing: echo A debugger is not needed:  "<project folder>"
Starting custom debugger by executing: echo A debugger is not needed:  "<project folder>"
Starting custom debugger by executing: echo A debugger is not needed:  "<project folder>"
Starting custom debugger by executing: echo A debugger is not needed:  "<project folder>"
[2016-11-17 10:24:52] <START> Requesting bundle  url: /index.android.bundle?platform=android&dev=true&hot=true&minify=false  
[2016-11-17 10:24:52] <START> Transforming modules
[2016-11-17 10:24:53] <END>   Transforming modules (498ms)
[2016-11-17 10:24:53] <END>   Requesting bundle  url: /index.android.bundle?platform=android&dev=true&hot=true&minify=false   (710ms)
[2016-11-17 10:24:53] <START> Requesting bundle  url: /index.android.map?platform=android&dev=true&hot=true&minify=false  
[2016-11-17 10:24:53] <END>   Requesting bundle  url: /index.android.map?platform=android&dev=true&hot=true&minify=false   (121ms)
Starting custom debugger by executing: echo A debugger is not needed:  "<project folder>"
Starting custom debugger by executing: echo A debugger is not needed:  "<project folder>"
Starting custom debugger by executing: echo A debugger is not needed:  "<project folder>"
Starting custom debugger by executing: echo A debugger is not needed:  "<project folder>"
Starting custom debugger by executing: echo A debugger is not needed:  "<project folder>"
Starting custom debugger by executing: echo A debugger is not needed:  "<project folder>"
[2016-11-17 10:33:44] <START> Requesting bundle  url: /index.android.bundle?platform=android&dev=true&hot=false&minify=false  
[2016-11-17 10:33:44] <START> Transforming modules
[2016-11-17 10:33:45] <END>   Transforming modules (661ms)
[2016-11-17 10:33:45] <END>   Requesting bundle  url: /index.android.bundle?platform=android&dev=true&hot=false&minify=false   (916ms)
[2016-11-17 10:33:47] <START> Processing asset request  asset: App/Images/ir.png  
[2016-11-17 10:33:47] <END>   Processing asset request  asset: App/Images/ir.png   (3ms)
[2016-11-17 10:41:01] <START> Requesting bundle  url: /index.android.bundle?platform=android  
[2016-11-17 10:41:01] <END>   Requesting bundle  url: /index.android.bundle?platform=android   (40ms)
######### The Bundle Cache was prewarmed. ##########
[2016-11-17 10:41:31] <START> Requesting bundle  url: /index.android.bundle?platform=android&dev=true&hot=false&minify=false  
[2016-11-17 10:41:31] <END>   Requesting bundle  url: /index.android.bundle?platform=android&dev=true&hot=false&minify=false   (36ms)
Starting custom debugger by executing: echo A debugger is not needed:  "<project folder>"
Starting custom debugger by executing: echo A debugger is not needed:  "<project folder>"

```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
shell.ts:440 l._setExceptionValue is not a function: TypeError: l._setExceptionValue is not a function
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:5751)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:9310)
    at _run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:11138)
    at _completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:10579)
    at then (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:12571)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:8389)
    at _run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:11138)
    at _setCompleteValue (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:10832)
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:5712)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:9310)
    at _run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:11138)
    at _completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:10579)
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:5732)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:9310)
    at _run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:11138)
    at _completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:10579)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:17241
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:5732)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:9310)
    at _run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:11138)
    at _completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:10579)
    at c (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:14117)
    at J.then.o.(anonymous function) (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:14334)
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:5732)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:9310)
    at _run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:11138)
    at _completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:10579)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by vladimir-kotikov** [comment] 2016-11-21 15:31
It looks like the `babel` from react-native packager somehow ignores `sourceMaps` option in `.babelrc`. In both cases, when running app from VSCode and when attaching to the packager, I can see the following error in debug console:
```
[vscode-react-native] [Warning] Couldn't import script at <http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false>. Debugging won't work: Try reloading the JS from inside the app, or Reconnect the VS Code debugger: Cannot GET /json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImQ6XFxQUk9KRUNUU1xcVGVtcFxcaWduaXRlX3Byb2plY3RfZmFpbHNfdG9fZGVidWdcXG5vZGVfbW9kdWxlc1xccmVhY3QtbmF0aXZlXFxwYWNrYWdlclxccmVhY3QtcGFja2FnZXJcXHNyY1xcUmVzb2x2ZXJcXHBvbHlmaWxsc1xccHJlbHVkZV9kZXYuanMiXSwibmFtZXMiOlsiZ2xvYmFsIiwiX19ERVZfXyIsIl9fQlVORExFX1NUQVJUX1RJTUVfXyIsIkRhdGUiLCJub3ciXSwibWFwcGluZ3MiOiI7QUFDQUEsT0FBT0MsT0FBUCxDQUFpQixJQUFqQjs7QUFFQUQsT0FBT0UscUJBQVAsQ0FBK0JDLEtBQUtDLEdBQUwsRUFBL0IiLCJmaWxlIjoicHJlbHVkZV9kZXYuanMiLCJzb3VyY2VzQ29udGVudCI6WyIvKiBlc2xpbnQgc3RyaWN0OjAgKi9cbmdsb2JhbC5fX0RFVl9fID0gdHJ1ZTtcblxuZ2xvYmFsLl9fQlVORExFX1NUQVJUX1RJTUVfXyA9IERhdGUubm93KCk7XG4iXX0=
```

This happens because the source maps are embedded into bundle (despite of `sourceMaps` value) as data URLs, and hence some internal logic in extension is failing to parse these URLs.

@Kimmen, could you please check `index.android.bundle` in `.vscode/.react` folder to see what are sourcemap URLs look like in your case?

**Comment by vladimir-kotikov** [comment] 2016-11-30 12:29
@Kimmen, ping. Can you check what sourcemap URLs look like in your case?

**Comment by Kimmen** [comment] 2016-12-06 12:28
Sorry for not answering earlier. 
I can't find anything regarding `index.android.bundle` inside the `.vscode/.react` folder. Can it be located outside the project folder? 

It's stated in some java files, but I don't know if that helps though.

**Comment by MSLaguana** [comment] 2016-12-06 17:12
We clean up the contents of `.vscode/.react` when you quit vscode, so if you haven't attempted to run your app since you opened vscode you will need to do so.

After you've run your app once, you should see something like `.vscode/.react/index.android.bundle`

**Comment by Kimmen** [comment] 2016-12-07 07:35
Found it.
So I searched for 'sourcemap' in the file and a couple of places where sourceMappingURLs are refered, eg:
`sourceMappingURLs=_data$body.sourceMappingURLs`

on the last line it says:
`//# sourceMappingURL=index.android.map`

Is "karma-sourcemap-loader" involved somehow? In the karma.config.js there are some configurations regarding inline-source-mapping.

**Comment by wafisher** [comment] 2016-12-28 00:43
I'm also having this exact same problem — have had this for multiple versions of Ignite, actually. It happens on iOS for me. Would love to help solve it.

**Comment by vladimir-kotikov** [comment] 2017-01-10 07:53
@wafisher, could you please check the following:
1. Does your `index.android|ios.bundle` have a reference to source map? Are there multiple references?
2. Does `sources` section in  corresponding `index.ios|android.bundle` contain a references to your source files?
3. Are these references valid? (i.e. the paths are correct and if resolved relative to `.vscode/.react` directory, ponting to the real files)

**Comment by ericvera** [comment] 2017-01-22 00:18
I am having the same problem of break points not working with an Ignite project. In my case the app launches (ios) and even attaching does not give me any errors (that I could find). Yet it still does not works.

Here is the content of my index.ios.bundle. It seems to be using an enconded source map rather than a path. I also have the sourceMap option in .babelrc set to true.

```
(function(global) {
global.__DEV__=true;

global.__BUNDLE_START_TIME__=Date.now();
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9Vc2Vycy9lcmljL0NvZGUva25vd25odW1hbnMvbm9kZV9tb2R1bGVzL3JlYWN0LW5hdGl2ZS9wYWNrYWdlci9yZWFjdC1wYWNrYWdlci9zcmMvUmVzb2x2ZXIvcG9seWZpbGxzL3ByZWx1ZGVfZGV2LmpzIl0sIm5hbWVzIjpbImdsb2JhbCIsIl9fREVWX18iLCJfX0JVTkRMRV9TVEFSVF9USU1FX18iLCJEYXRlIiwibm93Il0sIm1hcHBpbmdzIjoiO0FBQ0FBLE9BQU9DLE9BQVAsQ0FBaUIsSUFBakI7O0FBRUFELE9BQU9FLHFCQUFQLENBQStCQyxLQUFLQyxHQUFMLEVBQS9CIiwiZmlsZSI6InByZWx1ZGVfZGV2LmpzIiwic291cmNlc0NvbnRlbnQiOlsiLyogZXNsaW50IHN0cmljdDowICovXG5nbG9iYWwuX19ERVZfXyA9IHRydWU7XG5cbmdsb2JhbC5fX0JVTkRMRV9TVEFSVF9USU1FX18gPSBEYXRlLm5vdygpO1xuIl19
})(typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : this);
(function(global) {
```

**Comment by vladimir-kotikov** [comment] 2017-01-23 10:04
@ericvera, since version 0.2.4 these URLs are ignored - only the URL that points to map file is respected. Is there a `//# sourceMappingURL=index.ios.map` entry in your bundle? 

Also, what are the symptoms of the problem - are the breakpoints not get verified (i.e. stay greyed out after starting debug session) or they are not being hit?

**Comment by vladimir-kotikov** [comment] 2017-02-14 14:35
@ericvera, anhy updates? Are you still experiencing the issue with breakpoints?

**Comment by vladimir-kotikov** [comment] 2017-03-23 09:41
Guys, I'm going to close this since all my attempts to reproduce this problems didn't succeed. If anybody still experience the problem, feel free to reopen this

**Closed by vladimir-kotikov** 2017-03-23 09:41 UTC

**Comment by ericvera** [comment] 2017-03-23 16:28
I haven't had a chance to use this in a while, but probably will in the next couple of weeks. I'll reactivate and reach out if this is still an issue then. Thanks for following up!
