### ISSUE TITLE
Debug in exponent does not run or produce any kind of error

### ISSUE THREAD

**Issue by mtrivolli** [Microsoft/vscode-react-native#641] opened 2018-02-21 14:38 UTC
## Actual Behavior
1. "Debug in exponent" option in vscode does not produce any result. It seems to wait for something

## Expected Behavior
1. Launch the packager and show expo QR code

## Software versions
- React-Native VS Code extension version: 0.6.1
- VSCode version: 1.20.1
- OS platform and version: OSX Sierra 10.12.6
- NodeJS version: 8.9.4
- React Native version: 0.52.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.23.0
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox): no react-native in listbox, but some errors in extensions
```
{ Error: connect ENOENT /tmp/vscode-reactnative-b14cff98e8ffc692af84360a79508a440478f3fa67ecc65d64751eca479b886a.sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/tmp/vscode-reactnative-b14cff98e8ffc692af84360a79508a440478f3fa67ecc65d64751eca479b886a.sock' }
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```

console.ts:123 [Extension Host] Activating extension `vsmobile.vscode-react-native` failed:  Cannot find module 'app-center-node-client'
t.log @ console.ts:123
console.ts:123 [Extension Host] Here is the error stack:  Error: Cannot find module 'app-center-node-client'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:664:413)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/Users/vmorilla/.vscode/extensions/vsmobile.vscode-react-native-0.6.1/src/extension/appcenter/api/index.js:5:34)
	at Object.<anonymous> (/Users/vmorilla/.vscode/extensions/vsmobile.vscode-react-native-0.6.1/src/extension/appcenter/api/index.js:15:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
extensionService.ts:787 Activating extension `vsmobile.vscode-react-native` failed: Cannot find module 'app-center-node-client'.
R._logMessageInConsole @ extensionService.ts:787
```

## Additional information
This issue can be reproduced with a minimal application created with create-react-native-app

Thanks for your work!

**Comment by asaravi** [comment] 2018-02-21 17:56
I can also confirm I'm having this same issue, with the same output in Developer tools console.

**Software versions:**

- React-Native VS Code extension version: 0.6.1
- VSCode version: 1.20.1
- OS platform and version: Windows 10, version 1703, build 15063.909
- NodeJS version: 8.9.1
- React Native version: 0.52.0

**Comment by ldwight** [comment] 2018-02-21 19:54
VS Code: Version 1.20.1 

React-Native VS Code extension version: 0.6.1
OSX 10.13.3
Node 9.4.0
react-native-cli: 2.0.1
react-native: 0.52.0

I am having the same issue BUT- it works the first time I run it! After that, even uninstalling & reinstalling React Native Tools extension does not revive me.

Toggled "developer Tools" (hidden under Help- who know why) and see:

vsmobile.vscode-react-native` failed: Cannot find module 'app-center-node-client'.

full screen attached.
![debugnotworking](https://user-images.githubusercontent.com/15283742/36502012-abca83c6-1716-11e8-99b8-9cdc5a91270e.jpeg)

Thank you

**Comment by scolestock** [comment] 2018-02-22 22:05
I can also confirm I'm having this same issue, with the same output in Developer tools console.

Software versions:

React-Native VS Code extension version: 0.6.2
VSCode version: 1.20.1
OS platform and version: macOS 10.13.3
NodeJS version: 8.9.1
React Native version: 0.52.0

Output: 

{ Error: connect ENOENT /tmp/vscode-reactnative-6e8d5c66a6b6ee68087ee4366e492217296e1441eb7a925f408e417a2d91a364.sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/tmp/vscode-reactnative-6e8d5c66a6b6ee68087ee4366e492217296e1441eb7a925f408e417a2d91a364.sock' }{ Error: connect ENOENT /tmp/vscode-reactnative-6e8d5c66a6b6ee68087ee4366e492217296e1441eb7a925f408e417a2d91a364.sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/tmp/vscode-reactnative-6e8d5c66a6b6ee68087ee4366e492217296e1441eb7a925f408e417a2d91a364.sock' }

**Comment by Gremlin80** [comment] 2018-02-23 20:41
same issue encoutered. the extesions allow for a " debug once " feature. ..... 
uninstalling the extension does not work, however, completely clear the .vscode/extensions folder allow for another debug session....

**Comment by Gremlin80** [comment] 2018-02-23 20:42
is there a way to downgrade to pre 0.6.x version of react-native-tools?

**Comment by scolestock** [comment] 2018-02-23 21:18
@Gremlin80 I tried uninstalling the extension and then installing a previous version by downloading from this link (formulated following instructions on a stackoverflow article): 

`https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/vsmobile/extension/vscode-react-native/0.6.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage`

Rename file extension to VSIX, then use the ellipses button in the extensions panel (mac) to "install from VSIX".

**However**, I found that while the debugger ran and I get console output, no breakpoints were hit...

**Comment by Gremlin80** [comment] 2018-02-24 09:44
@scolestock . i'm pretty sure that if you replace a breakpoint on (say: line 11) with the corresponding `debugger; `instruction, the execution stops. 

maybe somewhat related to sourcemaps ?

**Comment by nahuelhds** [comment] 2018-02-25 19:03
This happens to my in Code and Code Insiders as well. First, I thought it was an insiders issue, but I cannot make it work in any of those softwares... anyone could make this work?

**Comment by nahuelhds** [comment] 2018-02-25 19:53
I've downgraded to 0.6.1 by following this steps:

# [Download the extension v0.6.1 from from here](https://vsmobile.gallery.vsassets.io/_apis/public/gallery/publisher/vsmobile/extension/vscode-react-native/0.6.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage) (thanks @scolestock).
# Rename that file's extension to `.vsix`
# In VSCode settings, set `"extensions.autoUpdate": false`
# Uninstalled the current extension (0.6.2).
# Installed the 0.6.1 from the vsix

That worked for me in both Code and Code Insiders as well.

Hope it helps.

**Comment by nahuelhds** [comment] 2018-02-25 20:24
Well... more news.

What I've mentioned worked only the first time. After running "reactNative.startExponentPackager" and restarting Code, it has the same problem that is mentioned in this thread.

So, I've noticed that the problem starts happening in when the extension finishes the "Checking if this is Expo app......" and that's is -in any way- related to the npm install that this process does (` npm install xdl @expo/ngrok --verbose --no-save`).

If you run the command `reactNative.startPackager` the extension works just fine even after restart.

So, in my case where I use Expo, the solution was stop using `reactNative.startPackager` and deploy the packager using XDE Expo software for it and debug normally as I do with this extension.

In conclusion, this is a `0.6.x` regression issue. So, my recommendation is:

1. If you already has this "command not found" issue when trying to use any of the `reactNative.*` commands, go to `~/.vscode/extensions` and delete the folder `vsmobile.vscode-react-native-x.y.z`
1. Install the extension normally in Code and through the vsix extension (it's the same).
1. [Download and install Expo XDE](https://docs.expo.io/versions/latest/introduction/installation.html#desktop-development-tool-xde)
1. With Expo XDE, open your project and wait for it to give you the message `Project opened!` in the logs.
1. Go to Code and `Attach the packager` as you normally do. Be sure to have the same `packagerPort` value given in `/.expo/packager-info.json` in your `"react-native.packager.port"` option at `/.vscode/settings.json` file (19001 in my case).

By doing this, I can use the debugger and breakpoints and after resetting Code it continues working without any problems.

Hope this helps to anybody.

**Comment by ruslan-bikkinin** [comment] 2018-02-26 09:59
Hi guys, I was able to reproduce it. I am working on a fix now so I'll keep you posted if there will be any news.

**Comment by ruslan-bikkinin** [comment] 2018-02-26 15:09
Well, after further investigation I figured that there was no real bug in my case - just a prolonged delay during extension work that led to timeout error on my machine. Anyway, I was able to reach "Expo QR code" step without errors using `6.0.3` version on a second try. @mtrivolli @nahuelhds could you please try to debug your app using this version and let me know whether it works?

**Comment by nahuelhds** [comment] 2018-02-26 16:22
Will do. You meant `0.6.3` right?

**Comment by ruslan-bikkinin** [comment] 2018-02-26 16:25
@nahuelhds yes, you are right) just a typo.

**Comment by ruslan-bikkinin** [comment] 2018-02-26 17:49
@nahuelhds In this case I can try again tomorrow and give you exact steps I followed so you could point me what I am missing now.

**Comment by nahuelhds** [comment] 2018-02-26 18:11
I leave what I do for getting the errors:

1. Uninstall the extension from Code.
1. Delete the folder from `~/.vscode/extensions/`
1. Install the extension again.
1. Go to a RN project and run `> React Native: Start Exponent Packager`
1. Wait for it to finish the entire process.
1. Close the app (cmd + Q)
1. Reopen the app, the project and try the same command.
1. You will see `reactNative.startExponenPackager` not found.

**Comment by mtrivolli** [comment] 2018-02-26 22:06
Same behaviour as @nahuelhds describes

**Comment by ruslan-bikkinin** [comment] 2018-02-27 15:05
@nahuelhds @mtrivolli Did you ran this command immediately after your project has opened? I was able to get `Command reactNative.startExponenPackager not found` if I did so but when I waited a little bit for extensions to be be loaded on the second try this message didn't appear.

**Comment by nahuelhds** [comment] 2018-02-27 15:17
@ruslan-bikkinin no. I know that "bug" and I wait for the IDE to finish loading before trying it =)

**Comment by nahuelhds** [comment] 2018-02-27 15:20
The issue is not about the command but about that the extension cannot load the `app-center-node-client` module at load time. If I open the IDE and then open the DevTools I see the error. See (no command executed yet):

![image](https://user-images.githubusercontent.com/1885647/36736952-9bd10174-1bb8-11e8-80a6-ab93581531b0.png)

**Comment by nahuelhds** [comment] 2018-02-27 15:21
That doesn't happen when you've just installed the extension

**Comment by nahuelhds** [comment] 2018-02-27 15:23
Remember I've also mentioned that the "Checking the Expo app" process, executes this npm command `npm install xdl @expo/ngrok --verbose --no-save` which give some errors. Maybe that's related @ruslan-bikkinin

**Comment by scolestock** [comment] 2018-02-27 22:48
@nahuelhds Your technique above (cleaning up, using the Expo packager, and then using "Attach to packager") is working somewhat for me - but with the curious behavior that I have to turn breakpoints on and off every time I reload the JS bundle in order to get execution to break.  

It will be awesome to have this whole extension working again - this was my primary workflow.

**Comment by ruslan-bikkinin** [comment] 2018-02-28 15:20
Thanks guys, I finally could reproduce it and working on a fix now.

**Comment by ruslan-bikkinin** [comment] 2018-03-02 14:11
@mtrivolli @scolestock @nahuelhds I have made a fix for this: #655. Could you, guys, please take a look on it and check whether it works for you? To test the fixed version of extension please do the following:
1. Uninstall current version of extension.
2. Create build of extension from my branch using these commands:

```
cd /your/preferred/directory
git clone https://github.com/ruslan-bikkinin/vscode-react-native.git
cd vscode-react-native
git checkout remove-file-dependency
npm i -g gulp
npm i
gulp release
```

3. Install fixed version of extension by clicking `Extensions -> ... -> Install from VSIX...` and selecting `/your/preferred/directory/vscode-react-native/vscode-react-native-0.6.3.vsix`.

**Comment by nahuelhds** [comment] 2018-03-02 14:19
I'll test it on my free time, tomorrow!


Nahuel Sotelo | Desarrollo de soluciones
Esmeralda 950, C1007ABL CABA
(+5411) 5263-0144 | www.cristalmedia.net
<http://www.twitter.com/CristalMedia>
<http://www.linkedin.com/company/cristalmedia>
<http://www.facebook.com/CristalMedia>
<http://plus.google.com/+CristalmediaNet>

2018-03-02 11:11 GMT-03:00 Ruslan Bikkinin <notifications@github.com>:

**Comment by nahuelhds** [comment] 2018-03-02 15:02
It gives me error when doing `gulp release` (I've done every command you mentioned) @ruslan-bikkinin 

My output

```
[12:01:16] Using gulpfile ~/Sites/vscode-react-native/gulpfile.js
[12:01:16] Starting 'check-imports'...
[12:01:16] Starting 'check-copyright'...
[12:01:19] Finished 'check-imports' after 2.71 s
[12:01:19] Finished 'check-copyright' after 2.71 s
[12:01:19] Starting 'build'...
[12:01:19] Building with preprocessor context: {"PROD":true}
[12:01:22] Finished 'build' after 3.1 s
[12:01:22] Starting 'release'...
Backing up license files to /var/folders/7k/84zxbl115dld560bwv6hhwbr0000gp/T/vscode-react-native...
Preparing license files for release...
Creating release package...
Restoring modified files...
[12:01:22] 'release' errored after 11 ms
[12:01:22] Error: An error occurred. Error: spawn vsce ENOENT
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:159:13)
    at Gulp.Orchestrator._emitTaskDone (/Users/nahuelhds/Sites/vscode-react-native/node_modules/orchestrator/index.js:264:8)
    at /Users/nahuelhds/Sites/vscode-react-native/node_modules/orchestrator/index.js:275:23
    at finish (/Users/nahuelhds/Sites/vscode-react-native/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/nahuelhds/Sites/vscode-react-native/node_modules/orchestrator/lib/runTask.js:45:4
    at _rejected (/Users/nahuelhds/Sites/vscode-react-native/node_modules/q/q.js:844:24)
    at /Users/nahuelhds/Sites/vscode-react-native/node_modules/q/q.js:870:30
    at Promise.when (/Users/nahuelhds/Sites/vscode-react-native/node_modules/q/q.js:1122:31)
MacBook-de-NiS:vscode-react-native nahuelhds$ vsce
-bash: vsce: command not found
```

**Comment by ruslan-bikkinin** [comment] 2018-03-03 08:07
@nahuelhds oh, sorry for that. I forgot to mention that you need global `vsce` package installed too. I will update my message.

**Comment by mtrivolli** [comment] 2018-03-03 08:56
The patch is working for me! Thank you!

**Closed** 2018-03-05 09:23 UTC
Labels: bug, fix-in-pull-request

**Comment by nahuelhds** [comment] 2018-03-06 14:10
The new version `0.6.4` works excellent for me. Thanks @ruslan-bikkinin 🎉

**Comment by ldwight** [comment] 2018-03-06 16:20
sorry to be a dummy, but I have many extensions involved in this debug. When you write:
"Uninstall current version of extension." I am not clear on which extension.
If it is the VSCode extension (as is implied by your instructions), how do I do that? 
Thanks!

**Comment by nahuelhds** [comment] 2018-03-06 17:46
@ldwight 0.6.4 doesn't work for you? it does for me.

Anyway about your question: yes, it's about removing the extension from VSCode program itself and then remove the folder in the extensions folders as well. In my case is `~/.vscode/extensions/vsmobile.vscode-react-native-x.y.z`

Hope it helps

**Comment by ldwight** [comment] 2018-03-06 20:41
@nahuelhds - well hot diggety! 0.6.4 is working - hooray! Thanks for making me look twice .

**Comment by ruslan-bikkinin** [comment] 2018-03-07 08:13
Yeah, guys, sorry for not mentioning that, but fix already in `0.6.4`.

**Comment by veedeo** [comment] 2018-03-07 11:58
I still have this issue with 0.6.4
When launching Debug IOS - debugger hangs and nothing happens;
Debug console
```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.23.0
```
Output
`{ Error: connect ENOENT /tmp/vscode-reactnative-7c08c89fe80d339aeae7a6c35c138afb1c1880125c7bf0446f59a69a1b12bec1.sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',`

**Comment by ruslan-bikkinin** [comment] 2018-03-12 07:16
Hi @veedeo. I don't think this is the same issue. More likely it's related to https://github.com/Microsoft/vscode-react-native/issues/646.

**Comment by ruslan-bikkinin** [comment] 2018-06-05 14:59
Hi @jhalborg and thanks for your feedback. Fix for this already in PRs: https://github.com/Microsoft/vscode-react-native/pull/717. Could you please try it on your machine and let me know whether it helps you? To test it please do the following:
1. Run these commands:
```
git clone git@github.com:ruslan-bikkinin/vscode-react-native.git
cd vscode-react-native
git checkout fix-enoent-socket-error
npm i 
```
2. Open `vscode-react-native` directory in VS Code, click on `Debug` icon, then select `Quick Launch Extension` in drop down menu and run it.
3. Wait for another instance of VS Code to be appeared (it will be named like `Extension Development Host...`), then open your project in it and try to reproduce issue.

Also, be aware that I have created separate issue https://github.com/Microsoft/vscode-react-native/issues/716 for this, so please don't hesitate to post your feedback there instead of this thread.
