### ISSUE TITLE
I encounted the issue #306 

### ISSUE THREAD

**Issue by Tonyhark** [Microsoft/vscode-react-native#499] opened 2017-07-29 07:19 UTC
## Actual Behavior
1.  When I use VSCode to open a project that initilized by https://github.com/react-community/create-react-native-app,
 I encounted the issue #306 
2.  the style intellSense do not work in component tag‘s style prop(<Text style={{}} />)  , but not in stylesheet.creator({}) 
3.  the function/method intellSense work well
![1](https://user-images.githubusercontent.com/4639033/28742996-1bd440ba-7471-11e7-8b4a-ffaca8af5ebe.PNG)\
![2](https://user-images.githubusercontent.com/4639033/28742998-28bd406a-7471-11e7-8065-507819018bc8.PNG)

## Expected Behavior
1. 
2. 

## Software versions
- React Native Tools extension version:   0.4.0
- VSCode version:  1.14.2
- OS platform and version:  both macOS 10.12.5   and windows 10
- NodeJS version:  6.10.0
- React Native version:  0.46.4

**Comment by vladimir-kotikov** [comment] 2017-07-31 12:06
@Tonyhark thanks for reporting - I was able to repro this, but an interesting observation is that if you trigger suggestion first (by pressing `Ctrl+Space`) all available property names are showed in suggestions list - see below

![image](https://user-images.githubusercontent.com/3857604/28776654-36662dd6-7600-11e7-997f-8839e1e6c676.png)

which sounds more like an issue with typescript engine that doesn't yield completions under some specific circumstances.

Also since we don't manage typings in this extension and completely rely on typescript and VSCode I doubt we can do anything here - I believe that [Microsoft/Typescript](https://github.com/Microsoft/TypeScript/issues) repository would be a better place to file this issue.

**Comment by vladimir-kotikov** [comment] 2017-08-01 09:44
@Tonyhark could you please confir that you're seeing the same behavior? Also, if there would be no objections I'm going to close this ticket in a couple of days.

**Comment by vladimir-kotikov** [comment] 2017-08-04 07:22
@Tonyhark any updates? If you don't have any objections, I'm going to close this

**Comment by gino8080** [comment] 2017-08-04 10:07
@vladimir-kotikov I can confirm i get the same behaviour,
no suggest while typing, but i got all the list with Ctrl+Space 

i have typescript 2.4.2 installed globally and also in the project folder

thank you!

**Comment by vladimir-kotikov** [comment] 2017-08-07 10:55
@gino8080 thanks for confirmation. Closing this

**Closed by vladimir-kotikov** 2017-08-07 10:55 UTC
Labels: external, triaged, wontfix

**Comment by aliazizi** [comment] 2019-03-17 04:10
I know this issue is closed but for more information I get very strange issue
I figure out its because of index.d.ts in react-native types in `create` method

So I change the type for test from
`export function create<T extends NamedStyles<T> | NamedStyles<any>>(styles: T): T;`
to
`export function create<T extends NamedStyles<T> | NamedStyles<any>>(styles: { [P in keyof T]: ViewStyle | TextStyle | ImageStyle }): T;`

I change style: T to actual type.

So now I get hint for style all styles except the first one!
In my case my first one is `container` So I did not get any hint for this but for other it's work perfect!

**Comment by aliazizi** [comment] 2019-03-17 04:10
I know this issue is closed but for more information I get very strange issue
I figure out its because of index.d.ts in react-native types in `create` method

So I change the type for test from
`export function create<T extends NamedStyles<T> | NamedStyles<any>>(styles: T): T;`
to
`export function create<T extends NamedStyles<T> | NamedStyles<any>>(styles: { [P in keyof T]: ViewStyle | TextStyle | ImageStyle }): T;`

I change style: T to actual type.

So now I get hint for style all styles except the first one!
In my case my first one is `container` So I did not get any hint for this but for other it's work perfect!
