### ISSUE TITLE
White screen on iOS simulator after running Attach to debugger configuration

### ISSUE THREAD

**Issue by LorandP** [Microsoft/vscode-react-native#476] opened 2017-07-17 08:32 UTC
## Actual Behavior
1. Nothing is showing on the simulator after running Attach to debugger configuration and selecting Remote JS Debugging on the device menu.
The break points are active.
Only the pause, restart and disconnect buttons are active in VS Code.

## Expected Behavior
1. A button and a text view appear. 
When I press the button, a number increments and is shown in the text view and I can debug the application on the iOS simulator. 

## Software versions
- React-Native VS Code extension version: 0.3.2
- VSCode version: 1.13.1
- OS platform and version: Sierra 10.12.5
- NodeJS version: 8.1.4
- React Native version: 0.46.1

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
[vscode-react-native] Debugger ready. Enable remote debugging in app.
[vscode-react-native] Starting debugger app worker.
[vscode-react-native] Established a connection with the Proxy (Packager) to the React Native 
application

After selecting Remote debugger in the simulator menu, this displays in the Debug Console:
[vscode-react-native] Debugger worker loaded runtime on port 32719
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
React-Native doesn't appear in the ListBox.
But this is what I get from the packager:

Scanning 559 folders for symlinks in /Users/lorand/React/Test/node_modules (93ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/lorand/React/Test 


React packager ready.

Loading dependency graph, done.
Bundling `index.ios.js`  100.0% (301/301), done.
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
[Extension Host] (node:875) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
But this error is not reproducing all the time. I tried to reproduce it but I can't.
```

**Comment by vladimir-kotikov** [comment] 2017-07-17 11:15
@LorandP this looks like a dupe of #459 and has been already fixed in #465

**Comment by RoJoHub** [comment] 2017-07-18 03:02
In vscode store ,version of tool is still 0.32.

When do you go to the release?

I'm new to here.

Thanks.

**Comment by vladimir-kotikov** [comment] 2017-07-18 08:01
@RoJoHub soon :) Sorry for delay guys, we're working on it.

/cc @panarasi

**Comment by vladimir-kotikov** [comment] 2017-07-18 08:02
Closing this as a dupe

**Closed** 2017-07-18 08:02 UTC
Labels: bug, duplicate, triaged

**Comment by RobIsHere** [comment] 2017-07-25 07:05
Would be great to have this soon, as it's really affecting productivity a lot. A developer without a debugger is like a fish without water...

**Comment by RoJoHub** [comment] 2017-07-26 08:07
@RobIsHere 
Where are u from?,I'm from china.
Your launguaue mode is like chinese.
haha.
:)
