### ISSUE TITLE
React native command palette doesn't work.

### ISSUE THREAD

**Issue by dominictwlee** [Microsoft/vscode-react-native#755] opened 2018-07-23 21:23 UTC
## Actual Behavior
1. Current Workspace is not a React Native project.

## Expected Behavior
1. Expect react native to run on android simulator.

## Software versions
- React-Native VS Code extension version: 0.6.13
- VSCode version: 1.25.1
- OS platform and version: Ubuntu 16.04
- NodeJS version: 10.4.0
- React Native version: 0.56.0
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- (View -> Output):
```
[Error] Failed to start the React Native packager

Stack: Error: Failed to start the React Native packager: Current workspace is not a React Native project.
    at Function.getWrappedError (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/common/error/internalError.js:35:16)
    at Function.wrapError (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/common/error/errorHelper.js:18:44)
    at resultOfCode.done.reason (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/common/entryPointHandler.js:43:72)
    at _rejected (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:844:24)
    at /home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:870:30
    at Promise.when (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:788:41)
    at /home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:604:44
    at runSingle (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:137:13)
    at flush (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Error] Failed to run the application in Android

Stack: Error: Failed to run the application in Android: Current workspace is not a React Native project.
    at Function.getWrappedError (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/common/error/internalError.js:35:16)
    at Function.wrapError (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/common/error/errorHelper.js:18:44)
    at resultOfCode.done.reason (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/common/entryPointHandler.js:43:72)
    at _rejected (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:844:24)
    at /home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:870:30
    at Promise.when (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:788:41)
    at /home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:604:44
    at runSingle (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:137:13)
    at flush (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Error] Failed to run the application in Android

Stack: Error: Failed to run the application in Android: Current workspace is not a React Native project.
    at Function.getWrappedError (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/common/error/internalError.js:35:16)
    at Function.wrapError (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/common/error/errorHelper.js:18:44)
    at resultOfCode.done.reason (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/common/entryPointHandler.js:43:72)
    at _rejected (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:844:24)
    at /home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:870:30
    at Promise.when (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:788:41)
    at /home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:604:44
    at runSingle (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:137:13)
    at flush (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

- Output (Developer Tools Console)
```
notificationsAlerts.ts:40 Error: Current workspace is not a React Native project.
    at Function.selectProject (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/extension/commandPaletteHandler.js:283:29)
    at Function.runAndroid (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/extension/commandPaletteHandler.js:87:21)
    at registerVSCodeCommand (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/extension/rn-extension.js:160:215)
    at generator.time (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/common/telemetryHelper.js:61:41)
    at TelemetryGenerator.time (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/common/telemetryGenerators.js:54:18)
    at Function.generate (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/common/telemetryHelper.js:61:26)
    at EntryPointHandler.runFunctionWExtProps (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/common/entryPointHandler.js:26:75)
    at context.subscriptions.push.vscode.commands.registerCommand (/home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13/src/extension/rn-extension.js:180:34)
    at e._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:697:706)
    at e.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:698:212)
    at e._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:87)
    at e._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:657:779)
    at e._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:656:851)
    at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:656:620)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:655:544
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:673
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:96:599
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:97:917)
    at u (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:159:721)
    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:159:898)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```
```

**Comment by iTOYS** [comment] 2018-07-24 06:58
Hi @dominictwlee 
Could you please open terminal in your VSCode and execute `react-native -v` and paste output here.

Thanks!

**Comment by dominictwlee** [comment] 2018-07-24 22:22
Sure, It's:

```
react-native-cli: 2.0.1
react-native: 0.56.0
```

**Comment by ruslan-bikkinin** [comment] 2018-07-25 07:42
Hi @dominictwlee what directory do you open? Is it root of react native project?

**Comment by dominictwlee** [comment] 2018-07-25 12:57
@ruslan-bikkinin Yep, root of react-native project created with ```react-native init```.
```react-native run-android``` works, but none of the commands in vscode are working.

**Comment by dominictwlee** [comment] 2018-07-25 19:58
@ruslan-bikkinin The only messages I get are from the Developer tools console and output as shown in my 1st post.

**Comment by ruslan-bikkinin** [comment] 2018-07-26 10:07
@dominictwlee I could reproduce your problem by installing *react-native* package (*not react-native-cli!*) globally and then by executing `React Native > Run Packager` command. In this case:
1. Please, check that you have installed `react-native-cli` package globally, not `react-native`.
2. If you are using nvm, please check that node versions that are available in VS Code and in system terminal are the same. Sometimes that could be a root of problems.

Please let us know if it helps you.

**Comment by dominictwlee** [comment] 2018-07-26 10:22
@ruslan-bikkinin 
So nvm node version has to match whatever is shown here?

![screenshot from 2018-07-09 15-28-58](https://user-images.githubusercontent.com/34794189/43256885-18b733b6-90c6-11e8-861d-de6aa3172ad2.png)

**Comment by ruslan-bikkinin** [comment] 2018-07-26 10:37
@dominictwlee could you please show screenshot of your project opened in VS Code after error being occured?

**Comment by ruslan-bikkinin** [comment] 2018-07-27 07:53
@dominictwlee What extension, among React Native Tools, do you have installed?

**Comment by dominictwlee** [comment] 2018-07-27 07:58
@ruslan-bikkinin 
![screenshot from 2018-07-27 08-57-44](https://user-images.githubusercontent.com/34794189/43308961-3cdfd0ee-917b-11e8-8de7-f9f5a6e98d8e.png)
![screenshot from 2018-07-27 08-56-55](https://user-images.githubusercontent.com/34794189/43308962-3cfa9280-917b-11e8-9a4a-33fa1abfa46c.png)

**Comment by iTOYS** [comment] 2018-07-27 08:37
@dominictwlee 
Could you please check your settings(both user and workspace settings).
https://code.visualstudio.com/docs/getstarted/settings
Especially `react-native-tools.projectRoot`

**Comment by dominictwlee** [comment] 2018-07-27 14:20
@iTOYS  ```react-native-tools.projectRoot``` is using the default "". 

My other settings are:
```
{
    "workbench.colorTheme": "Material Theme",
    "files.autoSave": "off",
    "editor.tabSize": 2,
    "editor.wordWrap": "on",
    "editor.formatOnSave": true,
    "window.zoomLevel": 0,
    "emmet.syntaxProfiles": {
        "javascript": "javascriptreact"
    },
    "files.associations": {
        "*.js": "javascriptreact"
    },
    "workbench.iconTheme": "eq-material-theme-icons",
    "materialTheme.fixIconsRunning": false,
    "workbench.statusBar.visible": true,
    "workbench.activityBar.visible": true,
    "prettier.requireConfig": true,
    "terminal.integrated.fontSize": 15,
    "typescript.validate.enable": false,
    "typescript.format.enable": false,
    "javascript.validate.enable": false,
    "emmet.triggerExpansionOnTab": true,
    "flow.useNPMPackagedFlow": true
}
```

**Comment by ruslan-bikkinin** [comment] 2018-07-27 15:01
@dominictwlee what is the full path to `package.json` file? Seems to be that problem line is 
https://github.com/Microsoft/vscode-react-native/blob/2c82a3f990836260c11640db528a30590867bb8a/src/common/reactNativeProjectHelper.ts#L25

and `fs.existsSync` method in your case unexpectedly returns false.
It is hard to say what's wrong in your particular case, so the only thing that I can suggest you is to try to debug extension itself on your side.
The instructions for that are the following:

1. Run these commands in terminal: 
`git clone https://github.com/Microsoft/vscode-react-native.git`
`cd vscode-react-native`
`npm i -g gulp && npm i`
2. Open extension project in VS Code, then run `Quick Extension + Debugger` debug configuration:
![image](https://user-images.githubusercontent.com/30265843/43328162-f20c9b42-91c5-11e8-8f17-4f5f6e9ca6fa.png). 
It should start new VS Code instance and debugger for the extension. You should see message like  `[/media/rbikkinin/work/projects/vscode-react-native]: Overwriting extension /home/rbikkinin/.vscode/extensions/vsmobile.vscode-react-native-0.6.13 with /media/rbikkinin/work/projects/vscode-react-native.`.
3. Set breakpoint at `vscode-react-native/src/common/reactNativeProjectHelper.ts:25`
4. In just opened VS Code instance open you app directory and execute `Run Packager` command.
5. Wait until breakpoint being hit and try to find out why your problem happens.

**Comment by dominictwlee** [comment] 2018-07-29 17:09
@ruslan-bikkinin  Got this message when I completed tasks 1 and 2, any ideas why? 

![screenshot from 2018-07-29 18-08-40](https://user-images.githubusercontent.com/34794189/43368780-942dc172-935a-11e8-889f-a73744ede71d.png)

Should I go ahead and click debug anyway?

**Comment by ruslan-bikkinin** [comment] 2018-07-30 07:58
@dominictwlee Did you restart vscode after 1, 2 steps? Seems to be that it couldn't find quick-build task, that is defined in gulpfile.js. You can check whether it exists by clicking `Tasks -> Run tasks...` and wait a little bit for VSCode to process.

**Comment by dominictwlee** [comment] 2018-07-30 21:27
I'm getting this in the console output:
```Gulp is not installed on your system. Run npm install -g gulp to install it.```

The only thing I can think of is that vscode isn't detecting the folder where nvm saves it's global modules.

Any ideas?

**Comment by ruslan-bikkinin** [comment] 2018-07-31 07:44
@dominictwlee You can try to remove `node_modules/.bin` folder.

**Comment by dominictwlee** [comment] 2018-07-31 22:04
@ruslan-bikkinin Deleted node_modules/.bin file, and the same warning still popped up so I clicked Debug anyway.

2nd VScode popped up with message ```[/home/domtwlee/Projects/vscode-react-native]: Overwriting extension /home/domtwlee/.vscode/extensions/vsmobile.vscode-react-native-0.6.13 with /home/domtwlee/Projects/vscode-react-native.```.

![unverified-breakpoints](https://user-images.githubusercontent.com/34794189/43489678-b7df9246-9515-11e8-9120-a492658bd9df.png)

Unverified breakpoints when attempting to set them on the 1st vscode window where debugger is running.

![listontimeout](https://user-images.githubusercontent.com/34794189/43489790-0fd1cabe-9516-11e8-920a-3105971cb67f.png)
This shows up when I click on debugger restart.

**Comment by iTOYS** [comment] 2018-08-01 09:45
@dominictwlee 
Could you please try to delete `nvm` and install nodejs directly

Thanks!

**Comment by ruslan-bikkinin** [comment] 2018-08-01 11:54
@dominictwlee Also you can try to set default node version by executing `nvm alias default NEEDED_VERSION`.

**Comment by dominictwlee** [comment] 2018-08-01 19:30
@iTOYS  @ruslan-bikkinin 

Tried setting ```nvm alias default``` and didn't make a difference.

So what I did was comment out nvm commands from my .bashrc and installed nodejs directly.

debugger is working and projectRoot is showing up as ```"/home/domtwlee/Projects/testDebugger"``` which is the right path.

So are you saying that vscode-react-native is incompatible with nvm?

**Comment by ruslan-bikkinin** [comment] 2018-08-02 08:27
@dominictwlee No exactly, I use nvm as well during my development on Ubuntu including debugging RN apps and extension - just in your particular case something goes wrong. Could you please do the following:
* run `nvm ls` in system terminal and in VS Code integrated terminal and show us the output?
* run `cat ~/.npmrc`, `cat ~/.bashrc`, `cat ~/.bash_profile` and show us the output?

**Comment by ruslan-bikkinin** [comment] 2018-08-07 10:12
@dominictwlee all seems to be in order here. How do you run VS Code? Could you please try to run it from terminal via `code` and let us know if issue still persists?
Also, please, make sure that you have no remains of another node instances in your path which have been installed not via nvm (potential directories are `/usr/bin`, `usr/local/bin` and so on).

**Comment by dominictwlee** [comment] 2018-08-10 22:54
@ruslan-bikkinin I managed to get it work by doing bash```nvm use default && code``` in the main terminal, but it stops working everytime I reload/open a folder/open a workspace. Any solutions to this? Because I can see this becoming really annoying.

**Comment by ruslan-bikkinin** [comment] 2018-08-13 11:10
@dominictwlee I think that this is mostly vscode and nvm issue rather than extension one, because all we do in extension that is lead to the problem you described in first post is running a `react-native -v` command by `childProcess.spawn("react-native",["-v"], { cwd: YOUR_RPOJECT_DIRECTORY })` . In your case it fails because seems to be that there is no available `react-native` command in PATH. I have no clues for now, why nvm doesn't work in your case, I'd recommend you to do the following steps that I did when I was trying to make nvm works on my machine:
1. Remove nvm and any other node instances that could be installed.
2. Install nvm
3. Run the following commands in system terminal, considering that v10.4.0 is your main node version:
```
nvm install v10.4.0
nvm use v10.4.0
nvm alias default v10.4.0
```
4. Install other node versions via nvm if needed

**Comment by ruslan-bikkinin** [comment] 2018-08-16 14:38
@dominictwlee do you have a chance to look at it?

**Comment by dominictwlee** [comment] 2018-08-16 21:07
@ruslan-bikkinin Yeah tried that, still have to declare nvm use default and launch code from terminal in order for things to work. I guess that'll have to do for now.

**Comment by ruslan-bikkinin** [comment] 2018-08-20 08:38
@dominictwlee could you please [submit issue](https://github.com/Microsoft/vscode/issues/new?template=bug_report.md) in vscode repo and share the link here? As soon as you do that, I join to discussion there.

**Comment by ruslan-bikkinin** [comment] 2018-11-14 14:57
@dominictwlee I am going to close this due to you already have an issue in vscode and we still don't have any strong evidence that the extension causes your problem. Also, please take a look at my recent comment https://github.com/Microsoft/vscode/issues/56890#issuecomment-436650669.

**Closed by ruslan-bikkinin** 2018-11-14 14:57 UTC
Labels: external, need-more-info

**Comment by iosToTop** [comment] 2020-04-29 06:14
I fixed this by change my wifi to use my phone 4G.
But when i change my wifi to office.The problem also with me.
So i don't know what the question now!!

**Comment by RedMickey** [comment] 2020-04-29 07:54
Hi @iosToTop, please open a new issue according to [our issue template](https://github.com/microsoft/vscode-react-native/blob/master/.github/ISSUE_TEMPLATE.md) and describe your problem in details.
