### ISSUE TITLE
breakpoints set but not yet bound

### ISSUE THREAD

**Issue by novellizator** [Microsoft/vscode-react-native#630] opened 2018-02-16 09:09 UTC
## Actual Behavior
1. program doesn't stop at any breakpoints

## Expected Behavior
1. program should stop at breakpoints

It used to work, now it doesn't work on any project now.
It does stop on `debugger` expression in code though.
 Is something wrong with the extension, or is it a potential problem with sourcemaps? If so, if there any easy way to find out, or to solve it? 

## Software versions
- React-Native VS Code extension version: 0.5.7
- VSCode version: 1.20.1
- OS platform and version: macOS
- NodeJS version: according to console "Adapter node: v7.9.0 x64", but when run in shell it's 8.9.0
- React Native version: 0.53.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.18.5
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 9684
Module RCTImageLoader requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
RCTLog.js:48
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by sergey-akhalkov** [comment] 2018-02-16 09:25
Hi @novellizator, thanks for reaching us and for filling the issue details. I'm closing this as duplicate of https://github.com/Microsoft/vscode-react-native/issues/625 , so please let's have a discussion in the one common issue.

Please let us know if you have any questions or see any other issues.

**Closed by sergey-akhalkov** 2018-02-16 09:25 UTC
Labels: duplicate
