### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by yuyuyoyo** [microsoft/vscode-react-native#1588] opened 2021-06-10 09:39 UTC
# 🐛 What is the bug? How can we reproduce it?

> 
![image](https://user-images.githubusercontent.com/85676324/121501522-83d19900-ca09-11eb-8b27-8034edb8a645.png)

I just use react-native run-android but is not working has error. How I solve the problem?

* React Native Tools extension version: 2.0.1 VERSION

**Comment by RedMickey** [comment] 2021-06-10 11:21
Hi @yuyuyoyo and thanks for reaching us.
It seems that the issue is connected to PowerShell script execution policy. It is not an issue of the extension.
You can try to change your script execution policy if you have administrator rights the following way:
* Start Windows PowerShell with the "Run as Administrator" option
* Enable running unsigned scripts using the command:
  ```
  Set-ExecutionPolicy RemoteSigned
  ```
  You can also change this policy for the CurrentUser scope the following way:
  ```
  Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
  ```

After that you will be able to run unsigned scripts that you write on your local computer and signed scripts from the Internet.
You can find more info about execution policies [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.1).

**Comment by yuyuyoyo** [comment] 2021-06-11 06:48
Sorry command show this?

- Start Windows PowerShell with the "Run as Administrator" option

- Enable running unsigned scripts using the command:

        Set-ExecutionPolicy** RemoteSigned

![image](https://user-images.githubusercontent.com/85676324/121642957-6d841580-cabb-11eb-9581-e3592cd287ba.png)

**Comment by RedMickey** [comment] 2021-06-11 07:29
@yuyuyoyo, It seems that you opened Command Prompt instead of Windows PowerShell which is used in VS Code terminal.
![image](https://user-images.githubusercontent.com/33267199/121647754-7109a380-ca9f-11eb-9f42-6fcadb970d10.png)

![image](https://user-images.githubusercontent.com/33267199/121647237-ddd06e00-ca9e-11eb-8fbb-7f9f595f9f24.png)

The command `Set-ExecutionPolicy RemoteSigned` is only available in Windows PowerShell.
Could you please try to execute it in Windows PowerShell console?

**Comment by yuyuyoyo** [comment] 2021-06-11 07:44
![image](https://user-images.githubusercontent.com/85676324/121650203-8690c480-cac3-11eb-89d9-32bee0c097c5.png)

**Comment by RedMickey** [comment] 2021-06-11 07:53
@yuyuyoyo If you are agree with the message, type `Y` and click enter. I think it's better to reload VS Code after that, so the settings take effect.

**Comment by yuyuyoyo** [comment] 2021-06-11 07:57
![image](https://user-images.githubusercontent.com/85676324/121651735-2569f080-cac5-11eb-97c1-114a178dacae.png)

Finish right? And then I try this?

You can also change this policy for the CurrentUser scope the following way:
       Set-ExecutionPolicy RemoteSigned -Scope CurrentUser

**Comment by RedMickey** [comment] 2021-06-11 08:01
To execute the command correctly, PowerShell should be opened with administrator rights via the `Run as Administrator` option.
![image](https://user-images.githubusercontent.com/33267199/121652297-2c343b80-caa4-11eb-8446-991d7d4666ae.png)

**Comment by yuyuyoyo** [comment] 2021-06-11 09:45
Thank you very much I can do this in VS code already 👍

**Comment by RedMickey** [comment] 2021-06-11 10:44
Awesome, I was glad to help you! I’m closing this issue, please feel free to open new ones if needed

**Closed by RedMickey** 2021-06-11 10:44 UTC
Labels: bug
