### ISSUE TITLE
3/0,[Bug] Bug description

### ISSUE THREAD

**Issue by sss6672** [microsoft/vscode-react-native#1718] opened 2022-01-03 20:11 UTC
# 🐛 What is the bug? How can we reproduce it?

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. Step 1
2. Step 2

## Expected behavior

What were you expecting to happen?

## Debug output

<details>
<summary>Debug Console</summary>

```text

PASTE OUTPUT OF DEBUG CONSOLE (View -> Toggle Debug Console)

```
</details>

<details>
<summary>React Native output channel</summary>

```text

PASTE OUTPUT OF REACT-NATIVE OUTPUT CHANNEL (View -> Toggle Output -> Select React-Native in ListBox)

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

PASTE OUTPUT OF DEVELOPER TOOLS CONSOLE (Help -> Toggle Developer Tools -> Select Console tab)

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
PASTE OUTPUT OF `npx react-native doctor` or `npx expo doctor`
```

* `envinfo`:

```text
PASTE OUTPUT OF `npx envinfo`
```

* React Native Tools extension version: VERSION
* Expo SDK version (if applicable): VERSION

**Comment by RedMickey** [comment] 2022-01-10 15:38
Closing this as a duplicate of the issue https://github.com/microsoft/vscode-react-native/issues/1719.

**Closed by RedMickey** 2022-01-10 15:38 UTC
Labels: bug, duplicate
