### ISSUE TITLE
Error while executing command 'react-native.cmd run-android --no-packager': Error while executing command 'react-native.cmd run-android --no-packager' (error code 101)

### ISSUE THREAD

**Issue by galla-devlop** [microsoft/vscode-react-native#1141] opened 2019-10-16 09:29 UTC
## Actual Behavior
1. Error while executing command 'react-native.cmd run-android --no-packager': Error while executing command 'react-native.cmd run-android --no-packager' (error code 101)

## Expected Behavior
1. Start Debugging

## Software versions
- VSCode version: 1.33.1
- OS platform and version: Windows_NT x64 10.0.17763
- NodeJS version: 10.2.0
- react-native-cli: 2.0.1
-react-native: 0.61.2

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
OS: win32 x64
Adapter node: v10.2.0 x64
vscode-chrome-debug-core: 6.8.2
Could not debug. Error while executing command 'react-native.cmd run-android --no-packager': Error while executing command 'react-native.cmd run-android --no-packager' (error code 101)
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
[Warning] Target simulator is not supported for Android platform. 
 If you want to use particular device or simulator for launching Android app,
 please specify  device id (as in 'adb devices' output) instead.

[Info] local.properties file doesn't exist. Using Android SDK location from PATH.

[Info] Starting React Native Packager.

error Unrecognized command "run-android".
info Run "react-native --help" to see a list of all available commands.
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
[Extension Host] debugger listening on port 26104
console.ts:134 [Extension Host] (node:58948) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:134
extensionHost.ts:215 Extension Host
extensionHost.ts:216 Debugger attached.

console.ts:134 [Extension Host] (node:58948) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```
PASTE OUTPUT HERE
```

**Comment by SounD120** [comment] 2019-10-16 10:09
Hi @galla-devlop . Thanks for reaching us. Does the `react-native run-android` terminal command work for your project?

**Comment by galla-devlop** [comment] 2019-10-16 10:12
Hi.. Thanks for the quick reply. 
Not worked i got the below error ,
Error while executing command 'react-native.cmd run-android --no-packager': Error while executing command 'react-native.cmd run-android --no-packager' (error code 101)

**Comment by SounD120** [comment] 2019-10-16 10:14
@galla-devlop Did you ran that command in terminal? Could you please try to run that command and send us outputs? It will be helpful for better understanding the situation from our side.

**Comment by galla-devlop** [comment] 2019-10-16 10:23
@SounD120  , I had done the following steps , 
npm uninstall -g react-native-cli
npm uninstall -g @react-native-community/cli
\npm>npm install -g react-native-cli

after that again i ran the following command. now this is the error i am getting 

 C:\Users\40003827\AppData\Roaming\npm\SmapleApp> react-native run-android
error Unrecognized command "run-android".
info Run "react-native --help" to see a list of all available commands.

**Comment by SounD120** [comment] 2019-10-16 10:29
@galla-devlop Ok, then could you please try to run this command in the freshly created app and let us know how it works for you? 
You can use the following commands for that:
```
react-native init newApp
cd newApp
react-native run-android
```

**Comment by galla-devlop** [comment] 2019-10-16 10:42
@SounD120  kindly find the below attached image for above commands output.
![Capture-react_error](https://user-images.githubusercontent.com/53257871/66912169-b4441280-f02f-11e9-988f-82bf1b1ddaa1.PNG)

**Comment by SounD120** [comment] 2019-10-16 11:16
@galla-devlop It seems that the folder with global npm packages is not in your PATH environment variable.
To add it you can run the following Powershell script to add it and then try to run the `Debug Android` scenario:
```
[Environment]::SetEnvironmentVariable("Path", [System.Environment]::GetEnvironmentVariable('PATH', 'user') + ";C:\Users\40003827\AppData\Roaming\npm", [System.EnvironmentVariableTarget]::User)
```

**Comment by galla-devlop** [comment] 2019-10-16 12:34
@SounD120  i am getting this error , while running
C:\Users\40003827\AppData\Roaming\npm>[Environment]::SetEnvironmentVariable("Path", [System.Environment]::GetEnvironmentVariable('PATH', 'user') + ";C:\Users\40003827\AppData\Roaming\npm", [System.EnvironmentVariableTarget]::User)
The filename, directory name, or volume label syntax is incorrect.

**Comment by SounD120** [comment] 2019-10-16 12:39
@galla-devlop This is a Powershell script, it shouldn't work in CMD. To run it you can execute Powershell from CMD and then run the command. You can use the following script for that:
```
powershell
[Environment]::SetEnvironmentVariable("Path", [System.Environment]::GetEnvironmentVariable('PATH', 'user') + ";C:\Users\40003827\AppData\Roaming\npm", [System.EnvironmentVariableTarget]::User)
```

**Comment by galla-devlop** [comment] 2019-10-16 12:47
@SounD120 , still i am getting same error . Script executed perfectly . After that i ran run-android command .

C:\Users\40003827\AppData\Roaming\npm\SmapleApp>react-native run-android
error Unrecognized command "run-android".
info Run "react-native --help" to see a list of all available commands.

**Comment by SounD120** [comment] 2019-10-16 12:49
@galla-devlop Now please try on a freshly created app.

**Comment by galla-devlop** [comment] 2019-10-16 13:06
@SounD120 , thanks for quick reply. 
i followed you steps, now i am not getting previous error. while building app i got one different error . 
i am attaching the error file , kindly help me on this.
[Error_While Installing.txt](https://github.com/microsoft/vscode-react-native/files/3734425/Error_While.Installing.txt)

**Comment by SounD120** [comment] 2019-10-17 09:07
@galla-devlop 
1) With respect to errors in a freshly created app, I'd recommend to clear your Gradle caches with following commands and then try to build an application:
```
gradle clean --refresh-dependencies
RD /Q /S %USERPROFILE%\.gradle\caches
```
2) With respect to `SmapleApp` application error I'd recommend you to reinstall `node_modules` and then try to run `Debug Android`. To do that you can use the following commands from your `SmapleApp` project root:
```
RD /Q /S node_modules
npm install
```
Could you please try that recommendations and let us know about the results?

**Comment by galla-devlop** [comment] 2019-10-17 09:38
@SounD120 
where should i try the above commands, i am getting confused bcz i am getting not recognized gradle error.

**Comment by SounD120** [comment] 2019-10-17 09:43
@galla-devlop Try it from your project android directory. Also please use `gradlew` instead of `gradle` in such case.

**Comment by galla-devlop** [comment] 2019-10-17 09:59
@SounD120 

i tired to run the above commands, i am getting following error 


D:\LearningWS\React Native\FirstApp\newApp\android>gradlew clean --refresh-dependencies

> Configure project :
[Fatal Error] jvnet-parent-4.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'newApp'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
     Required by:
         project : > com.android.tools.build:gradle:3.4.2 > com.android.tools.build:builder:3.4.2 > com.android.tools:sdklib:26.4.2 > com.android.tools:repository:26.4.2
      > Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
         > Could not parse POM https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.pom
            > Could not resolve com.sun.xml.bind.mvn:jaxb-runtime-parent:2.2.11.
               > Could not resolve com.sun.xml.bind.mvn:jaxb-runtime-parent:2.2.11.
                  > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-runtime-parent/2.2.11/jaxb-runtime-parent-2.2.11.pom
                     > Could not resolve com.sun.xml.bind.mvn:jaxb-parent:2.2.11.
                        > Could not resolve com.sun.xml.bind.mvn:jaxb-parent:2.2.11.
                           > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-parent/2.2.11/jaxb-parent-2.2.11.pom
                              > Could not resolve com.sun.xml.bind:jaxb-bom-ext:2.2.11.
                                 > Could not resolve com.sun.xml.bind:jaxb-bom-ext:2.2.11.
                                    > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/jaxb-bom-ext/2.2.11/jaxb-bom-ext-2.2.11.pom
                                       > Could not resolve org.glassfish.jaxb:jaxb-bom:2.2.11.
                                          > Could not resolve org.glassfish.jaxb:jaxb-bom:2.2.11.
                                             > Could not parse POM https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-bom/2.2.11/jaxb-bom-2.2.11.pom
                                                > Could not resolve net.java:jvnet-parent:4.
                                                   > Could not resolve net.java:jvnet-parent:4.
                                                      > Could not parse POM https://jcenter.bintray.com/net/java/jvnet-parent/4/jvnet-parent-4.pom
                                                         > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 36s

**Comment by SounD120** [comment] 2019-10-17 10:13
@galla-devlop It looks like there is misconfiguration lying deeply inside your Android SDK environment. I recommend you to go through the [official React Native Getting Started guide](https://facebook.github.io/react-native/docs/getting-started.html) and check that your environment tuned correctly for React Native applications, because build errors reproduces without the extension at all.

**Comment by galla-devlop** [comment] 2019-10-17 10:18
@SounD120 
i already followed official document for setting environment steps. but still it's giving same issue.

**Comment by galla-devlop** [comment] 2019-10-17 10:20
@SounD120 
It's not related to environment based on following output i am predicting.

[Warning] Error: Packager is still running. If the packager was started outside VS Code, please quit the packager process using the task manager.

[Info] Packager is already running.

[Warning] Error: React Native Packager running outside of VS Code. If you want to debug please use the 'Attach to packager' option

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=android

[Info] Building and running application.

[Error] Error: Error while executing command 'react-native.cmd run-android --no-packager': Error while executing command 'react-native.cmd run-android --no-packager' (error code 101)

[Info] Starting Packager

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   d:\LearningWS\React Native\FirstApp\newApp 

[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=android

Loading dependency graph, done.
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (457/457), done.

[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

[Error] Error: Error while executing command 'react-native.cmd run-android --no-packager': Error while executing command 'react-native.cmd run-android --no-packager' (error code 101)

**Comment by SounD120** [comment] 2019-10-17 10:50
@galla-devlop Could you please also attach outputs from React Native: Run Android output channel?

**Comment by galla-devlop** [comment] 2019-10-17 11:51
@SounD120 

[Warning] Target simulator is not supported for Android platform. 
 If you want to use particular device or simulator for launching Android app,
 please specify  device id (as in 'adb devices' output) instead.

[Info] local.properties file doesn't exist. Using Android SDK location from PATH.

[Info] Starting React Native Packager.

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 863 file(s) to forward-jetify. Using 4 workers...
info Installing the app...

> Configure project :
[Fatal Error] jvnet-parent-4.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'newApp'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
     Required by:
         project : > com.android.tools.build:gradle:3.4.2 > com.android.tools.build:builder:3.4.2 > com.android.tools:sdklib:26.4.2 > com.android.tools:repository:26.4.2
      > Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
         > Could not parse POM https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.pom
            > Could not resolve com.sun.xml.bind.mvn:jaxb-runtime-parent:2.2.11.
               > Could not resolve com.sun.xml.bind.mvn:jaxb-runtime-parent:2.2.11.
                  > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-runtime-parent/2.2.11/jaxb-runtime-parent-2.2.11.pom
                     > Could not resolve com.sun.xml.bind.mvn:jaxb-parent:2.2.11.
                        > Could not resolve com.sun.xml.bind.mvn:jaxb-parent:2.2.11.
                           > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-parent/2.2.11/jaxb-parent-2.2.11.pom
                              > Could not resolve com.sun.xml.bind:jaxb-bom-ext:2.2.11.
                                 > Could not resolve com.sun.xml.bind:jaxb-bom-ext:2.2.11.
                                    > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/jaxb-bom-ext/2.2.11/jaxb-bom-ext-2.2.11.pom
                                       > Could not resolve org.glassfish.jaxb:jaxb-bom:2.2.11.
                                          > Could not resolve org.glassfish.jaxb:jaxb-bom:2.2.11.
                                             > Could not parse POM https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-bom/2.2.11/jaxb-bom-2.2.11.pom
                                                > Could not resolve net.java:jvnet-parent:4.
                                                   > Could not resolve net.java:jvnet-parent:4.
                                                      > Could not parse POM https://jcenter.bintray.com/net/java/jvnet-parent/4/jvnet-parent-4.pom
                                                         > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 12s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
[Fatal Error] jvnet-parent-4.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'newApp'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
     Required by:
         project : > com.android.tools.build:gradle:3.4.2 > com.android.tools.build:builder:3.4.2 > com.android.tools:sdklib:26.4.2 > com.android.tools:repository:26.4.2
      > Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
         > Could not parse POM https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.pom
            > Could not resolve com.sun.xml.bind.mvn:jaxb-runtime-parent:2.2.11.
               > Could not resolve com.sun.xml.bind.mvn:jaxb-runtime-parent:2.2.11.
                  > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-runtime-parent/2.2.11/jaxb-runtime-parent-2.2.11.pom
                     > Could not resolve com.sun.xml.bind.mvn:jaxb-parent:2.2.11.
                        > Could not resolve com.sun.xml.bind.mvn:jaxb-parent:2.2.11.
                           > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-parent/2.2.11/jaxb-parent-2.2.11.pom
                              > Could not resolve com.sun.xml.bind:jaxb-bom-ext:2.2.11.
                                 > Could not resolve com.sun.xml.bind:jaxb-bom-ext:2.2.11.
                                    > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/jaxb-bom-ext/2.2.11/jaxb-bom-ext-2.2.11.pom
                                       > Could not resolve org.glassfish.jaxb:jaxb-bom:2.2.11.
                                          > Could not resolve org.glassfish.jaxb:jaxb-bom:2.2.11.
                                             > Could not parse POM https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-bom/2.2.11/jaxb-bom-2.2.11.pom
                                                > Could not resolve net.java:jvnet-parent:4.
                                                   > Could not resolve net.java:jvnet-parent:4.
                                                      > Could not parse POM https://jcenter.bintray.com/net/java/jvnet-parent/4/jvnet-parent-4.pom
                                                         > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 12s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (d:\LearningWS\React Native\FirstApp\newApp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at buildAndRun (d:\LearningWS\React Native\FirstApp\newApp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at Object.runAndroid [as func] (d:\LearningWS\React Native\FirstApp\newApp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:106:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by galla-devlop** [comment] 2019-10-17 11:59
@SounD120 
While cleaning gradle i am getting following error 

D:\LearningWS\React Native\FirstApp\newApp\android>gradlew clean

> Configure project :
[Fatal Error] jvnet-parent-4.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'newApp'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
     Required by:
         project : > com.android.tools.build:gradle:3.4.2 > com.android.tools.build:builder:3.4.2 > com.android.tools:sdklib:26.4.2 > com.android.tools:repository:26.4.2
      > Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
         > Could not parse POM https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.pom
            > Could not resolve com.sun.xml.bind.mvn:jaxb-runtime-parent:2.2.11.
               > Could not resolve com.sun.xml.bind.mvn:jaxb-runtime-parent:2.2.11.
                  > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-runtime-parent/2.2.11/jaxb-runtime-parent-2.2.11.pom
                     > Could not resolve com.sun.xml.bind.mvn:jaxb-parent:2.2.11.
                        > Could not resolve com.sun.xml.bind.mvn:jaxb-parent:2.2.11.
                           > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-parent/2.2.11/jaxb-parent-2.2.11.pom
                              > Could not resolve com.sun.xml.bind:jaxb-bom-ext:2.2.11.
                                 > Could not resolve com.sun.xml.bind:jaxb-bom-ext:2.2.11.
                                    > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/jaxb-bom-ext/2.2.11/jaxb-bom-ext-2.2.11.pom
                                       > Could not resolve org.glassfish.jaxb:jaxb-bom:2.2.11.
                                          > Could not resolve org.glassfish.jaxb:jaxb-bom:2.2.11.
                                             > Could not parse POM https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-bom/2.2.11/jaxb-bom-2.2.11.pom
                                                > Could not resolve net.java:jvnet-parent:4.
                                                   > Could not resolve net.java:jvnet-parent:4.
                                                      > Could not parse POM https://jcenter.bintray.com/net/java/jvnet-parent/4/jvnet-parent-4.pom
                                                         > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 14s

D:\LearningWS\React Native\FirstApp\newApp\android>

**Comment by SounD120** [comment] 2019-10-17 12:02
@galla-devlop As seen from your logs it is the same error which has been reproduced without extension. I recommend you to clean your gradle build cache with the following command from your project android root folder:
```
gradlew cleanBuildCache
```

**Comment by galla-devlop** [comment] 2019-10-17 12:07
@SounD120 
i have done the same , see the error 


D:\LearningWS\React Native\FirstApp\newApp\android>gradlew cleanBuildCache

> Configure project :
[Fatal Error] jvnet-parent-4.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'newApp'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
     Required by:
         project : > com.android.tools.build:gradle:3.4.2 > com.android.tools.build:builder:3.4.2 > com.android.tools:sdklib:26.4.2 > com.android.tools:repository:26.4.2
      > Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
         > Could not parse POM https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.pom
            > Could not resolve com.sun.xml.bind.mvn:jaxb-runtime-parent:2.2.11.
               > Could not resolve com.sun.xml.bind.mvn:jaxb-runtime-parent:2.2.11.
                  > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-runtime-parent/2.2.11/jaxb-runtime-parent-2.2.11.pom
                     > Could not resolve com.sun.xml.bind.mvn:jaxb-parent:2.2.11.
                        > Could not resolve com.sun.xml.bind.mvn:jaxb-parent:2.2.11.
                           > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/mvn/jaxb-parent/2.2.11/jaxb-parent-2.2.11.pom
                              > Could not resolve com.sun.xml.bind:jaxb-bom-ext:2.2.11.
                                 > Could not resolve com.sun.xml.bind:jaxb-bom-ext:2.2.11.
                                    > Could not parse POM https://jcenter.bintray.com/com/sun/xml/bind/jaxb-bom-ext/2.2.11/jaxb-bom-ext-2.2.11.pom
                                       > Could not resolve org.glassfish.jaxb:jaxb-bom:2.2.11.
                                          > Could not resolve org.glassfish.jaxb:jaxb-bom:2.2.11.
                                             > Could not parse POM https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-bom/2.2.11/jaxb-bom-2.2.11.pom
                                                > Could not resolve net.java:jvnet-parent:4.
                                                   > Could not resolve net.java:jvnet-parent:4.
                                                      > Could not parse POM https://jcenter.bintray.com/net/java/jvnet-parent/4/jvnet-parent-4.pom
                                                         > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 16s

D:\LearningWS\React Native\FirstApp\newApp\android>

**Comment by SounD120** [comment] 2019-10-18 10:56
@galla-devlop Your issue is lying somewhere deep inside Android SDK configuration, so I'd recommend you to reinstall all your React Native environment using the [official React Native getting started instruction](https://facebook.github.io/react-native/docs/getting-started.html). 
I am also recommend to post your issue in [React Native repository](https://github.com/facebook/react-native) if it persists after that. 
I am closing that issue because that issue is reproduced without an extension at all.
Please feel free to re-open if you face a problem with extension usage.

**Closed by SounD120** 2019-10-18 10:56 UTC
Labels: android, need-more-info

**Comment by akashrao1991** [comment] 2021-01-13 13:28
Hello,
I am facing the same issue.
the error says : 
An error occurred while launching the application. Error while executing command 
'd:\programming\Aclize\custom_build\MyApplication\node_modules\.bin\react-native.cmd run-android --no-packager': Error while executing command 'd:\programming\Aclize\custom_build\MyApplication\node_modules\.bin\react-native.cmd run-android --no-packager' (error code 101) (error code 303)

**Comment by RedMickey** [comment] 2021-01-13 14:16
Hi @akashrao1991   and thanks for reaching us. Please create a new issue for your specific case and describe your problem using our [issue template](https://github.com/microsoft/vscode-react-native/blob/master/.github/ISSUE_TEMPLATE/1-bug-report.md).

**Comment by thexdd** [comment] 2022-05-09 13:13
> Hello,
> I am facing the same issue.
> the error says :
> An error occurred while launching the application. Error while executing command
> 'd:\programming\Aclize\custom_build\MyApplication\node_modules.bin\react-native.cmd run-android --no-packager': Error while executing command 'd:\programming\Aclize\custom_build\MyApplication\node_modules.bin\react-native.cmd run-android --no-packager' (error code 101) (error code 303)

have you found any solution to this problem? I am having the same issue...
