### ISSUE TITLE
[Bug] An error occurred while launching the application. Error while executing command 'npm install @expo/xdl @expo/ngrok --verbose --no-save' on npm 7

### ISSUE THREAD

**Issue by shaftwin** [microsoft/vscode-react-native#1473] opened 2020-12-14 12:49 UTC
## Current behavior
Error is thrown on Debug in Expo's first fun, failing when trying to install dependencies

## Expected behavior
Dependencies install successfully and debugging begins

<details>
<summary>Debug Console</summary>

```text

`Launching the application`

```
</details>

<details>
<summary>React Native output channel</summary>

```text

`[Info] Making sure your project uses the correct dependencies for Expo. This may take a while...

Checking if this is Expo app......
....[Error] Error: Error while executing command 'npm install @expo/xdl @expo/ngrok --verbose --no-save' (error code 101)` 

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

I got no message here

```
</details>

## Environment

Please tell us about your system and your project:

Here is my config from launch.json:
`{
      "name": "Debug in Exponent",
      "cwd": "${workspaceFolder}",
      "type": "reactnative",
      "request": "launch",
      "platform": "exponent"
}`

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
`WARNING: expo-cli has not yet been tested against Node.js v15.1.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=10.13.0 <11.0.0 (Maintenance LTS)
* >=12.13.0 <13.0.0 (Active LTS)
* >=14.0.0  <15.0.0 (Current Release)

┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (4.0.13).                │
│   You are currently using expo-cli 3.28.5                               │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
Didn't find any issues with the project!`
```

* `envinfo`:

```text
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 326.92 MB / 16.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 15.1.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    Composer: 2.0.8 - /usr/local/bin/composer
    Homebrew: 2.6.1 - /usr/local/bin/brew
    pip2: 18.1 - /usr/local/bin/pip2
    pip3: 20.2.4 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.26.0 - /usr/local/bin/git
    Clang: 1200.0.32.2 - /usr/bin/clang
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
  Virtualization:
    Docker: 19.03.8 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 26, 27, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5264788
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.52.0 - /usr/local/bin/code
    Vim: 8.1 - /usr/bin/vim
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_191 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.11 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.9.0 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Brave Browser: 87.1.17.73
    Safari: 14.0.1
```

* React Native Tools extension version: v1.2.0
* Expo SDK version (if applicable): 37.0.1

Thanks a lot for the futur help you will be able to provide !

**Comment by SounD120** [comment] 2020-12-14 13:14
Hi, @shaftwin . Thank you for the report, could you please try to install Node.js 12 LTS instead of Node.js 15, try to launch the debug scenario again? If this didn't work, please try to remove the extension, close VS Code, then reopen VS Code and install extension, and then launch the debug scenario. Could you please try this and let us know if this worked for you?

**Comment by shaftwin** [comment] 2020-12-14 13:28
Thanks for your quick response, i will try it as soon as possible and let you know the result.

**Comment by SounD120** [comment] 2020-12-14 13:35
@shaftwin There are few issues connected with Node.js 15 that we are investigating right now, so as a workaround it is better to use the LTS versions for now. I tried to reproduce your issue and it is more likely that this happens due to this issue: https://github.com/npm/cli/issues/2000

**Comment by shaftwin** [comment] 2020-12-14 22:21
@SounD120 I have to say thank you, it's working like a charm with the Node.js 12.
Hope you will find a way to solve your issues with v15 !

You can close this up, thanks.

**Comment by superandrew** [comment] 2020-12-17 22:04
I'm having the same problem. @SounD120 could you please elaborate installing node 12? If someone's using nvm it should be a matter of changing version there, but what about VS code? which node uses?

**Comment by SounD120** [comment] 2020-12-18 07:38
@superandrew VS Code uses Node.js 12 for now. Which version of npm do you use? If it is 7, than it might be the the main problem since from version 7 the algorithm to build dependencies tree has changed and it causes problems in some cases. We have already reported that to Expo since that happens due to one specific package: https://github.com/expo/expo-cli/issues/3027.

**Comment by superandrew** [comment] 2020-12-18 07:41
i was able to check that my node installed with brew was 15 and i think it was the only one. I installed node 12, brew-linked it and after restarting vs code and reinstalling the extension the error is gone

**Comment by RedMickey** [comment] 2021-02-22 11:23
Hi @shaftwin and @superandrew, I tested debugging of Expo apps using React Native Tools extension v1.4.0 on Node.js `v15.1.0`, `v15.6.0`, `v15.9.0` and couldn't reproduce the issue. In RNT 1.4.0 we updated some dependencies, that caused issues while installing `@expo/xdl` and `@expo/ngrok` packages on Node.js 15.x. 
Could you please try to debug an Expo application on Node.js 15.x using the latest (v1.4.0) version of the extension to check if the issue is fixed for you?
You can follow the instruction below to test the extension:
1. Install Node.js 15.x
1. Uninstall the extension
1. Close VS Code
1. Open VS Code
1. Install the extension
1. Run `Debug in Exponent` debugging scenario

**Comment by superandrew** [comment] 2021-02-22 11:49
to me so far everything is working properly.

Thanks!

**Comment by RedMickey** [comment] 2021-02-25 12:56
After the release of `React Native Tools v1.4.0`, the issue is no longer reproducible, so I'm closing it. Feel free to reopen if needed.

**Closed by RedMickey** 2021-02-25 12:56 UTC
Labels: bug, external-report, known-issues
