### ISSUE TITLE
VS code debugging crashes with react native and realm-js

### ISSUE THREAD

**Issue by deodeveloper** [Microsoft/vscode-react-native#363] opened 2016-12-10 07:05 UTC
## Actual Behavior
1. debugging crashes on react native 0.39, vscode 1.7.2, realm 0.15.0

## Expected Behavior
1. Could able to debug the app with Realm-JS

## Software versions
- React-Native VS Code extension version: 1.7.2
- VSCode version: 1.7.2
- OS platform and version: mac os 10.12.1
- NodeJS version: 7.2.1
- React Native version: 0.39

## Outputs (Include if relevant)
[vscode-react-native] Starting debugger app worker.
[vscode-react-native] Established a connection with the Proxy (Packager) to the React Native application
[vscode-react-native] Debugging session started successfully.
Error: socket hang up 
    at doRequest (/Users/admin/Documents/Development/react-native/lang-app/languageApp/node_modules/sync-request/index.js:37:11)
    at makeRequest (/Users/admin/Documents/Development/react-native/lang-app/languageApp/.vscode/.react/index.ios.bundle:73531:14)
    at sendRequest (/Users/admin/Documents/Development/react-native/lang-app/languageApp/.vscode/.react/index.ios.bundle:73561:14)
    at Object.createSession (/Users/admin/Documents/Development/react-native/lang-app/languageApp/.vscode/.react/index.ios.bundle:73452:1020)
    at /Users/admin/Documents/Development/react-native/lang-app/languageApp/.vscode/.react/index.ios.bundle:73080:31
    at loadModuleImplementation (/Users/admin/Documents/Development/react-native/lang-app/languageApp/.vscode/.react/index.ios.bundle:188:1)
    at guardedLoadModule (/Users/admin/Documents/Development/react-native/lang-app/languageApp/.vscode/.react/index.ios.bundle:140:8)
    at _require (/Users/admin/Documents/Development/react-native/lang-app/languageApp/.vscode/.react/index.ios.bundle:124:1)
    at /Users/admin/Documents/Development/react-native/lang-app/languageApp/.vscode/.react/index.ios.bundle:72899:18
    at loadModuleImplementation (/Users/admin/Documents/Development/react-native/lang-app/languageApp/.vscode/.react/index.ios.bundle:188:1)
Realm failed to connect to the embedded debug server inside the app. If attempting to use Chrome debugging from a device, ensure the device is reachable on the same network as this machine.

**Comment by MSLaguana** [comment] 2016-12-10 18:27
Looks like you are debugging an iOS app; are you trying to debug against the iOS simulator or an iOS device?

**Comment by deodeveloper** [comment] 2016-12-10 19:13
iOS simulator , iPhone 6

**Comment by deodeveloper** [comment] 2016-12-10 19:25
I mean it's iOS simulator using iPhone 6

**Comment by MSLaguana** [comment] 2016-12-12 22:20
This looks like it's a regression in realm-js caused by changes in react-native. They change behavior depending on the environment that they detect, and one check that the current release does is whether `typeof window != 'undefined'`. This is trying to detect running in chrome, but recent react-native releases actually define `window` as an alias for the global object, which confuses it and ends up causing your issue.

It looks like their master branch on github attempts to fix this by checking for a node-like environment first,  but that also includes a check for `(''+process) == '[object process]'` and that didn't seem to work in our environment. I'd suggest that you open an issue on realm-js and reference this issue, and we might need to coordinate to make sure that the detection works properly.

**Comment by MSLaguana** [comment] 2016-12-12 22:56
On that last point there; we sandbox the app and try not to expose much of the environment (to avoid scenarios where things work under testing but not on an actual app) and that includes not passing in the `process` object, and then react-native later on constructs a default process object. If realm needs it, we could potentially pass in the process object to the sandbox.

**Comment by deodeveloper** [comment] 2016-12-25 03:14
@MSLaguana It doesn't fix the issue with VS debugger. 
It looks to me some issue with VS debugger and realm connecting it. 

Error: 

Realm failed to connect to the embedded debug server inside the app. If attempting to use Chrome debugging from a device, ensure the device is reachable on the same network as this machine.
message:"Realm failed to connect to the embedded debug server inside the app. If attempting to use Chrome debugging from a device, ensure the device is reachable on the same network as this machine."
`stack:"Error: Realm failed to connect to the embedded debug server inside the app. If attempting to use Chrome debugging from a device, ensure the device is reachable on the same network as this machine.\n    at /Users/admin/Documents/Development/react-native/lang-app/languageApp/.vscode/.react/index.ios.bundle:73077:7\n    at loadModuleImplementation (/Users/admin/Documents/Development/react-native/lang-app/languageApp/.vscode/.react/index.ios.bundle:188:1)\n    at guardedLoadModule (/Users/admin/Documents/Development/react-native/lang-app/languageApp/.vscode/.react/index.ios.bundle:140:8)\n    at _require (/Users/admin/Documents/Development/react-native/lang-app/languageApp/.vscode/.react/index.ios.bundle:124:1)\n    at /Users/admin/Documents/Development/react-native/lang-app/languageApp/.vscode/.react/index.ios.bundle:72868:16\n    at loadModuleImplementation (/Users/admin/Documents/Development/react-native/lang-app/languageApp/.vscode/.react/index.ios.bundle:188:1)\n    at guardedLoadModule (/Users/admin/Documents/Dev...`

**Comment by Exilz** [comment] 2017-01-17 10:55
It's still happening for me too. It fixed the constructor problem, but not the error @deodeveloper pasted before.

**Comment by vladimir-kotikov** [comment] 2017-03-27 13:21
Tested w/ latest master and realm and it seems to work correctly after updating vscode detection logic as suggested in https://github.com/realm/realm-js/pull/855#issuecomment-288920254. Closing this.

**Closed by vladimir-kotikov** 2017-03-27 13:21 UTC
