### ISSUE TITLE
[Bug] Not able to run debug on exponent

### ISSUE THREAD

**Issue by Perh0rd** [microsoft/vscode-react-native#1765] opened 2022-04-01 18:54 UTC
# 🐛 What is the bug? How can we reproduce it?

1 - Launching a expo repo on codespace
2 - Add the configuration "Debug exponent"
3 - F5
4- Got this error : "Launching the application
An error occurred while launching the application. Cannot read properties of undefined (reading 'replace') (error code 303)"

Sample : https://p-BOF7zw99.t3.n0.cdn.getcloudapp.com/items/BluoK8rD/f58e72cf-635c-4853-8914-2e96cfc207a7.gif?v=7e6971e01f0dae771b92bc0ba170e772

## Expected behavior

The debugger should work

## Debug output

<details>
<summary>Debug Console</summary>

```text

"Launching the application
An error occurred while launching the application. Cannot read properties of undefined (reading 'replace') (error code 303)"

```
</details>

<details>
<summary>React Native output channel</summary>

```text

[Info] Making sure your project uses the correct dependencies for Expo. This may take a while...

Checking if this is an Expo app......
[Error] TypeError: Cannot read properties of undefined (reading 'replace')

[Error] TypeError: Cannot read properties of undefined (reading 'replace')

Checking if this is an Expo app......
[Error] TypeError: Cannot read properties of undefined (reading 'replace')

[Error] TypeError: Cannot read properties of undefined (reading 'replace')



```
</details>

<details>
<summary>Developer Tools console</summary>

```text

ERR [Extension Host] An error occurred while launching the application. Cannot read properties of undefined (reading 'replace') (error code 303)
console.ts:137 [Extension Host] An error occurred while launching the application. Cannot read properties of undefined (reading 'replace') (error code 303)
D @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:473
_invokeHandler @ rpcProtocol.ts:458
_receiveRequest @ rpcProtocol.ts:374
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:569
fire @ event.ts:736
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
invoke @ event.ts:569
fire @ event.ts:736
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
(anonymous) @ browserSocketFactory.ts:230
invoke @ event.ts:569
fire @ event.ts:736
_fileReader.onload @ browserSocketFactory.ts:91
```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
🎉 Didn't find any issues with the project!
```

* `envinfo`:

```text
  System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz
    Memory: 447.46 MB / 7.77 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.18.3 - ~/.nodejs/current/bin/node
    Yarn: 1.22.15 - /opt/yarn/stable/bin/yarn
    npm: 6.14.15 - ~/.nodejs/current/bin/npm
  Managers:
    Apt: 2.0.6 - /usr/bin/apt
    Cargo: 1.58.0 - /usr/local/cargo/bin/cargo
    Composer: 2.0.8 - /usr/local/bin/composer
    Gradle: 7.3.3 - /usr/local/sdkman/candidates/gradle/current/bin/gradle
    Maven: 3.6.3 - /opt/maven/lts/bin/mvn
    pip2: 20.3.4 - /usr/local/bin/pip2
    pip3: 21.3.1 - /usr/local/bin/pip3
    RubyGems: 3.2.9 - /home/codespace/.ruby/current/bin/gem
  Utilities:
    CMake: 3.16.3 - /usr/bin/cmake
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.3.0 - /usr/bin/gcc
    Git: 2.35.0 - /usr/local/bin/git
    Clang: 10.0.0 - /usr/bin/clang
    Mercurial: 5.3.1 - /usr/bin/hg
    Subversion: 1.13.0 - /usr/bin/svn
  Virtualization:
    Docker: 20.10.11+ - /usr/bin/docker
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    VSCode: 1.66.0 - /vscode/bin/linux-x64/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/bin/remote-cli/code
    Vim: 8.1 - /usr/bin/vim
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
    Go: 1.17.6 - /usr/local/go/bin/go
    Java: 17.0.1 - /home/codespace/.java/current/bin/javac
    Perl: 5.30.0 - /usr/bin/perl
    PHP: 7.3.27 - /home/codespace/.php/current/bin/php
    Python: 3.8.12 - /home/codespace/.python/current/bin/python
    Python3: 3.8.10 - /usr/bin/python3
    Ruby: 2.7.2 - /home/codespace/.ruby/current/bin/ruby
    Rust: 1.58.1 - /usr/local/cargo/bin/rustc
  Databases:
    SQLite: 3.31.1 - /usr/bin/sqlite3
```

* React Native Tools extension version: 1.9.2
* Expo SDK version (if applicable): 44

Thank you

**Comment by JiglioNero** [comment] 2022-04-04 11:04
Hi @Perh0rd and thanks for contacting us. Unfortunately we can`t reproduce this error. Our steps:
1) Create a new Expo project using the command `expo init ExpoProject -t tabs`
2) Open it with VSCode
3) Create a launch configuration for the Expo application with the option expoHostType: tunnel
```json
{
"name": "Debug in Exponent",
"cwd": "${workspaceFolder}",
"type": "reactnative",
"request": "launch",
"platform": "exponent",
"expoHostType":"tunnel"
}
```
4) Run this configuration
5) Everything started successfully

Could you please attach the versions of packages for debugging Expo applications, which are specified in the extension settings. Like this:
![image](https://user-images.githubusercontent.com/43934531/161530809-09705de0-d497-4619-8e8c-172415e17aa8.png)

It would also be great if you could attach a small demo project that reproduces this error.

**Comment by JiglioNero** [comment] 2022-04-11 08:32
@Perh0rd have you had a chance to look at it?

**Comment by Perh0rd** [comment] 2022-04-13 15:09
No i'll trake a look later today.

Thanks!

**Comment by JiglioNero** [comment] 2022-04-28 12:43
Hi @Perh0rd I'm closing this issue due to inactivity. Feel free to reopen if needed.

**Comment by jfavrod** [comment] 2022-10-26 15:09
I'm experiencing seemingly the same problem. Debugging had been working in our project, but now I'm getting the following:

![image](https://user-images.githubusercontent.com/1852827/198063839-73df0bd0-2beb-4904-aa9d-ad1080aa12ba.png)

When I start debugging I see this Output:
```
Making sure your project uses the correct dependencies for Expo. This may take a while...
```

Which I didn't notice before, then the error appears and I cannot launch debugging.

I don't know if I can create a project that reproduces the issue as the project I'm experiencing this in is quite complex.

**Comment by jfavrod** [comment] 2022-11-03 15:30
I reverted to v1.9.2 and that seems to have got things working again.
Now when I launch the debugger I get the following output:

```bash
[Info] Making sure your project uses the correct dependencies for Expo. This may take a while...

...............................
Checking if this is an Expo app......
[Warning] Couldn't read packager's options from exp.json, continue...

[Info] Starting Packager

warn Package @types/jest has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/jfavrod/dev/Cruz.Mobile/node_modules/@types/jest/package.json
                                                      
                        ####### 
```
Then Metro and Expo start.

I also deleted the `~/.vscode-react-native` and `~/.vscode/obsolete` directories. I'm not sure if that did anything though.

**Comment by Trashpants** [comment] 2022-11-14 10:35
Also can confirm that Ii'm getting the same issue as @jfavrod - deleting the directories first had no impact but downgrading to v1.9.3 worked without issue (expo SDK 46 & 47)

**Comment by EzioLi01** [comment] 2022-11-15 01:54
Reopen this issue.
@jfavrod @Trashpants Could you please provide any project to repro this issue and I can do further investigation on this?

**Comment by Trashpants** [comment] 2022-11-16 10:28
Hmmm Im not sure how related this is but I can see instantly with a new SDK 47 blank project as soon as start debugging the `app.json`

goes from 
```
{
  "expo": {
    "name": "VSCodeTest",
    "slug": "VSCodeTest",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
```

to

```
{
  "expo": {
    "slug": "vscodetest",
    "name": "vscodetest",
    "sdkVersion": "47.0.0"
  },
  "name": "vscodetest"
}
```

as im trying to copy / paste bits of config into a new project from my old project to see whats breaking it this is making it a bit weird to reproduce :(

**Comment by EzioLi01** [comment] 2022-11-16 11:38
> as im trying to copy / paste bits of config into a new project from my old project to see whats breaking it this is making it a bit weird to reproduce :(

 @Trashpants , The app.json overwrite issue is fixed in nightly version, please try to use [nightly version](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview) for debugging. But I think it is not related to your expo debugging issue. It works well on my local for the sample expo app in SDK 47. 
 So it's nice if you can provide any steps that can repro it.

**Comment by Trashpants** [comment] 2022-11-21 10:57
Incredibly simple fix here for me...

In previous projects `package.json` did not require a `name` or `version` key. Added those in and everything works.

@jfavrod any chance you can confirm this on your project?

**Comment by EzioLi01** [comment] 2022-11-22 03:16
> Incredibly simple fix here for me...
> 
> In previous projects `package.json` did not require a `name` or `version` key. Added those in and everything works.
> 
> @jfavrod any chance you can confirm this on your project?

I can confirm that I have tried to remove this `name `field in `package.json`, this issue is coming. 
@Trashpants Thanks for sharing this detail, it's the really nice found to help us improve our extension, we will investigate and plan to make some improvements for attach and debug logic.

**Comment by EzioLi01** [comment] 2022-11-24 05:37
Hello @Trashpants , do you have chance to try to use [nightly version](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview) in your side, to check if the error still display when `package.json` do not have `name` field?

**Closed** 2022-11-25 08:24 UTC
Labels: need-more-info, investigating, expo

**Comment by Trashpants** [comment] 2022-11-25 08:38
> Hello @Trashpants , do you have chance to try to use [nightly version](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview) in your side, to check if the error still display when `package.json` do not have `name` field?

Sorry to be slow on this - tried on nightly and I can remove the keys from package.json and it works without issue. 

That said I'll be keeping those keys in as expo new projects include them

**Comment by EzioLi01** [comment] 2022-11-25 11:12
> > Hello @Trashpants , do you have chance to try to use [nightly version](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native-preview) in your side, to check if the error still display when `package.json` do not have `name` field?
> 
> Sorry to be slow on this - tried on nightly and I can remove the keys from package.json and it works without issue.
> 
> That said I'll be keeping those keys in as expo new projects include them

OK, that's cool! Thanks for checking! And if you have any other issue on extension, please feel free to open issue here.
