### ISSUE TITLE
Expo app doesn't connect to packager

### ISSUE THREAD

**Issue by superandrew** [microsoft/vscode-react-native#1109] opened 2019-09-22 13:40 UTC
It's been 3 hours that I'm trying to figure out what broke my working setup out of nowhere.

My expo application doesn't connect to packager, let it alone debug it. If I launch `expo r` everything works like a charm.

I tried to disable the debugger from expo and just make the application start. I checked also from another device (not simulator) and the behaviour is exactly the same.

Any other app launched in Expo work.

While the debugging was on, I found a connection to http://localhost:8081 to succeed.

A connection to http://localhost:19000 generates the response:

```
{
  "error": "XDLError: ValidationError: \"https\" is not allowed"
}
```

I have no glue on what to check. Any help is appreciated.

## Actual Behavior
1. I click on "Debug in Exponent"
2. Packager starts
3. Debugger starts
4. I launch Expo
5. Expo doesn't connect, no matter how many caches cleared, systems restarted or voodoo operations performed on expo's doll.

## Expected Behavior
1. I click on "Debug in Exponent"
2. Packager starts
3. Debugger starts
4. I launch Expo
5. Expo connects to the packager and loads the app.

## Software versions
- React-Native VS Code extension version: 

- VSCode version: 
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
- OS platform and version: 
OSX Mojave 10.14.4
- NodeJS version: 
Hard to tell, my default is 12.6.0 but I'm never sure of what uses VS Code

- React Native version: 
0.59
- Expo SDK version (include if relevant):
SDK35
## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Info] Making sure your project uses the correct dependencies for Expo. This may take a while...

Checking if this is Expo app......
[Info] Starting Packager

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/superandrew/code/tutelart-rn 

Loading dependency graph, done.
[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] Building and running application.

No issue with doctor-watchman-versionNo issue with doctor-watchman-versionNo issue with doctor-problem-checking-watchman-versionNo issue with doctor-problem-checking-watchman-versionNo issue with doctor-both-app-and-exp-jsonNo issue with doctor-both-app-and-exp-jsonNo issue with doctor-schema-validationNo issue with doctor-schema-validationNo issue with doctor-validate-asset-fieldsNo issue with doctor-validate-asset-fieldsNo issue with doctor-schema-validation-exceptionNo issue with doctor-schema-validation-exceptionNo issue with doctor-unversionedNo issue with doctor-unversionedNo issue with doctor-versions-endpoint-failedNo issue with doctor-versions-endpoint-failedNo issue with doctor-invalid-sdk-versionNo issue with doctor-invalid-sdk-versionNo issue with doctor-node-modules-missingNo issue with doctor-node-modules-missingNo issue with doctor-react-native-not-installedNo issue with doctor-react-native-not-installedNo issue with doctor-unoptimized-assetsNo issue with doctor-unoptimized-assetsTunnel ready.Tunnel ready.[Info] Enable JS Debugging

No issue with doctor-watchman-versionNo issue with doctor-watchman-versionNo issue with doctor-problem-checking-watchman-versionNo issue with doctor-problem-checking-watchman-versionNo issue with doctor-both-app-and-exp-jsonNo issue with doctor-both-app-and-exp-jsonNo issue with doctor-schema-validationNo issue with doctor-schema-validationNo issue with doctor-validate-asset-fieldsNo issue with doctor-validate-asset-fieldsNo issue with doctor-schema-validation-exceptionNo issue with doctor-schema-validation-exceptionNo issue with doctor-unversionedNo issue with doctor-unversionedNo issue with doctor-versions-endpoint-failedNo issue with doctor-versions-endpoint-failedNo issue with doctor-invalid-sdk-versionNo issue with doctor-invalid-sdk-versionNo issue with doctor-node-modules-missingNo issue with doctor-node-modules-missingNo issue with doctor-react-native-not-installedNo issue with doctor-react-native-not-installedNo issue with doctor-unoptimized-assetsNo issue with doctor-unoptimized-assets
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
[Extension Host] debugger listening on port 43571
workbench.desktop.main.js:sourcemap:3424 [jundat95.react-native-snippet]: Unknown language in `contributes.react-native-snippet.language`. Provided value: jsx
_logMessageInConsole @ workbench.desktop.main.js:sourcemap:3424
workbench.desktop.main.js:sourcemap:230 [Extension Host] [vscode-icons] v9.4.0 activated!
workbench.desktop.main.js:sourcemap:230 [Extension Host] (node:36943) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ workbench.desktop.main.js:sourcemap:230
```

**Comment by superandrew** [comment] 2019-09-22 14:15
I was able to restore debugging after deleting the `.expo-shared` which contained this `asset.json` file:

```{
  "7adc6cdde1172c646f8dda7fcb1186d148e59e6d2a40774bd7e03281a653f19c": true,
  "796951473c719ad8e46b7b70380efd80d26df0c11d3469d6212a56e8ef71cc18": true,
  "dd783a7cbdbb29800782f11af86c80df4961140b1a280481f64df031e2ea0ff9": true,
  "89ed26367cdb9b771858e026f2eb95bfdb90e5ae943e716575327ec325f39c44": true,
  "b3cdac6ca96d142ff3f53e97cf97185e5e31481322ef1ebbdebc0fc97304a146": true
}```

Could anyone please help me understand what did the trick, so we can help myself of the future and others who might incur in this freaky problem?

**Comment by superandrew** [comment] 2019-09-22 16:54
I just realized that expo shared is created when assets are optimized. I guess that `rm -rf node_modules` and a couple of `yarn install` and kill whatever must have worked. However I have to say this.

This extension is FANTASTIC. And works 98% of the time. The 2% is when something gets stuck and it is so frustrating not knowing what can obliterate the setup and MUST work to reset the status.. any hint appreciated.

**Comment by SounD120** [comment] 2019-09-23 07:41
Hi @superandrew and thanks for reaching us. I [faced](https://github.com/expo/expo-cli/issues/951) such behavior with Expo apps, and I found out that there is `https: "false"` line in `.expo/settings.json` file which is most likely blocks https requests inside the app. Could you please check your `.expo/settings.json` file and let us know if it contains such line?

**Comment by superandrew** [comment] 2019-09-23 08:44
Hi @SounD120 I can confirm that the line is there. Googling for the problem, that was one of the first things that I tried to change, to no avail. However I'm not sure if after changing that line to `"https":true` I should have done some extra steps to "rebuild" the application with the new settings applied.

**Comment by SounD120** [comment] 2019-09-23 09:41
@superandrew Since that problem was reproduced without the extension at all, I think it is a problem of expo and expo-cli. I think that will be resolved as soon as [this](https://github.com/microsoft/vscode-react-native/issues/1109) issue will be fixed. 
I am closing this issue for now. Please feel free to create new issues, if have any.

**Closed by SounD120** 2019-09-23 09:41 UTC
Labels: external-report

**Comment by superandrew** [comment] 2019-09-23 09:44
thanks @SounD120 you probably meant to link the other issue, you linked the current one in your comment. Thanks for your support, this plugin is awesome!
