### ISSUE TITLE
IntelliSense Doesn't Understand Flow Type Annotations in .js files

### ISSUE THREAD

**Issue by joshuaskelton** [Microsoft/vscode-react-native#85] opened 2016-02-26 19:31 UTC
Salsa intellisense doesn't correctly handle JSX type annotations.

`'property declarations' can only be used in a .ts file.`

![screen shot 2016-02-26 at 11 27 16 am](https://cloud.githubusercontent.com/assets/14099985/13362982/1f2105ca-dc7c-11e5-8917-56b0d0df4741.png)

**Comment by egamma** [comment] 2016-02-27 16:24
This issue was moved to Microsoft/TypeScript#7275

**Comment by artyomtrityak** [comment] 2016-03-02 02:26
@egamma they are not going to fix this, React Native supports Flowtype from the box so i assum vscode react native plugin should support flowtype annotations. This is the reason i am not using vscode right now

**Comment by egamma** [comment] 2016-03-02 08:16
@artyomtrityak actually, there is a flow extension for Code https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode

One idea would be that you use this extension and then you map .js files as flow files in an extension. Something like this:

```json
{
	"name": "js-is-flow",
	"displayName": "JS is  Flow overwrite",
	"description": "Overwrites the file mapping of java script files so that they are treated like flow files",
	"version": "0.0.1",
	"publisher": "eg2",
	"engines": {
		"vscode": "^0.10.x"
	},
	"categories": [
		"Languages"
	],
	"contributes": {
		"languages": [
		{
				"id": "flow",
				"aliases": [
					"Flow"
				],
				"extensions": [
					".js"
				]
			}
		]
	}
}

**Comment by mroswald** [comment] 2016-04-28 08:37
@egamma does not work for me, js files as still detected as Javascript. I added the properties engines, categories and contributes to my package.json and restarted vs code. still no success. I also removed the `// @flow` comments from the top of the files. any clue?

**Comment by egamma** [comment] 2016-04-28 09:29
@mroswald someone got flow working, please see this discussion https://github.com/Microsoft/vscode/issues/5214#issuecomment-209357738

**Comment by mroswald** [comment] 2016-04-28 10:48
@egamma setting this via package.json seems no longer available. but files to language assocations can now be done in user or workspace settings via 
```	
"files.associations": {
  "*.js": "flow"
}
```

**Comment by egamma** [comment] 2016-04-28 13:11
@mroswald using the files association is now the recommended way. The package.json language contribution was more of a work around.

**Comment by prashaantt** [comment] 2016-05-21 13:36
I've enabled Flow using the extension and mapped *.js to flow, as suggested. This makes VS Code no longer report errors, but this also means IntelliSense stops working.

This was the exact issue with .jsx earlier and it was resolved by allowing files using the JavaScript React language mode to be first class JavaScript citizens with TypeScript enabled. A similar solution that treats the Flow lang mode (as provided by the Flow extension) but _without_ enforcing TypeScript checks and letting Flow take over would be the way to go. If I understand this correctly, this needs to happen inside Code itself rather than in the extension and perhaps by providing a new setting to disable TS validation for certain file types/language modes.

My personal use for Flow is exclusively with React which naturally works much better with Flow than TypeScript. Nuclide supports Flow out of the box, but I'm determined to stick with Code for all its other goodies. So I know it's probably too much to ask, but can you please make this happen @egamma? :)

**Comment by egamma** [comment] 2016-05-21 18:24
I was able to get Intellisense and diagnostics using the flow extension (see below).
- installed the flow extension from the market place
- added a `.flowconfig` file
- associated `.js` files with the flow language

Verified that the error message doesn't come from Salsa (it would have `[js]` as a prefix) and tried Intellisense.

![image](https://cloud.githubusercontent.com/assets/172399/15450074/c2000cac-1f91-11e6-8a9a-9d300cae884e.png)

**Comment by prashaantt** [comment] 2016-05-23 06:54
I just don't know what you're doing differently, because all I get to see is this

<img width="1026" alt="screenshot 2016-05-23 12 17 48" src="https://cloud.githubusercontent.com/assets/390540/15462439/71e00c9a-20e0-11e6-8897-8dbd2cf89a18.png">

I've tested this in the latest Insiders and regular builds. Do you have anything inside your .flowconfig?

**Comment by prashaantt** [comment] 2016-05-23 08:44
Can you please tell me the version of flow you have installed?

**Comment by egamma** [comment] 2016-05-23 08:53
I might be on an older version... 
`Flow, a static type checker for JavaScript, version 0.18.1`.

I suggest to file issues against the flow extension if the problem persists.
https://github.com/flowtype/flow-for-vscode

**Comment by prashaantt** [comment] 2016-05-23 09:04
Thanks, and sorry for the bother. Yes, I've verified that this is an issue with newer versions of the extension itself.

However, in regular JS mode, IntelliSense for "bar" returns many more suggestions from JavaScript, so it still appears that the full IntelliSense is not available to the Flow extension. Is that also a deficiency of the extension or something to do with Code itself?

**Comment by egamma** [comment] 2016-05-23 09:15
> in regular JS mode, IntelliSense for "bar" returns many more suggestions from JavaScript, so it still appears that the full IntelliSense is not available to the Flow extension. 

This is by design, the JS mode adds suggestion based on type inference and since not all types can be inferred it also offers the global JS symbols. This is described here: https://code.visualstudio.com/docs/languages/javascript#_intellisense

**Comment by niedzielski** [comment] 2016-05-28 19:17
Thanks for all the background on this issue! I believe the relevant issue mentioned in the extension is flowtype/flow-for-vscode/issues/13. Unfortunately, it seems that the suggested workaround breaks ESLint highlighting.

**Comment by egamma** [comment] 2016-05-29 03:51
> @julioolvr, this is a neat workaround but unfortunately seems to break ESLint highlights :(

I assume the issue is that once the language mode is set to something else than JavaScript then the vscode-eslint extension no longer considers the file. I've filed an issue against vscode-eslint.

**Comment by faceyspacey** [comment] 2016-12-06 01:57
any update on this?

**Comment by dudeinthemirror** [comment] 2017-03-08 21:25
After installing VSCode 1.10.2, I had the same issue. Adding

```json
    "files.associations": {
        "*.js": "flow"
    }
```
to the user settings did not solve the issue, it made syntax highlighting go away.
However when I took that out of settings and restarted the editor, Flow is working again properly.

**Comment by agrcrobles** [comment] 2017-03-21 20:16
This is working for me having the following in `settings.json`
```
{
    "javascript.validate.enable": false,
    "flow.useNPMPackagedFlow": true
}
```

**Comment by dually8** [comment] 2017-04-07 12:38
Thank you @agrcrobles, I've been messing with this for hours in an asp.net core application. FINALLY got it.

**Comment by rankun203** [comment] 2017-05-10 12:59
Thanks @agrcrobles ! 

**Note:** Place those settings provided by @agrcrobles in `$workspace/.vscode/settings.json` will only effective in current project.

**Comment by dotbear** [comment] 2017-05-24 15:17
Thank you so much @agrcrobles !

**Comment by jeantimex** [comment] 2017-06-20 03:53
You are awesome @agrcrobles!

**Comment by agrcrobles** [comment] 2017-06-20 05:18
Great it helped guys, I will add it to docs.

**Comment by vladimir-kotikov** [comment] 2017-08-01 10:36
Thanks to @agrcrobles, steps to get flow intellisense working are now reflected in README. Closing this

**Closed by vladimir-kotikov** 2017-08-01 10:36 UTC
Labels: known-issues

**Comment by johnunclesam** [comment] 2017-10-29 17:13
News on this?

**Comment by iTOYS** [comment] 2017-10-30 09:53
Hi @joshuaskelton,
Please see https://github.com/Microsoft/vscode-react-native/blob/master/doc/intellisense.md

**Comment by kunokdev** [comment] 2018-08-28 12:35
By disabling, `    "javascript.validate.enable": false,` what do we lose?
Thanks for solution tho @agrcrobles

**Comment by aMarCruz** [comment] 2018-08-29 00:01
In flow files, nothing
