### ISSUE TITLE
Getting unverified breakpoints in Debug iOS

### ISSUE THREAD

**Issue by EduardJS** [Microsoft/vscode-react-native#529] opened 2017-09-07 10:06 UTC
## Actual Behavior
1. Breakpoints appear as a grey circle with an "Unverified Breakpoint" note

## Expected Behavior
1. Breakpoints should work as expected

## Software versions
- React-Native VS Code extension version: 0.4.1
- VSCode version: 1.15.1
- OS platform and version: macOS, 10.12.6
- NodeJS version: 8.2.1
- React Native version: 0.48.1

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
[https://pastebin.com/CsQQgczp](https://pastebin.com/CsQQgczp)
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
[https://pastebin.com/HT4TU7RE](https://pastebin.com/HT4TU7RE)

- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
[http://i.imgur.com/hOiGTE9.png](http://i.imgur.com/hOiGTE9.png)

**Comment by EduardJS** [comment] 2017-09-07 10:25
Also mentioning the fact that I have just generated a clean project, via:
```
react-native init test
```

Went in Debug section, clicked gear icon, selected React-Native environment as it asked me, then chose Debug iOS from the dropdown and clicked Run.

Packager started, no error messages, app started, debug saying success, as per the post above, but when creating a breakpoint, the greyed out circle appears.

Leaving here the package json created by `react-init`.

```json
{
	"name": "test",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.48.1"
	},
	"devDependencies": {
		"babel-jest": "21.0.0",
		"babel-preset-react-native": "3.0.2",
		"jest": "21.0.1",
		"react-test-renderer": "16.0.0-alpha.12"
	},
	"jest": {
		"preset": "react-native"
	}
}
```

**Comment by vladimir-kotikov** [comment] 2017-09-07 11:01
@EduardJS thanks.

It looks like debugger runtime is getting started but not receiving any signal from RN app to start debugging. A first thing that comes into my mind - you probably have JS debugging disabled on simulator. Could you please try invoking dev menu on simulator, check if JS debugging is enabled and if not - enable it and let me know if it would help.

**Comment by EduardJS** [comment] 2017-09-07 11:30
Well, that was easy.

You should really highlight this in the README, as I've looked again, under `Get Started`, and I couldn't find it it.

Thanks a lot!

**Comment by vladimir-kotikov** [comment] 2017-09-07 12:51
@EduardJS, the reason why it's non mentioned in docs is because the extension _should_ enable it automatically in case of simulator. So actually I think this is a bug - I'll reopen this and we will try to reproduce and investigate

**Comment by vladimir-kotikov** [comment] 2017-09-08 09:25
Okay, I completely forgot that I have already merged #510 that has a fix, so I'm goingto close this

**Closed by vladimir-kotikov** 2017-09-08 09:25 UTC
Labels: bug, need-repro

**Comment by tafelito** [comment] 2018-04-16 13:09
@vladimir-kotikov I'm facing the same issue now, but the remote debug is indeed automatically enabled now, but the breakpoints are still grayed out. Not logs on the dev tools console. I updated  vscode to version 1.22.2 but still happening. Should I open a new issue?

**Comment by vladimir-kotikov** [comment] 2018-04-16 18:49
@tafelito, sorry, I do not work on this anymore - probably either @max-mironov or @annakocheshkova would be able to help
