### ISSUE TITLE
Debugging for ports other than 8081 not working

### ISSUE THREAD

**Issue by graduad** [microsoft/vscode-react-native#2002] opened 2023-07-20 21:57 UTC
# 🐛 What is the bug? How can we reproduce it?

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. Have created an old style React Native app (not Expo flow)
2. The app is in the example folder of the workspace
3. I cannot use port 8081 for Metro (something else is using it and cannot change this situation)
4. Have launched Metro on port 8088
5. The application stats and connects to the Metro server correctly (and works correctly as well)
7. Am trying to attach the debugger  using the configuration below
8. It looks like **VSCode is trying to start another instance of the Metro server** rather than **attach the debugger to the existing one**; this in spite of the configuration request  being "attach" (please see the "React Native output channel" section)
9. The VSCode **debugger** is not attached and **does not stop on breakpoints**, while the **application continues to work correctly**

Launch config:
```
{
    "configurations": [
        {
            "name": "Attach to packager",
            "request": "attach",
            "type": "reactnative",
            "cwd": "${workspaceFolder}/example",
            "port": 8088
        }
    ]
}
```

## Expected behavior

The debugger should attach and execution should stop when encountering breakpoints.

## Debug output

<details>
<summary>Debug Console</summary>

```text

Attaching to the application
An error occurred while attaching debugger to the application. Could not start the packager. (error code 1410)

```
</details>

<details>
<summary>React Native output channel</summary>

```text

[Info] Need to check main file and entry point of open module, will setup and write new content if they're not existing. Path: /Users/xxxxxxx/Documents/Develop/yyyyyyyy/example/node_modules/open

[Info] Find open-main.js and entry in open module, skip setup...

[Info] Starting Packager

error listen EADDRINUSE: address already in use :::8081.
Error: listen EADDRINUSE: address already in use :::8081
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at Server.listen (node:net:1876:7)
    at /Users/xxxxxxx/Documents/Develop/yyyyyyyy/example/node_modules/metro/src/index.flow.js:343:14
    at new Promise (<anonymous>)
    at earlyPortCheck (/Users/xxxxxxx/Documents/Develop/yyyyyyyy/example/node_modules/metro/src/index.flow.js:339:11)
    at exports.runServer (/Users/xxxxxxx/Documents/Develop/yyyyyyyy/example/node_modules/metro/src/index.flow.js:131:9)
    at Object.runServer [as func] (/Users/xxxxxxx/Documents/Develop/yyyyyyyy/example/node_modules/@react-native-community/cli-plugin-metro/build/commands/start/runServer.js:100:49)
    at async Command.handleAction (/Users/xxxxxxx/Documents/Develop/yyyyyyyy/example/node_modules/@react-native-community/cli/build/index.js:108:9)
info Run CLI with --verbose flag for more details.

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

 WARN [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.dart.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/dart/syntaxes/dart.tmLanguage.json.
New grammar file: file:///Users/xxxxxxx/.vscode/extensions/dart-code.dart-code-3.68.1/syntaxes/dart.json
register @ TMScopeRegistry.ts:46
log.ts:441   ERR [Extension Host] (node:63608) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Plugin) --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:63608) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Plugin) --trace-deprecation ...` to show where the warning was created)
v @ console.ts:137
log.ts:421  INFO [perf] Render performance baseline is 18ms
log.ts:441   ERR [Extension Host] An error occurred while attaching debugger to the application. Could not start the packager. (error code 1410)
console.ts:137 [Extension Host] An error occurred while attaching debugger to the application. Could not start the packager. (error code 1410)
v @ console.ts:137

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
-
```

* `envinfo`:

```text
-
```

* React Native Tools extension version: v1.11.1
* Expo SDK version (if applicable): -

**Comment by EzioLi01** [comment] 2023-07-21 04:32
Hey @graduad , thanks for reaching us. Please follow below steps to setup your rn app and try it again. Thanks!

1. Start rn app using `npx react-native run-android --port 8088`
2. In app, open dev menu -> change bundle location -> localhost:8088
3. Attach debugger using your launch settings above

**Comment by graduad** [comment] 2023-07-21 09:31
Hi @EzioLi01 , thank you very much for your comment. Unfortunately I do not think that your suggestion will help, because the app actually works. It starts and connects to the metro server using port 8088. The problem I have is that the VSCode debugger does not stop on breakpoint after attaching it using the config from my initial post.

**Comment by EzioLi01** [comment] 2023-07-21 11:57
Thanks @graduad , will look into this.

**Comment by EzioLi01** [comment] 2023-07-21 12:41
@graduad Nice catch! We do need to update some scenarios for it, will work on this soon, any update will comment here, thank you for the great issue!

**Comment by EzioLi01** [comment] 2023-07-24 02:44
Hey @graduad , could you please unzip and install this .vsix file and verify if the issue is fixed on your side? Thanks!
[vscode-react-native-1.11.1.vsix.zip](https://github.com/microsoft/vscode-react-native/files/12141237/vscode-react-native-1.11.1.vsix.zip)

**Comment by EzioLi01** [comment] 2023-07-25 01:53
Hey @graduad , do you have chance to try this?

**Closed** 2023-07-28 02:22 UTC
Labels: bug, triaged, resolved

**Comment by EzioLi01** [comment] 2023-07-28 08:59
This issue should be fixed, if you're using `run-android --port 8088` , you need to add 
```
{
    "react-native.packager.port": 8088
}
```
in `/projectRoot/.vscode/settings.json`.
