### ISSUE TITLE
Does not stop at breakpoint in Android simulator

### ISSUE THREAD

**Issue by AndyIsaacson** [Microsoft/vscode-react-native#285] opened 2016-08-16 23:18 UTC
I can't get the debugger to stop at a breakpoint in my project when using the Android simulator.  I created a minimal test project to demonstrate the issue (see below.)  The `.babelrc` file in the project is copied directly from the vscode-react-native README page.  It seems like something isn't working properly with the source maps, but I don't know what, and not sure what steps I can take to debug.  I'm a fan of VSCode, so I'd love to make this work!

## Actual Behavior
1. Clone minimal test repo at https://github.com/AndyIsaacson/VSCodeDebugTest
2. Open the project in VSCode
3. Add a breakpoint on line 22 on `index.android.js`
4. Debug for Android, tap the line that says "Press here for breakpoint" - nothing happens
5. Tap the line that says "Press here for debugger statement" - notice the source is not properly mapped to pre-babel source

## Expected Behavior
1. After adding breakpoint on line 22, debugger should stop when the first text element is tapped.
2. Upon hitting the debugger statement, the original source should be shown

## Software versions
- React-Native VS Code extension version: 0.1.5
- VSCode version: 1.4.0
- OS platform and version: MacOS 10.11.6
- React Native version: 0.31

**Comment by MSLaguana** [comment] 2016-08-17 00:31
What version of nodejs is installed on your machine? This sounds like it may be similar to issue #273.

**Comment by AndyIsaacson** [comment] 2016-08-17 03:20
v4.3.1 - thanks!

**Comment by MSLaguana** [comment] 2016-08-18 21:38
Looks like the issue is the kind of sourcemaps generated, they use sections which we don't support in the currently published version. The latest bits in the repo do work though, so feel free to try that out. The specific fix was https://github.com/Microsoft/vscode-react-native/pull/259 I believe

Next time we publish it should be fixed and I hope to publish a new version in the near future, but I don't have a timeline sorry.

**Comment by AndyIsaacson** [comment] 2016-08-19 15:33
Thanks @MSLaguana !  I grabbed master and built it - breakpoints work fine.  

Just curious, what component is actually building the sourcemaps?  Is it babel?  Node?  Is there a different version that I could have used that wouldn't have made sourcemaps with sections?  Still learning this ecosystem :-)

**Comment by MSLaguana** [comment] 2016-08-19 16:14
The sourcemaps are built by the react-native packager, and the process involves both babel and webpack if I remember correctly. The sourcemaps that it was producing were correct in this case, but used features that we didn't understand as a debugger. It's also possible that tweaking the settings for babel may let you compile a flat source map, rather than one with several sections (that's the part that we don't handle right) but I haven't looked into that.

**Closed** 2016-08-19 16:57 UTC
Labels: bug, external-report
