### ISSUE TITLE
Debugger doesn't work with Fat arrow function using ES2015+ class properties

### ISSUE THREAD

**Issue by jpgarcia** [Microsoft/vscode-react-native#297] opened 2016-08-31 13:34 UTC
## Actual Behavior
1. Set a breakpoint on an onPress handler function (```handleOnPress1```)
2. Set a breakpoint inside a fat arrow function using ES2015+ class properties (```handleOnPress2```)
3. Debug the code on iOS
3. It stops fine on the onPress handler function
4. It doesn't stops on the class property with arrow function to handle an onPress event
5. The application hangs

## Expected Behavior
1. Stop in an arrow functions defined in a ES2015+ class properties

## Software versions
- React-Native VS Code extension version: 0.1.6
- VSCode version: 1.4.0
- OS platform and version: OSX 10.11.6
- React Native version: 0.31.0

## Sample code

```javascript
import React, { Component } from 'react'
import { View, Text, TouchableOpacity, StyleSheet } from 'react-native'

export default class Sample extends Component {
  handleOnPress1() {
    console.log('stops here!!!')
  }

  handleOnPress2 = () => {
    console.log('doesn\'t stops here')
  }

  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity onPress={() => this.handleOnPress1()} style={styles.button}>
          <Text style={styles.text}>Press Me 1!</Text>
        </TouchableOpacity>
        <TouchableOpacity onPress={this.handleOnPress2} style={styles.button}>
          <Text style={styles.text}>Press Me 2!</Text>
        </TouchableOpacity>
      </View>
    )
  }
}

var styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    padding: 30,
    margin: 10,
    backgroundColor: 'cyan',
    borderColor: 'blue',
    borderWidth: 1,
  },
  text: {
    color: 'black'
  },
})
```

**Comment by changsi-an** [comment] 2016-08-31 17:37
Can you help check what Node version you are on?

**Comment by jpgarcia** [comment] 2016-08-31 17:45
6.2.0

**Comment by changsi-an** [comment] 2016-09-01 19:15
Thanks @jpgarcia 

From my understanding. None of those break point should work at node 6.x series. And that is the same issue as #273 (The reason is explained there). I tried 6.2.0 today, and that was the experience for me.

If applicable to you, switching to node 4.5.0 will fix the issue. I can get the breakpoint hit in the fat arrow function.

We are also following with Node.JS group on this issue. [Breakpoint event is not reported in Node.js 6](https://github.com/nodejs/node/issues/8347)

**Comment by changsi-an** [comment] 2016-09-01 19:16
Also using arrow function make babel compiles it into a different way:

```javascript
var example1 = function(_Component) {
    babelHelpers.inherits(example1, _Component);

    function example1() {
        var _Object$getPrototypeO;
        var _temp, _this, _ret;
        babelHelpers.classCallCheck(this, example1);
        for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
            args[_key] = arguments[_key];
        }
        	return _ret = (_temp = (_this = babelHelpers.possibleConstructorReturn(this, (_Object$getPrototypeO = Object.getPrototypeOf(example1)).call.apply(_Object$getPrototypeO, [this].concat(args))), _this), _this.

            handleOnPress2 = function() {
                console.log('doesn\'t stops here');
            }, _temp), babelHelpers.possibleConstructorReturn(_this, _ret);
        }
  
        babelHelpers.createClass(example1, [{
            key: 'handleOnPress1',
            value: function handleOnPress1() {
                console.log('stops here!!!');
            }
        }, {
            key: 'render',
            value: function render()

            {
                var _this2 = this;
                return (
                    _react2.default.createElement(_reactNative.View, {
                            style: styles.container
                        },
                        _react2.default.createElement(_reactNative.TouchableOpacity, {
                                onPress: function onPress() {
                                    return _this2.handleOnPress1();
                                },
                                style: styles.button
                            },
                            _react2.default.createElement(_reactNative.Text, {
                                style: styles.text
                            }, 'Press Me 1!')),

                        _react2.default.createElement(_reactNative.TouchableOpacity, {
                                onPress: this.handleOnPress2,
                                style: styles.button
                            },
                            _react2.default.createElement(_reactNative.Text, {
                                style: styles.text
                            }, 'Press Me 2!'))));



            }
        }]);
        return example1;
}(_react.Component);
exports.default = example1;
```

It might or might not be what you want.

**Comment by changsi-an** [comment] 2016-09-06 21:49
In the investigation we also noticed that the source map is not generated correctly. This reproduces even without VS code. We believe that it's a react-native issue.  [Source map for the bundle is not generated correctly when fat arrow function is used](https://github.com/facebook/react-native/issues/9778)

**Comment by mbraude** [comment] 2016-10-27 17:47
I think this is a dupe of #273, so I am closing this. @jpgarcia, please let me know if that is not the case and I will re-open.

**Closed by mbraude** 2016-10-27 17:47 UTC
Labels: bug, external, external-report, triaged
