### ISSUE TITLE
[Bug] Unable to Debug iOS Hermes on React Native 0.70.x

### ISSUE THREAD

**Issue by justin-tay** [microsoft/vscode-react-native#1853] opened 2022-11-03 10:06 UTC
# Unable to Debug iOS Hermes on React Native 0.70.x

The debugger fails to set breakpoints or attach.

1. npx react-native init MyApp --template react-native-template-typescript
2. Use VSCode and attempt to use Debug iOS Hermes - Experimental

Performing the same steps using React Native 0.69.x on the same machine sets breakpoints and attaches. 

## Expected behavior

The debugger should set breakpoints or attach.

## Environment

```text
 ✓ Node.js
 ✓ yarn
 ● Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 31.0.0
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ● ios-deploy - Required for installing your app on a physical device with the CLI
 ✖ .xcode.env - File to customize Xcode environment
```

* `envinfo`:

```text
 System:
    OS: macOS 11.7
    CPU: (8) arm64 Apple M1
    Memory: 401.03 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/opt/node@16/bin/npm
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    Homebrew: 3.6.8 - /opt/homebrew/bin/brew
    Maven: 3.8.6 - /opt/homebrew/bin/mvn
    pip3: 20.2.3 - /usr/bin/pip3
    RubyGems: 3.1.6 - /Users/user/.rbenv/shims/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.32.0 - /usr/bin/git
    Clang: 13.0.0 - /usr/bin/clang
  Servers:
    Apache: 2.4.54 - /usr/sbin/apachectl
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.73.0 - /opt/homebrew/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 11.0.15 - /usr/bin/javac
    Perl: 5.30.2 - /usr/bin/perl
    PHP: 7.3.29 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.8.9 - /usr/bin/python3
    Ruby: 2.7.5 - /Users/user/.rbenv/shims/ruby
  Databases:
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 107.0.5304.87
    Safari: 16.0
```

* React Native Tools extension version: v1.10.0

<img width="1440" alt="Screenshot 2022-11-03 at 5 43 52 PM" src="https://user-images.githubusercontent.com/49700559/199693424-19565a53-660b-4e5a-bac4-5d17a104b0c0.png">

<img width="1440" alt="Screenshot 2022-11-03 at 5 36 42 PM" src="https://user-images.githubusercontent.com/49700559/199693459-107113e0-5c0c-47c8-9778-830232283db5.png">

**Comment by EzioLi01** [comment] 2022-11-03 13:49
Hey @justin-tay , thanks for reaching us, I have tried to follow your steps, but no luck to repro this issue. 
But I will keep this issue opening and investigate the root cause.
Btw, could you please try to use classic mode to debug you app like this?

        {
            "name": "Debug iOS",
            "request": "launch",
            "type": "reactnative",
            "cwd": "${workspaceFolder}",
            "platform": "ios"
        }

**Comment by justin-tay** [comment] 2022-11-03 14:53
Thanks @EzioLi01! I didn't think of trying that since it was running Hermes and Debug iOS Hermes - Experimental worked for me before upgrading to 0.70.x. This also worked for the actual application I was trying to debug.

<img width="1440" alt="Screenshot 2022-11-03 at 10 18 18 PM" src="https://user-images.githubusercontent.com/49700559/199750488-1a25958c-0ff0-438b-8183-517fe29ea3d5.png">

**Comment by EzioLi01** [comment] 2022-11-04 02:53
Hey @justin-tay , could you please try to delete your app in simulator and try it again? It works on my side.

<img width="1114" alt="Screenshot 2022-11-04 at 10 51 27" src="https://user-images.githubusercontent.com/19662219/199874952-2aa7d6a0-1ea6-476d-809b-904143341d80.png">

**Comment by justin-tay** [comment] 2022-11-04 06:42
Have tried to remove the application in the simulator and clearing `ios/build` before reattempting.

Tried again with a completely fresh template but have the same result. 

I notice however that it does appear that the execution is stopped at the breakpoint, because the `console.log` statements don't print until after I press the stop button.

<img width="1440" alt="Screenshot 2022-11-04 at 2 15 58 PM" src="https://user-images.githubusercontent.com/49700559/199906345-d65c3bbb-712c-45e8-a00f-db589338ae0d.png">

After stopping

<img width="1440" alt="Screenshot 2022-11-04 at 2 16 11 PM" src="https://user-images.githubusercontent.com/49700559/199906326-cd74822a-2d79-45e9-823a-dfe025d97c18.png">

**Comment by EzioLi01** [comment] 2022-11-04 09:06
@justin-tay , I will do some further investigation and any update will let you know. Thank you!

**Comment by justin-tay** [comment] 2022-11-04 15:20
My vscode version is 1.73.0. Another thing is that Debug Android Hermes - Experimental works fine.

- Debug Console

From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"reactnativedirect","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-gb","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true,"supportsArgsCanBeInterpretedByShell":true})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsEvaluateForHovers":true,"supportTerminateDebuggee":true,"supportsCancelRequest":true}}
From client: launch({"name":"Debug iOS Hermes - Experimental","request":"launch","type":"reactnativedirect","cwd":"/Users/user/Documents/repo/MyApp704","platform":"ios","trace":"verbose","__configurationTarget":6,"__sessionId":"515bdf30-78f5-4756-94ff-6ce9e99294d3"})
Launching the application
Launching the application: {
  "name": "Debug iOS Hermes - Experimental",
  "request": "launch",
  "type": "reactnativedirect",
  "cwd": "/Users/user/Documents/repo/MyApp704",
  "platform": "ios",
  "trace": "verbose",
  "__configurationTarget": 6,
  "__sessionId": "515bdf30-78f5-4756-94ff-6ce9e99294d3",
  "sourceMaps": true,
  "enableDebug": true,
  "sourceMapRenames": false,
  "useHermesEngine": true
}
From client: attach({"name":"Debug iOS Hermes - Experimental","request":"launch","type":"reactnativedirect","cwd":"/Users/user/Documents/repo/MyApp704","platform":"ios","trace":"verbose","__configurationTarget":6,"__sessionId":"515bdf30-78f5-4756-94ff-6ce9e99294d3","sourceMaps":true,"enableDebug":true,"sourceMapRenames":false,"useHermesEngine":true})
Attaching to the application
Attaching to the application: {
  "name": "Debug iOS Hermes - Experimental",
  "request": "launch",
  "type": "reactnativedirect",
  "cwd": "/Users/user/Documents/repo/MyApp704",
  "platform": "ios",
  "trace": "verbose",
  "__configurationTarget": 6,
  "__sessionId": "515bdf30-78f5-4756-94ff-6ce9e99294d3",
  "sourceMaps": true,
  "enableDebug": true,
  "sourceMapRenames": false,
  "useHermesEngine": true,
  "webkitRangeMin": 9223,
  "webkitRangeMax": 9322
}
Connecting to 8081 port
To client: {"seq":0,"type":"response","request_seq":3,"command":"attach","success":true}
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}

- Output

[2022-11-4 14:55:55] [Reply From Debugger To Target] {
  "id": 1002,
  "method": "NodeWorker.enable",
  "params": {
    "waitForDebuggerOnStart": true
  }
}

[2022-11-4 14:55:55] [Reply From Debugger To Target] {
  "id": 1003,
  "method": "Debugger.enable",
  "params": {}
}

[2022-11-4 14:55:55] [Reply From Target To Debugger] {
  "result": {},
  "id": 1003
}

[2022-11-4 14:55:55] [Command Target To Debugger] {
  "params": {
    "context": {
      "id": 1,
      "origin": "",
      "name": "hermes"
    }
  },
  "method": "Runtime.executionContextCreated"
}

[2022-11-4 14:55:55] [Command Target To Debugger] {
  "params": {
    "url": "http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.MyApp704&cachePrevention=1",
    "startColumn": 0,
    "startLine": 0,
    "scriptId": "3",
    "endColumn": 0,
    "hash": "",
    "endLine": 0,
    "sourceMapURL": "http://localhost:8081/index.map?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.MyApp704&cachePrevention=1",
    "executionContextId": 0
  },
  "method": "Debugger.scriptParsed"
}

[2022-11-4 14:55:55] [Reply From Debugger To Target] {
  "id": 1004,
  "method": "Runtime.enable",
  "params": {}
}

[2022-11-4 14:55:56] [Command Target To Debugger] {
  "params": {
    "type": "log",
    "timestamp": 0,
    "args": [
      {
        "type": "string",
        "value": "Hi"
      }
    ],
    "executionContextId": 0
  },
  "method": "Runtime.consoleAPICalled"
}

[2022-11-4 14:56:01] [Command Target To Debugger] {
  "params": {
    "type": "log",
    "timestamp": 0,
    "args": [
      {
        "type": "string",
        "value": "Hi"
      }
    ],
    "executionContextId": 0
  },
  "method": "Runtime.consoleAPICalled"
}

[2022-11-4 14:56:06] [Command Target To Debugger] {
  "params": {
    "type": "log",
    "timestamp": 0,
    "args": [
      {
        "type": "string",
        "value": "Hi"
      }
    ],
    "executionContextId": 0
  },
  "method": "Runtime.consoleAPICalled"
}

[2022-11-4 14:56:11] [Command Target To Debugger] {
  "params": {
    "type": "log",
    "timestamp": 0,
    "args": [
      {
        "type": "string",
        "value": "Hi"
      }
    ],
    "executionContextId": 0
  },
  "method": "Runtime.consoleAPICalled"
}

[2022-11-4 14:56:16] [Command Target To Debugger] {
  "params": {
    "type": "log",
    "timestamp": 0,
    "args": [
      {
        "type": "string",
        "value": "Hi"
      }
    ],
    "executionContextId": 0
  },
  "method": "Runtime.consoleAPICalled"
}

[2022-11-4 14:56:21] [Command Target To Debugger] {
  "params": {
    "type": "log",
    "timestamp": 0,
    "args": [
      {
        "type": "string",
        "value": "Hi"
      }
    ],
    "executionContextId": 0
  },
  "method": "Runtime.consoleAPICalled"
}

**Comment by EzioLi01** [comment] 2022-11-05 02:37
Thank you, I will also investigate if it  related to vscode.js-debug.

**Comment by justin-tay** [comment] 2022-11-05 04:09
Using the Xcode 13.2.1 as still on Big Sur 11.7.1. ios-deploy not installed as testing on simulator and not device.

**Comment by EzioLi01** [comment] 2022-11-08 02:26
React-native is release new version 0.70.5, still can't repro this issue.

**Comment by justin-tay** [comment] 2022-11-09 09:41
Appreciate all the effort you've put in @EzioLi01. Thanks!

Have tried uninstalling and reinstalling the React Native Tools. Have tried with 0.71.0-RC.0 and still can't get it to attach even though attaching to 0.69 works. I guess I'll have to come back to this when I'm eventually ready to upgrade MacOS and XCode to see if that's a factor.

**Comment by EzioLi01** [comment] 2022-11-09 10:27
> Appreciate all the effort you've put in @EzioLi01. Thanks!
> 
> Have tried uninstalling and reinstalling the React Native Tools. Have tried with 0.71.0-RC.0 and still can't get it to attach even though attaching to 0.69 works. I guess I'll have to come back to this when I'm eventually ready to upgrade MacOS and XCode to see if that's a factor.

@justin-tay That's OK, we can keep this issue here and I will keep investigating in my side. Also, if you get any found in your working please update some details here. That we can try to find some workaround to help it works on your machine.

**Comment by weinixuehao** [comment] 2022-11-10 02:46
Have a workaround?

**Comment by EzioLi01** [comment] 2022-11-10 05:48
> Have a workaround?

Still cannot repro on my side, so just keep investigating for related scenarios, if you have some stable way to help repro this issue, it's will be helpful. Thank you!
Checked RN repo, it have some new issues related to hermes debugging, I'm not sure if they had the same root cause, but will keep an eye on it.

**Comment by EzioLi01** [comment] 2022-11-10 06:24
Please have this steps a try:
1. Run `npx react-native start` to start metro.
2. Run `npx react-native run-ios` to build and open app in simulator
3. Add below config in lanuch.json and run debugger
        {
            "name": "Attach to Hermes application - Experimental",
            "request": "attach",
            "type": "reactnativedirect",
            "cwd": "${workspaceFolder}"
        }

**Comment by EzioLi01** [comment] 2022-11-10 06:49
Here is the same issue I found in Flipper debugger: [Using IOS simulator, Flipper 0.173.0 does not stop at breakpoints](https://github.com/facebook/flipper/issues/4303).

**Comment by EzioLi01** [comment] 2022-11-18 03:27
Update status: React-native released new version 0.70.6, still can't repro this issue.

**Comment by EzioLi01** [comment] 2022-12-09 02:50
iOS debugger is working well on my side so far, and no further updates in this issue.
Will close this issue, if anyone can help us repro this issue, please reopen this issue or create a new one. Thanks!

**Closed by EzioLi01** 2022-12-09 02:50 UTC
Labels: need-more-info, need-repro, iOS, hermes

**Comment by QDFish** [comment] 2023-11-15 08:57
> Hey @justin-tay , could you please try to delete your app in simulator and try it again? It works on my side. I used `RN: 0.70.4, RNT: 1.10.0, OS: M2 Ventura 13.0, XCode: 14.1, Simulator iOS: 16.1` ![rndebug1](https://user-images.githubusercontent.com/19662219/199898462-6362bd59-ca13-4717-8987-747b7f1df1ae.gif) [ ![rndebug1](https://user-images.githubusercontent.com/19662219/199898462-6362bd59-ca13-4717-8987-747b7f1df1ae.gif) ](https://user-images.githubusercontent.com/19662219/199898462-6362bd59-ca13-4717-8987-747b7f1df1ae.gif) [ ](https://user-images.githubusercontent.com/19662219/199898462-6362bd59-ca13-4717-8987-747b7f1df1ae.gif)

when I saw thi video, I have a question why the variables is loading and can't show, which is happened in my device
