### ISSUE TITLE
Stop recreating typings and .vscode/typings folders

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode-react-native#360] opened 2016-12-04 05:23 UTC
## Actual Behavior
1. Every time I start vscode, it creates typings and .vscode/typings for react
2. Project won't compile anymore because of duplicated declarations

## Expected Behavior
1. Delete typings folder generated by this plugin
2. Don't regenerate

## Software versions
- React-Native VS Code extension version: 0.2.3
- VSCode version:  1.8.0-insider
- OS platform and version: windows 10 x64
- NodeJS version: 6.9.1
- React Native version: 0.38.0

**Comment by vladimir-kotikov** [comment] 2016-12-04 11:57
@pocesar, this sounds like a dupe of #348 and should be resolved by #357 in newer versions of extension

**Comment by pocesar** [comment] 2016-12-04 21:47
oh yeah, it is. but isn't 1.8.0 insiders >= 1.7.2? I update daily, where can I get a newer version of the extension?

**Comment by vladimir-kotikov** [comment] 2016-12-05 07:00
@pocesar, I think you'll need to wait until new version of extension is published.

**Comment by MSLaguana** [comment] 2016-12-08 21:15
I've just published a version 0.2.4 which should have these fixes now. If you still face issues, please let us know!

**Closed by MSLaguana** 2016-12-08 21:15 UTC
