### ISSUE TITLE
Known issues of Hermes debugging 

### ISSUE THREAD

**Issue by RedMickey** [microsoft/vscode-react-native#1266] opened 2020-05-06 07:34 UTC
This issue continues that [one #1099](https://github.com/microsoft/vscode-react-native/issues/1099) in terms of debugging via [js-debug extension](https://github.com/microsoft/vscode-js-debug).

The extension has experimental support for React Native Hermes debugging. At this moment we know about several issues related to Hermes debugging. Please see the list of known issues below.

The table of problems consists of two columns: the first one illustrates the problem when the extension is used for debugging an Hermes app , the second one - when Google Chrome is used for debugging an app.

If you faced new issues with React Native Hermes debugging via React Native Tools, please send them to the commentaries section of this issue.

## The list of issues

1. An application crashes when we are trying to watch content of some properties/objects on debugging. The problem is no longer reproducible on Android since React Native 0.66.0, but remains on iOS Hermes. See the issue [Application crashes on debugging Map and Set objects](https://github.com/facebook/hermes/issues/167).
  
  |Debugging using VS Code RNT Hermes debugger prototype|Debugging using Chrome|Resolved|
  |---|---|:---:|
  | <img width="1440" alt="iOS_hermes_map_extension" src="https://user-images.githubusercontent.com/77284023/136588592-de87931c-ba1e-40a2-b214-ccffa8e12647.png"> | <img width="1440" alt="iOS_hermes_map" src="https://user-images.githubusercontent.com/77284023/136588709-a613ce66-3885-40ad-b558-394133128ed6.png"> | Android resolved |

2. Sometimes the debugger cannot attach to an application correctly, which makes it impossible to set a breakpoint and view application logs in the debug console. An application could crash in case of incorrect attachment ([js-debug](https://github.com/microsoft/vscode-js-debug) refactoring).

  |Debugging using VS Code RNT Hermes debugger prototype|Debugging using Chrome|Resolved|
  |---|---|:---:|
  |![image](https://user-images.githubusercontent.com/33267199/81147864-de393400-8f83-11ea-9be5-3e17d5584dc3.png)|||

3. Hermes engine doesn't support `Runtime.callFunctionOn` method. See the issue [Runtime.callFunctionOn returns an empty value on debugging](https://github.com/facebook/hermes/issues/166).

4. [Android]:Hermes app crash when a second debugger tries to connect (https://github.com/facebook/hermes/issues/792)

**Comment by EricCornelson** [comment] 2020-06-02 22:46
Is #1 still happening? In the linked issue it looks like the issue is resolved on the Hermes side.

**Comment by RedMickey** [comment] 2020-06-03 12:32
@EricCornelson, we tried React Native [`0.63.0-rc.1`](https://www.npmjs.com/package/react-native/v/0.63.0-rc.1) and there the first issue still remains. We decided to wait for the next RN version and check if this issue has been fixed.

**Comment by liquidvisual** [comment] 2022-03-16 14:36
Still seems to be an issue on React Native 0.67.3 as of 2022. Attempting to debug crashes the app on Android, where as iOS fails to connect to dev tools.

**Comment by EzioLi01** [comment] 2022-08-11 12:07
The second issue is not repro currently.

**Comment by evelant** [comment] 2022-12-09 17:38
I have also noticed that Hermes debugging seems to fail whenever the app is reloaded. You must detach the debugger and reattach it. That makes it impossible to hit breakpoints that happen on app load.

**Comment by sjungwirth** [comment] 2023-04-22 17:29
I'm having the issue described in https://stackoverflow.com/questions/73362632/react-native-typescript-number-0-read-as-nan where `0` is showing as `NaN` for variable inspection when debugging. This only started recently when updating from RN 68.x to 71.x
![image](https://user-images.githubusercontent.com/314856/233798298-5655f1c0-ed0d-42fe-8eee-0b3dcca824fe.png)

**Comment by kylecesmat** [comment] 2023-05-25 19:26
ince upgrading to 0.71 w/ metro 0.73 we've been seeing this crash the metro server when attempting to load the 'Hermes Debugger'

```
throw er; // Unhandled 'error' event
      ^

RangeError: Max payload size exceeded
    at Receiver.haveLength (/Users/kylecesmat/code/react-native/node_modules/metro-inspector-proxy/node_modules/ws/lib/receiver.js:369:16)
    at Receiver.getPayloadLength64 (/Users/kylecesmat/code/react-native/node_modules/metro-inspector-proxy/node_modules/ws/lib/receiver.js:355:17)
    at Receiver.startLoop (/Users/kylecesmat/code/react-native/node_modules/metro-inspector-proxy/node_modules/ws/lib/receiver.js:137:22)
    at Receiver._write (/Users/kylecesmat/code/react-native/node_modules/metro-inspector-proxy/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.socketOnData (/Users/kylecesmat/code/react-native/node_modules/metro-inspector-proxy/node_modules/ws/lib/websocket.js:1162:35)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (/Users/kylecesmat/code/react-native/node_modules/metro-inspector-proxy/node_modules/ws/lib/websocket.js:1049:13)
    at Receiver.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'WS_ERR_UNSUPPORTED_MESSAGE_LENGTH',
  [Symbol(status-code)]: 1009
}

Node.js v18.14.2
```

**Comment by evelant** [comment] 2024-02-06 20:08
Trying to set a breakpoint with verbose logging shows this

```
[2024-2-6 20:06:53] [Reply From Debugger To Target] {
  "id": 1030,
  "method": "Debugger.setBreakpointByUrl",
  "params": {
    "urlRegex": "file:\\/\\/\\/Users\\/imagio\\/dev\\/TaskHero\\/apps\\/taskhero\\/build\\/src\\/components\\/hero\\/HeroAvatarImage\\.js($|\\?)|\\/Users\\/imagio\\/dev\\/TaskHero\\/apps\\/taskhero\\/build\\/src\\/components\\/hero\\/HeroAvatarImage\\.js($|\\?)",
    "lineNumber": 995,
    "columnNumber": 32
  }
}

[2024-2-6 20:06:53] [Reply From Debugger To Target] {
  "id": 1031,
  "method": "Debugger.setBreakpointByUrl",
  "params": {
    "urlRegex": "file:\\/\\/\\/Users\\/imagio\\/dev\\/TaskHero\\/apps\\/taskhero\\/src\\/components\\/hero\\/HeroAvatarImage\\.tsx($|\\?)|\\/Users\\/imagio\\/dev\\/TaskHero\\/apps\\/taskhero\\/src\\/components\\/hero\\/HeroAvatarImage\\.tsx($|\\?)",
    "lineNumber": 1270,
    "columnNumber": 0
  }
}

[2024-2-6 20:06:53] [Reply From Target To Debugger] {
  "id": 1030,
  "result": {
    "breakpointId": "0",
    "locations": []
  }
}

[2024-2-6 20:06:53] [Reply From Target To Debugger] {
  "id": 1031,
  "result": {
    "breakpointId": "9",
    "locations": []
  }
}
```

**Comment by EzioLi01** [comment] 2024-12-05 02:47
Update:
Issue 1, 2, 3: Fix verified on all mobile platforms.
Issue 4: Crashing issue is not existing with new rn devtools and RNT.

**Comment by EzioLi01** [comment] 2024-12-05 02:47
Close this issue since all issues are resolved.

**Closed by EzioLi01** 2024-12-05 02:48 UTC
Labels: known-issues, hermes
