### ISSUE TITLE
Debugger fails with SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by redlock** [Microsoft/vscode-react-native#613] opened 2017-12-12 17:22 UTC
## Actual Behavior
On running the debugger for iOS the debugger worker fails to run printing this error: 
`SyntaxError: Unexpected token <`

This is similar to this issue   #580 

## Expected Behavior
To run the react-native app on the simulator with vscode debugger attached.

## Software versions
- React-Native VS Code extension version: 0.5.7
- VSCode version: 1.18.1
- OS platform and version:  macOS 10.13.2
- NodeJS version: 9.1.0
- React Native version: 0.51.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
SyntaxError: Unexpected token <
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
 
```

 
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):

<img width="800" alt="screen shot 2017-12-12 at 8 13 27 pm" src="https://user-images.githubusercontent.com/438431/33898870-b5e6cd70-df7a-11e7-9f8e-1022f897d123.png">

debuggerWorker.js has HTML markup inserted every time I run the debugger:

<img width="1224" alt="screen shot 2017-12-12 at 8 22 16 pm" src="https://user-images.githubusercontent.com/438431/33898665-2b2936dc-df7a-11e7-8833-e64e6c6af0b3.png">

**Comment by iTOYS** [comment] 2017-12-12 17:27
Is it `react-native init` project?
Also please paste Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox).

**Comment by redlock** [comment] 2017-12-12 17:32
It is a react-native init project. 
The output of the React-Native output channel:

<img width="1290" alt="screen shot 2017-12-12 at 8 30 17 pm" src="https://user-images.githubusercontent.com/438431/33899103-82861e1c-df7b-11e7-869b-cd98e3e37d15.png">

**Comment by redlock** [comment] 2017-12-12 17:36
When I downgraded react-native to version 0.49.5 the problem disappeared. 
Advised by the following thread: 
https://github.com/Microsoft/vscode/issues/37734

**Comment by alexey-m-ukolov** [comment] 2017-12-26 10:12
I had this exact problem after updating from 0.49.5 to 0.51.0. Turning debugger off and on again fixed it.

**Comment by iTOYS** [comment] 2017-12-29 11:34
@redlock 
Sorry for delay.
Looks like you have run packager outside the vscode:
`[Info] packager is already running.`
Could you please check it and close packager if it's true. And try to run debug ios again from vscode.
Thanks!

**Comment by sergey-akhalkov** [comment] 2018-01-31 16:24
Hi @redlock, please let us know if the issue still has place for you and if you have a chance to take a look at the message above.

**Comment by olegdizus** [comment] 2018-02-01 06:24
I have same error in both cases: when packager started from within vscode and when I connect to external packager. This behaviour was checked few times and I had same result. Later I try to give more details.

**Comment by sergey-akhalkov** [comment] 2018-02-20 12:51
Hey guys, I'm closing this for now, please feel free to reopen or create new one if the issue still has place for you. Please also provide us as much info as possible so we would be able to reproduce and fix this.

**Closed by sergey-akhalkov** 2018-02-20 12:51 UTC
Labels: bug, need-more-info, need-repro, triaged, waiting-for-clarification
