### ISSUE TITLE
Can not debug when install haul

### ISSUE THREAD

**Issue by i7soft** [microsoft/vscode-react-native#1119] opened 2019-09-26 08:21 UTC
## Actual Behavior
1. 
2. 

## Expected Behavior
1. 
2. 

## Software versions
- React-Native VS Code extension version: 0.11.1
- VSCode version: 1.38.1
- OS platform and version: Mac OS 10.14.6
- NodeJS version: 10.11.0
- React Native version: 0.60.5
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: darwin x64
Adapter node: v10.11.0 x64
vscode-chrome-debug-core: 6.7.46
启动调试器应用辅助进程。
已建立代理(包生成工具)与 React Native 应用程序之间的连接
调试器辅助进程在端口 4314 上已加载运行时
TypeError: (intermediate value)(...) is not a function
    at Object.<anonymous> (/Users/shiqiren/Downloads/Compressed/project/.vscode/.react/debuggerWorker.js:124:9)
    at Module._compile (internal/modules/cjs/loader.js:774:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11
```
.vscode/.react/debuggerWorker.js:124:9 the function is:
```
(function(self) {
        'use strict';
        if (self.fetch) {
          return
        }
        self.fetch = fetch;
        function fetch(url) {
            return new Promise((resolve, reject) => {
                var data = require("fs").readFileSync(url, 'utf8');
                resolve(
                    {
                        text: function () {
                            return data;
                        }
                    });
            });
        }
      })(global); //👈line 124
```

**Comment by SounD120** [comment] 2019-09-26 08:23
Hi @i7soft . The fix for that issue is already proposed and will be released soon. Duplicate of #1108

**Closed by SounD120** 2019-09-26 08:23 UTC

**Comment by i7soft** [comment] 2019-09-26 08:26
@SounD120 👌
