### ISSUE TITLE
Debugger stability improvements

### ISSUE THREAD

**Issue by molant** [microsoft/vscode-react-native#1271] opened 2020-05-08 23:26 UTC
There have been a few reports about issues with the debugger, and in some cases having to restart VS Code to make it work again. The following comments seem to indicate that we are not properly closing all processes we spawn and that sometimes there are issues with sourcemaps:

>  I find myself having to close VSCode semi-frequently as there's a stuck debugger that won't end. The debugger launches and says a debugger is already active, the only solution I found is to close vs and relaunch

>  The debugger is very frustrating. Has to be restarted a lot as it loses it's place in the source and, sometimes, opens the bundle JS

> There seems to be errors connecting to the debugger, or the packager remaining open on the background... the process needs to be more seamless

> There seems to be errors connecting to the debugger, or the packager remaining open on the background... the process needs to be more seamless

> In the past, I could enable/disable/reenable debug mode in React Native whilst leaving VSCode attached to the packager. Lately, disabling debug mode detaches VSCode from the packager and it has to be reattached before I can enable debug mode again, else it will go back to launching Chrome

**Comment by molant** [comment] 2020-05-26 12:12
This should be improved via #1291 
Currently part of the migration to the new JS debugger so I'll leave this open until it reaches master.

**Comment by JiglioNero** [comment] 2020-06-02 15:01
@molant We looked through the feedback and unfortunately the described cases are not reproduced on the freshly created apps. We'll be glad to investigate each of these cases, but it will be much easier if we will have repro demos and repro steps. Without them it is quite hard to reproduce this.

**Comment by molant** [comment] 2020-06-02 16:50
> cases are not reproduced on the freshly created apps

I'd assume they happen when working on an application throughout the day and not consistently. I tried reaching out to the submitters but got no answers. I think we should keep this issue open to see if we get less reports once we start rolling-out the new version.

**Comment by SounD120** [comment] 2020-11-10 10:41
Hey @molant , are there any updates on this issue?

**Comment by molant** [comment] 2020-11-10 17:38
I haven't seen any comment in the latest ratings. I think we can leave this open for a couple more releases while we continue fixing some of the bugs and close it then.

I think we might have to use our experiments pipeline to prompt about the survey because we are getting a lot less answers these last few months 😞

**Comment by SounD120** [comment] 2020-11-11 08:42
@molant Which exact survey do you mean? Do you mean [this section](https://marketplace.visualstudio.com/items?itemName=msjsdiag.vscode-react-native&ssr=false#review-details)?

**Comment by molant** [comment] 2020-11-11 13:22
We have another survey that pops to only some users. That's how I got a lot of the initial feedback :)

**Comment by JiglioNero** [comment] 2022-04-28 12:58
It looks like this, the problem was no longer reproduced, I think we can close this issue and open it again if necessary

**Closed by JiglioNero** 2022-04-28 12:58 UTC
Labels: enhancement
