### ISSUE TITLE
After upgrade to macOS Catalina cannot debug.

### ISSUE THREAD

**Issue by shlaikov** [microsoft/vscode-react-native#1131] opened 2019-10-09 09:30 UTC
## Actual Behavior
Because of your extension the emulator doesn't work. Became after the upgrade macOS.

<img width="402" alt="Снимок экрана 2019-10-09 в 12 19 14" src="https://user-images.githubusercontent.com/16617640/66468781-68252b00-ea8f-11e9-9292-405fc66e0d9b.png">

## Expected Behavior
I would like it to work.

## Software versions
- React-Native VS Code extension version: 0.12.0
- VSCode version: 1.38.1
- OS platform and version: macOS Catalina 10.15
- NodeJS version: v10.16.3
- React Native version: 0.61.0-rc.0
- Expo SDK version (include if relevant): -

## Outputs (Include if relevant)
- When debug with throw Exceptions.
<img width="1017" alt="Снимок экрана 2019-10-09 в 12 13 28" src="https://user-images.githubusercontent.com/16617640/66468464-dc130380-ea8e-11e9-8629-036aa5f0277f.png">

**Comment by SounD120** [comment] 2019-10-09 09:38
Hi @shlaikov . It is a known issue and the fix will be released soon. Could you please try VSIX with a fix and let us know how it works for you? To try it please do the following:
* Download and unzip compiled extension VSIX : [vscode-react-native-0.12.0.vsix.zip](https://github.com/microsoft/vscode-react-native/files/3706287/vscode-react-native-0.12.0.vsix.zip)
* Uninstall extension
* Close VS Code
* Open VS Code
* Click `Extensions -> ... -> Install from VSIX...` and select downloaded VSIX

**Comment by shlaikov** [comment] 2019-10-09 09:44
@SounD120 the same.

**Comment by GraemeAllanBryce** [comment] 2019-10-09 09:49
The VSIX is not a fix for me - same outcomes.

**Comment by shlaikov** [comment] 2019-10-09 09:50
<img width="1010" alt="Снимок экрана 2019-10-09 в 12 50 08" src="https://user-images.githubusercontent.com/16617640/66471035-5e052b80-ea93-11e9-8404-55755728efee.png">

**Comment by SounD120** [comment] 2019-10-09 09:52
@shlaikov Could you please provide a minimal demo application in which this behavior is reproduces?

**Comment by shlaikov** [comment] 2019-10-09 09:58
@SounD120 I can't provide my code. But the starter pack took [here](https://github.com/ueno-llc/react-native-starter).  Maybe it will help you.

**Comment by SounD120** [comment] 2019-10-09 10:06
@shlaikov Does this reproduce on the previous extension versions? You can try to install them as follows:
* Right click on the React Native Tools extension in the VS Code extension tab
* Click on `Install Another Version...` 
* Choose the previous version, for example `0.11.2`

Please let us know if that helped.

**Comment by SounD120** [comment] 2019-10-09 10:18
@shlaikov I just tried to reproduce your issue on ueno-llc starter app, and it reproduced on old version of extension, and worked without any problems on a VSIX with a fix. 
Could you please also make sure that the latest version was installed correctly?
To do that please do the following:
* Uninstall extension (when clicked VS Code will mark it for deletion, but will not delete until you restart VS Code)
* Restart VS Code
* Click `Extensions` (at this point all the extensions marked for deletion are deleted and you can install a new version)
* Click` ...`
* Click  `Install from VSIX...` and select downloaded VSIX

**Comment by shlaikov** [comment] 2019-10-09 10:37
> @shlaikov Does this reproduce on the previous extension versions? You can try to install them as follows:
> 
> * Right click on the React Native Tools extension in the VS Code extension tab
> * Click on `Install Another Version...`
> * Choose the previous version, for example `0.11.2`
> 
> Please let us know if that helped.

It's helped. But the errors are still throwing.

**Comment by SounD120** [comment] 2019-10-09 10:39
@shlaikov Could you please describe what kind of errors do you encounter?

**Comment by shlaikov** [comment] 2019-10-09 10:48
First ex.
```
TypeError: exports.DOMException is not a constructor
    at http://localhost:8081/src/index.tsx.bundle?platform=ios&dev=true&minify=false:30843:7
    at http://localhost:8081/src/index.tsx.bundle?platform=ios&dev=true&minify=false:30402:68
    at http://localhost:8081/src/index.tsx.bundle?platform=ios&dev=true&minify=false:30403:5
```
Second ex. it's my issue.
```
Error: 400: An update check must include a valid deployment key - please check that your app has been configured correctly. To view available deployment keys, run 'code-push deployment ls <appName> -k'.
```

**Comment by SounD120** [comment] 2019-10-09 10:58
@shlaikov That seems to be an issue that is not connected with the original one. Could you please create a new issue for that?

**Comment by GraemeAllanBryce** [comment] 2019-10-09 11:06
Can I confirm that the latest code with the proposed fix is indeed https://github.com/microsoft/vscode-react-native/files/3706287/vscode-react-native-0.12.0.vsix.zip.

If so then I have uninstalled, restarted and then installed that version and the issue remains evident.

If there is a more recent build can you please post the URL for the VSIX

Thanks

**Comment by shlaikov** [comment] 2019-10-09 11:08
@SounD120 I was wrong. VSIX ex. has the same exceptions like 0.11.2 version. And VSIX ex. is working for me. I create a new issue for that.

**Comment by SounD120** [comment] 2019-10-09 11:24
@GraemeAllanBryce Have you tried that instruction?

> Does this reproduce on the previous extension versions? You can try to install them as follows:
> 
> * Right click on the React Native Tools extension in the VS Code extension tab
> * Click on `Install Another Version...`
> * Choose the previous version, for example `0.11.2`
> 
> Please let us know if that helped.

**Comment by SounD120** [comment] 2019-10-09 11:49
@shlaikov , @GraemeAllanBryce React Native Tools v0.12.1 with a fix for that has been released. Please try it out and let us know if the problem persists.

**Closed by SounD120** 2019-10-09 11:49 UTC
Labels: bug, known-issues

**Comment by GraemeAllanBryce** [comment] 2019-10-09 12:25
Fantastic - confirm that 0.12.1 is a fix for the issue.  Many Thanks
