### ISSUE TITLE
Not all success patterns were matched. (error code 712)

### ISSUE THREAD

**Issue by ezranbayantemur** [microsoft/vscode-react-native#1106] opened 2019-09-19 10:56 UTC
## Actual Behavior
I'm trying to debug a RN project but it gives error on below. I'm using my pc on Turkish language so package installed on TR as by default. But it found same error output on EN and I will post on below.

I checked [this issue](https://github.com/microsoft/vscode-react-native/issues/898) but I'm not using any package runner at same time. I just open project folder on VS Code and hit the debug button. By the way my launch.json file:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Android",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "launch",
            "platform": "android",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react"
        },
    ]
}
```

## Expected Behavior
1. Proper debug session.

## Software versions
- React-Native VS Code extension version: 0.11.0
- VSCode version: 1.38.1
- OS platform and version: Windows_NT x64 10.0.18362
- NodeJS version: 10.11.0
- React Native version: 0.60.4
- Expo SDK version (include if relevant): -

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: win32 x64
Adapter node: v10.11.0 x64
vscode-chrome-debug-core: 6.7.46
Hata ayıklanamadı. Bilinmeyen hata: Başarı desenlerinin tümü eşleşmedi. 
 Bu durum, "react-native run-android" komutunun başarısız olduğu anlamına gelir. 
 Lütfen, Görünüm -> Çıkışı Aç/Kapat -> React Native, 
 Görünüm -> Çıkışı Aç/Kapat -> React Native: android Çalıştır çıkış pencerelerini gözden geçirin. (error code 712)
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Info] Paketleyici başlatılıyor

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   c:\Users\ezran\Desktop\SADELABS\testPRO 

[Info] Paketleyici başlatıldı.

[Info] Toplu paket önbelleği önceden hazırlanıyor. Bu işlem biraz zaman alabilir...

[Info] Şu alınmak üzere: http://localhost:8081/index.bundle?platform=android

Loading dependency graph, done.
[Warning] Toplu Paket Önbelleği önceden hazırlandı.

[Info] Uygulama oluşturuluyor ve çalıştırılıyor.

 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (971/971), done.

[Error] Error: Bilinmeyen hata: Başarı desenlerinin tümü eşleşmedi. 
 Bu durum, "react-native run-android" komutunun başarısız olduğu anlamına gelir. 
 Lütfen, Görünüm -> Çıkışı Aç/Kapat -> React Native, 
 Görünüm -> Çıkışı Aç/Kapat -> React Native: android Çalıştır çıkış pencerelerini gözden geçirin. (error code 712)
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.
```

```
(ENGLISH:)
[Error] Error: Unknown error: not all success patterns were matched. It means that "react-native run-android" command failed. Please, check the View -> Toggle Output -> React Native, View -> Toggle Output -> React Native: Run android output windows. (error code 712)
```

- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
statusbar.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
workbench.desktop.main.js:sourcemap:3579 [Extension Host] debugger listening on port 61172
workbench.desktop.main.js:sourcemap:230 [Extension Host] vscode-customcss is active!
workbench.desktop.main.js:sourcemap:230 [Extension Host] (node:19356) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ workbench.desktop.main.js:sourcemap:230
workbench.desktop.main.js:sourcemap:230 [Extension Host] (node:19356) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ workbench.desktop.main.js:sourcemap:230
2workbench.desktop.main.js:sourcemap:1504   ERR Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at s.getElementLocation (file:///C:/Users/ezran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:124:791)
    at s.isCollapsed (file:///C:/Users/ezran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:124:65)
    at q.isCollapsed (file:///C:/Users/ezran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1009:19)
    at W.revealMarkersForCurrentActiveEditor (file:///C:/Users/ezran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5714:628)
    at W.autoReveal (file:///C:/Users/ezran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5714:485)
    at W.onActiveEditorChanged (file:///C:/Users/ezran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5711:775)
    at W._register.e (file:///C:/Users/ezran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5710:789)
    at d.fire (file:///C:/Users/ezran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:107:488)
    at setTimeout (file:///C:/Users/ezran/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:103:913)
```

**Comment by SounD120** [comment] 2019-09-19 11:01
Hi @ezranbayantemur and thanks for reaching us. Could you please also provide us logs from 
`View -> Toggle Output ->  React Native: Run Android` output channel?

**Comment by ezranbayantemur** [comment] 2019-09-19 14:22
```
[Warning] simulator hedefi Android platformu için desteklenmiyor. 
 Android uygulamasını başlatmak için belirli bir cihaz veya simülatör kullanmak istiyorsanız
 lütfen bunun yerine cihaz kimliğini ('adb devices' çıkışındaki gibi) belirtin.

[Info] android/local.properties dosyasında tanımlanan Android SDK konumu kullanılıyor: C:\Users\ezran\AppData\Local\Android\Sdk.

[Info] React Native Paketleyicisi başlatılıyor.

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1041 file(s) to forward-jetify. Using 8 workers...
info Installing the app...
> Task :@react-native-community_async-storage:preBuild UP-TO-DATE
> Task :@react-native-community_async-storage:preDebugBuild UP-TO-DATE
> Task :@react-native-community_async-storage:compileDebugAidl NO-SOURCE
> Task :@react-native-community_async-storage:checkDebugManifest UP-TO-DATE
> Task :@react-native-community_async-storage:compileDebugRenderscript NO-SOURCE

...
...

SO MANY PACKAGES..

...
...

> Task :react-native-vector-icons:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
> Task :app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
> Task :app:packageDebug UP-TO-DATE

> Task :app:installDebug
05:19:18 V/ddms: execute: running am get-config
05:19:19 V/ddms: execute 'am get-config' on 'aa62dc2a' : EOF hit. Read: -1
05:19:19 V/ddms: execute: returning
Installing APK 'app-debug.apk' on 'General Mobile 4G Dual - 7.1.1' for app:debug
05:19:19 D/app-debug.apk: Uploading app-debug.apk onto device 'aa62dc2a'
05:19:19 D/Device: Uploading file onto device 'aa62dc2a'
05:19:19 D/ddms: Reading file permision of C:\Users\ezran\Desktop\SADELABS\testPRO\android\app\build\outputs\apk\debug\app-debug.apk as: rwx------
05:19:21 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
05:19:31 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on 'aa62dc2a' : EOF hit. Read: -1
05:19:31 V/ddms: execute: returning
05:19:31 V/ddms: execute: running rm "/data/local/tmp/app-debug.apk"
05:19:31 V/ddms: execute 'rm "/data/local/tmp/app-debug.apk"' on 'aa62dc2a' : EOF hit. Read: -1
05:19:31 V/ddms: execute: returning
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BU�LD SUCCESSFUL in 28s
117 actionable tasks: 2 executed, 115 up-to-date
info Connecting to the development server...
info Starting the app on "aa62dc2a"...
Starting: Intent { cmp=com.testproject/.MainActivity }
```

**Comment by ezranbayantemur** [comment] 2019-09-23 10:28
@SounD120  Will you not gonna help about it?

**Comment by SounD120** [comment] 2019-09-23 10:37
Hi @ezranbayantemur . I am investigating your issue right now, and found out that there is an issue with encoding in your `React Native: Run Android` outputs with `BUILD SUCCESSFUL` message, which is used to validate the build logs. 
Did you modify project encoding, or maybe change gradle scripts?

**Comment by SounD120** [comment] 2019-09-23 11:25
@ezranbayantemur Could you please also try to run the command `react-native run-android` and attach the output of this command here?

**Comment by SounD120** [comment] 2019-09-23 13:56
@ezranbayantemur I also recommend you to clear Gradle caches. To do that please run the following command:
```
RD /Q /S %USERPROFILE%\.gradle\caches
```
Please let us know if it helps.

**Comment by SounD120** [comment] 2019-09-27 11:04
Hi @ezranbayantemur . Are you still experiencing this issue?

**Comment by ezranbayantemur** [comment] 2019-09-30 06:19
> Hi @ezranbayantemur . Are you still experiencing this issue?

I will working on it today

**Comment by ezranbayantemur** [comment] 2019-09-30 09:31
I created a new project with ``` react: "16.9.0", react-native: "0.61.1" ``` versions for being sure and I ran project for first time, it worked successfully. Also I clean gradle with ```gradlew clean``` command just in case.

Later I create configuration for React Native on Debug section, press Run and it gives these outputs.


**OUTPUT > React Native Run Android Platform**
```
[Warning] simulator hedefi Android platformu için desteklenmiyor. 
 Android uygulamasını başlatmak için belirli bir cihaz veya simülatör kullanmak istiyorsanız
 lütfen bunun yerine cihaz kimliğini ('adb devices' çıkışındaki gibi) belirtin.

[Info] local.properties dosyası yok. PATH içindeki Android SDK konumu kullanılıyor.

[Info] React Native Paketleyicisi başlatılıyor.

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 863 file(s) to forward-jetify. Using 8 workers...
info Installing the app...
> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:bundleDebugJsAndAssets SKIPPED
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders UP-TO-DATE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:copyDebugBundledJs SKIPPED
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:signingConfigWriterDebug UP-TO-DATE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE
> Task :app:transformDexArchiveWithDexMergerForDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
> Task :app:packageDebug UP-TO-DATE

> Task :app:installDebug
12:16:41 V/ddms: execute: running am get-config
12:16:42 V/ddms: execute 'am get-config' on 'aa62dc2a' : EOF hit. Read: -1
12:16:42 V/ddms: execute: returning
Installing APK 'app-debug.apk' on 'General Mobile 4G Dual - 7.1.1' for app:debug
12:16:42 D/app-debug.apk: Uploading app-debug.apk onto device 'aa62dc2a'
12:16:42 D/Device: Uploading file onto device 'aa62dc2a'
12:16:42 D/ddms: Reading file permision of C:\Users\ezran\Desktop\TestingProjects\testProject\android\app\build\outputs\apk\debug\app-debug.apk as: rwx------
12:16:44 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
12:16:53 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on 'aa62dc2a' : EOF hit. Read: -1
12:16:53 V/ddms: execute: returning
12:16:53 V/ddms: execute: running rm "/data/local/tmp/app-debug.apk"
12:16:53 V/ddms: execute 'rm "/data/local/tmp/app-debug.apk"' on 'aa62dc2a' : EOF hit. Read: -1
12:16:53 V/ddms: execute: returning
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings

BU�LD SUCCESSFUL in 20s
27 actionable tasks: 2 executed, 25 up-to-date
info Connecting to the development server...
info Starting the app on "aa62dc2a"...
Starting: Intent { cmp=com.testproject/.MainActivity }
```

**OUTPUT > React Native**
```
[Info] Paketleyici başlatılıyor

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   c:\Users\ezran\Desktop\TestingProjects\testProject 

[Info] Paketleyici başlatıldı.

[Info] Toplu paket önbelleği önceden hazırlanıyor. Bu işlem biraz zaman alabilir...

[Info] Şu alınmak üzere: http://localhost:8081/index.bundle?platform=android

Loading dependency graph, done.
[Warning] Toplu Paket Önbelleği önceden hazırlandı.

[Info] Uygulama oluşturuluyor ve çalıştırılıyor.

 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (449/449), done.

[Error] Error: Bilinmeyen hata: Başarı desenlerinin tümü eşleşmedi. 
 Bu durum, "react-native run-android" komutunun başarısız olduğu anlamına gelir. 
 Lütfen, Görünüm -> Çıkışı Aç/Kapat -> React Native, 
 Görünüm -> Çıkışı Aç/Kapat -> React Native: android Çalıştır çıkış pencerelerini gözden geçirin. (error code 712)

info Starting custom debugger by executing:, echo A debugger is not needed:  "c:\Users\ezran\Desktop\TestingProjects\testProject"
 DELTA  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

 MAP  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

 LOG  Running "testProject" with {"rootTag":1}
 LOG  3750
```

**DEBUG CONSOLE**
```
OS: win32 x64
Adapter node: v10.11.0 x64
vscode-chrome-debug-core: 6.7.46
Hata ayıklanamadı. Bilinmeyen hata: Başarı desenlerinin tümü eşleşmedi. 
 Bu durum, "react-native run-android" komutunun başarısız olduğu anlamına gelir. 
 Lütfen, Görünüm -> Çıkışı Aç/Kapat -> React Native, 
 Görünüm -> Çıkışı Aç/Kapat -> React Native: android Çalıştır çıkış pencerelerini gözden geçirin. (error code 712)
```

----------------------------------------------------------------------------------------------
I'm not sure about these outputs are necessary but added just in case

**OUTPUT > Git**
```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.22.0.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

... it keeps going with same errors
```

**OUTPUT > TypeScript**
```
[Info  - 12:15:45] Using tsserver from: c:\Users\ezran\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 12:15:46] <syntax> Forking...
[Info  - 12:15:46] <syntax> Starting...
[Info  - 12:15:46] <semantic> Forking...
[Info  - 12:15:46] <semantic> Starting...
```

**Comment by SounD120** [comment] 2019-09-30 13:02
Hi @ezranbayantemur this issue is specific only for Turkish language and this is a [Gradle bug](https://issuetracker.google.com/issues/126874329). For some reason in `BUILD SUCCESSFUL` line capital `I` changes to `İ` and this causes failures in the output verifier of the extension. Since this behavior connected to Gradle bug, I recommend to use `Attach to packager` debug scenario as a workaround for your case until this bug will be completely fixed. To do that please do the following:
1. Run application with `react-native run-android` command
1. Run `Attach to packager` debug scenario
1. Enable [`Remote JS Debugging`](https://facebook.github.io/react-native/docs/debugging#accessing-the-in-app-developer-menu) inside the app

Please let us know if this was helpful.

**Comment by ezranbayantemur** [comment] 2019-09-30 13:30
I add configuration on "Attach to packager" and tried but it gives that error on **Debug Console**

```
OS: win32 x64
Adapter node: v10.11.0 x64
vscode-chrome-debug-core: 6.7.46
Hata ayıklayıcısı uygulama çalışanı başlatılıyor.
Ara sunucuyla (Paketleyici) React Native uygulaması arasında bağlantı kuruldu
Ara sunucunun (Paketleyici) React Native uygulamasıyla olan bağlantısı kesildi. Birazdan yeniden bağlanmaya çalışılacak...
Hata ayıklanamadı. Paketleyiciye başka bir hata ayıklayıcısı zaten bağlı. Lütfen VS Code ile hata ayıklamayı denemeden önce diğer hata ayıklayıcısını kapatın. (error code 505)
```

It's kind a say there are already debug packager connected.

**Comment by SounD120** [comment] 2019-09-30 13:32
@ezranbayantemur Please ensure that React Native debugger tab in Chrome is closed.

**Comment by ezranbayantemur** [comment] 2019-09-30 13:59
It's starting, thanks for that but there is problem happend. 
I think it's not catch breakpoints, when I toggle a breakpoint it says "Unverified Breakpoint" and "Step Over/Into/Out" buttons are disabled.

Did I something wrong?

![23](https://user-images.githubusercontent.com/42299721/65885658-b0fc2600-e3a3-11e9-9710-6f839c54d1d0.png)

**Comment by SounD120** [comment] 2019-09-30 14:07
@ezranbayantemur This issue reproduces since React Native 0.61. Fix for that is already proposed in #1122 so this problem will be fixed soon.

**Comment by ezranbayantemur** [comment] 2019-09-30 14:10
Okay then I'm waiting. Thank you so much for help 👍

**Comment by SounD120** [comment] 2019-10-07 13:34
Hi @ezranbayantemur . React Native Tools v0.12.0 with React Native 0.61 support has been released. I am closing that issue. Please feel free to reopen if needed.

**Closed by SounD120** 2019-10-07 13:34 UTC
Labels: external, fix-in-master

**Comment by KubilayKerim** [comment] 2021-06-14 08:40
I got the same error I changed my windows language from Turkish to Eng but it did not help uninstalled and installed after that did not help either error logs are still in turkish and error  persisting Rn tools version is 1.5.1 RN version is 0.63.4

**Comment by RedMickey** [comment] 2021-06-15 10:25
It seems that [the issue related to Turkish language still persists in Gradle](https://github.com/gradle/gradle/issues/1506). I'd recommend to use [this workaround](https://github.com/microsoft/vscode-react-native/issues/1106#issuecomment-536550524), until the issue is fixed.

**Comment by 05397060115** [comment] 2024-04-11 20:07
ayde

**Comment by 05397060115** [comment] 2024-04-11 20:09
Ayşe

**Comment by 05397060115** [comment] 2024-04-11 22:23
05421900813
