### ISSUE TITLE
[Bug] Dynamic configuration read from .env failing

### ISSUE THREAD

**Issue by superandrew** [microsoft/vscode-react-native#1436] opened 2020-10-11 20:33 UTC
It seems that the debugger is unable to load environment variables in app config. This is basically a duplicate of an [issue](https://github.com/microsoft/vscode-react-native/issues/1302#issuecomment-706179042) that had been [fixed](https://github.com/expo/expo-cli/pull/2220) earlier this year, but I noticed that something changed in expo cli, so I am not able of fixing things as suggested there.

I have another machine in which I have vs code, same approx node version (12.13.1 vs 12.13.0), expo cli same version and I do not have the same problem. Same 1.0.1 version of react-native-tools.

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. Step 1
put an app configuration in (e.g. `./tenant_configs/tenant1.app.json`)

2. Step 2
using https://github.com/tusbar/babel-plugin-dotenv-import import an environment variable from an .env file
for ex. `TENANCY_NAME=tenant1`

3. Step 3
try to read values from those variables

```
import { ConfigContext, ExpoConfig } from "@expo/config/build";
import { mergeDeep } from "./utils/objectUtils";
import { TENANCY_NAME } from "react-native-dotenv";

export default ({ config }: ConfigContext): ExpoConfig => {
  // try {

    let customConfig = require(`./tenant_configs/${TENANCY_NAME}.app.json`);
    if (!customConfig) {
      customConfig = {};
    }
    const conf =  mergeDeep({}, config, customConfig);
    //console.log(JSON.stringify(conf))

    return conf;
  // } catch (e) {
  //   throw new Error(`Missing app configuration for tenant ${TENANCY_NAME}`);
  // }
};



};
```
4. Step 4 
Launch the debugger

## Expected behavior
The application should launch normally, as it does while running `expo r`

## Debug output
Launch applications
(popup shows)
![CleanShot 2020-10-11 at 22 21 44](https://user-images.githubusercontent.com/71364/95689320-2b46c380-0c10-11eb-8de2-97bd0494f1e4.png)

```text

Launching the application

```
</details>

<details>
<summary>React Native output channel</summary>

```text

[Info] Building and running application.

[Error] ConfigError: Failed to read config at: /Users/superandrew/code/irideweb2-iridewebapp/app.config.ts

```
</details>

<details>
<summary>Developer Tools console</summary>

```text
(nothing particular)
 WARN UNRESPONSIVE extension host, 'Gruntfuggly.todo-tree' took 99% of 3690.505ms, saved PROFILE here: '/var/folders/gt/m4bh7qbd29jgb4xf3c9wtqs80000gn/T/exthost-ada452.cpuprofile' (12) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
console.ts:137 [Extension Host] (node:15986) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:70
$logExtensionHostMessage @ remoteConsoleUtil.ts:29
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:535
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
console.ts:137 [Extension Host] [vscode-icons] v11.0.0 activated!
2console.ts:137 [Extension Host] Message Connecting... didn't get externalized correctly.
t.log @ console.ts:70
$logExtensionHostMessage @ remoteConsoleUtil.ts:29
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:535
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
console.ts:137 [Extension Host] Message Add a region to AWS Explorer... didn't get externalized correctly.
t.log @ console.ts:70
$logExtensionHostMessage @ remoteConsoleUtil.ts:29
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:535
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
console.ts:137 [Extension Host] Message Click here to add a region to AWS Explorer. didn't get externalized correctly.
t.log @ console.ts:70
$logExtensionHostMessage @ remoteConsoleUtil.ts:29
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:535
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
console.ts:137 [Extension Host] Message AWS Toolkit didn't get externalized correctly.
t.log @ console.ts:70
$logExtensionHostMessage @ remoteConsoleUtil.ts:29
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:535
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
console.ts:137 [Extension Host] Message Connect to AWS... didn't get externalized correctly.
t.log @ console.ts:70
$logExtensionHostMessage @ remoteConsoleUtil.ts:29
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:535
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
console.ts:137 [Extension Host] Message Click here to select credentials for the AWS Toolkit didn't get externalized correctly.
t.log @ console.ts:70
$logExtensionHostMessage @ remoteConsoleUtil.ts:29
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:535
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
npx react-native doctor
Common
 ✓ Node.js
 ✓ yarn
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✖ JDK
   - Version found: 1.8.0_251
   - Version supported: >= 8
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: Not Found
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   2
Warnings: 0

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.
Common
 ✓ Node.js
 ✓ yarn
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✖ JDK
   - Version found: 1.8.0_251
   - Version supported: >= 8
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: Not Found
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   2
Warnings: 0

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.

```

* `npx envinfo`:

```text
 ➜ npx envinfo            

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Xeon(R) CPU E5-1680 v2 @ 3.00GHz
    Memory: 335.04 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
    Gradle: 6.3 - /usr/local/bin/gradle
    Homebrew: 2.5.2 - /usr/local/bin/brew
    pip3: 20.1.1 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.24.3 - /usr/bin/git
    Clang: 1200.0.32.2 - /usr/bin/clang
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
  Virtualization:
    Docker: 19.03.13 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.50.0 - /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
    Vim: 8.1 - /usr/bin/vim
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_251 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.11 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.8.5 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    PostgreSQL: 12.3 - /Applications/Postgres.app/Contents/Versions/latest/bin/postgres
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 85.0.4183.121
    Safari: 14.0
    Safari Technology Preview: 14.0.1
```

 
* React Native Tools extension version: latest
* Expo SDK version (if applicable): 38

**Comment by RedMickey** [comment] 2020-10-13 08:00
Hi @superandrew and thanks for reaching us. We found out that this issue has been reproduced since the `@expo/xdl@58.0.4` package. Some changes which probably cause the problem were done at that version. We could also reproduce this issue running a project from the terminal, so we opened [the issue](https://github.com/expo/expo-cli/issues/2782) in the `expo/expo-cli` repository.

**Comment by superandrew** [comment] 2020-10-13 10:36
@RedMickey is there any way to restore the project in a way that works again? Installing a previous version of @expo/xdl?

**Comment by superandrew** [comment] 2020-10-13 12:19
```
cd ~/.vscode/extensions/msjsdiag.vscode-react-native-1.0.1 
npm uni --no-save @expo/xdl 
npm i --no-save @expo/xdl@58.0.3 
```

works for me

**Comment by superandrew** [comment] 2020-10-13 13:02
I'm sorry, no. This doesn't fix anything. It seems that the debug is starting but in the end it doesn't. If anyone has suggestion on how to get back to work with this it would be highly appreciated as I'm out in the dark.

**Comment by RedMickey** [comment] 2020-10-14 06:25
@superandrew, the extension doesn't use commands from the global `expo-cli` while launching an Expo application. It uses functions from the local `@expo/xdl` package.
To install a specific version of the `@expo/xdl` package to the extension you need do the following:
1. Open VS Code `extensions`  folder in terminal by using one of the following commands:
   * **Windows:** `cd %USERPROFILE%\.vscode\extensions`
   * **macOS:** `cd ~/.vscode/extensions`
   * **Linux:** `cd ~/.vscode/extensions`
2. Go to `msjsdiag.vscode-react-native-x.x.x` (where `x` - your version numbers) extension folder and run these commands:
```
npm uni --no-save @expo/xdl
npm i --no-save @expo/xdl@58.0.3
```
3. Close and reopen VS Code.

If you don't do the last step, the extension will continue to use the previously installed package.

It must be enough to change only the version of the `@expo/xdl` package. We just downgraded the version of the package and then we were able to run the Expo debugging scenario without problems.

**Comment by RedMickey** [comment] 2020-10-21 11:29
Hi @superandrew, according to the [Expo team's answer](https://github.com/expo/expo-cli/issues/2782#issuecomment-713189387) for now Expo doesn't support use of `babel-plugin-dotenv-import` in a `app.config.js` file the way it used to work. They also proposed possible workarounds until the issue is fixed.  It seems that the issue isn't an issue of the extension, since it is reproduced with Expo CLI commands, so I'm closing the issue. But we continue to track [this issue](https://github.com/expo/expo-cli/issues/2782) on Expo side.

**Closed by RedMickey** 2020-10-21 11:29 UTC
Labels: bug, external-report

**Comment by superandrew** [comment] 2020-10-23 06:40
@RedMickey thanks. I followed the suggestions and acknowledge the change in expo. However, while expo-cli starts and read the variable, it seems that the extension is unable to read those variables when I launch the debug configuration. Should I do some extra configuration in launch.json to read those variables I set with direnv?
