### ISSUE TITLE
VSCode wipes out my working node_modules

### ISSUE THREAD

**Issue by mark0978** [Microsoft/vscode-react-native#488] opened 2017-07-26 05:02 UTC
## Actual Behavior
1. Tell it to start the debugger, it begins removing and reinstalling things, how it knows what is appropriate is beyond me, because YARN installed everthing, and with EXPO XDE it runs, just without a debugger.
```
Getting exponent dependecy.
######### Making sure your project uses the correct dependencies for exponent. This may take a while... ##########
Checking if react native is from exponent......
Getting appropriate Exponent SDK Version to install......
Uninstalling current react native package.....
Installing exponent react native package...........
######### Dependencies are correct. Making sure you have any necessary configuration file. ##########
######### Project setup is correct. Generating entrypoint code. ##########
######### Starting Packager ##########
######### Executing command: react-native start --port 8081 --root .vscode --assetExts ttf,mp4 ##########
Scanning 547 folders for symlinks in /Users/markjones/personal/beoui-expo/node_modules (3ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/markjones/personal/beoui-expo 


React packager ready.

######### Packager started. ##########
```
2.  Then it proceeds to fail building due to packages that are "missing"
```
Loading dependency graph, done.
"Warning: Problem validating asset fields: Invalid URI \"./assets/icons/app-icon.png\"."
"Warning: Problem validating asset fields: Invalid URI \"./assets/icons/app-icon.png\"."
"Warning: 'html-entities' dependency is not installed.\nWarning: 'lodash' dependency is not installed.\nWarning: 'moment' dependency is not installed.\nWarning: 'react' peer depencency missing. Run `npm ls` in /Users/markjones/personal/beoui-expo to see full warning.\n\nIf there is an issue running your project, please run `npm install` in /Users/markjones/personal/beoui-expo and restart."
"Warning: 'html-entities' dependency is not installed.\nWarning: 'lodash' dependency is not installed.\nWarning: 'moment' dependency is not installed.\nWarning: 'react' peer depencency missing. Run `npm ls` in /Users/markjones/personal/beoui-expo to see full warning.\n\nIf there is an issue running your project, please run `npm install` in /Users/markjones/personal/beoui-expo and restart."
```

## Expected Behavior
1.  I expect it to leave my build environment alone and just attach the debugger.  I appreciate it trying to be helpful and all, but there needs to be some way to say, just debug the project.
2.  Is there some method to just act as the debug agent?  Attach to packager doesn't do anything of note, it outputs this error message, which neglects to give the key and section this port would be placed in.
```
[Error] "Could not debug. Cannot attach to packager. Are you sure there is a packager and it is running in the port 8081? If your packager is configured to run in another port make sure to add that to the setting.json."
```
Expo's packager runs on 19001 by default, no 8081, and not including the key here makes this almost useless.

## Software versions
- React-Native VS Code extension version: 0.3.2
- VSCode version: 1.14.2
- OS platform and version: OSX 10.11.16
- NodeJS version: v6.9.4
- React Native version:  "https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz"

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
See above^^^
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
**I have no View -> Toggle Output **  However I can find the Output window, but have not React-Native in the list box.
```
nothing
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
workbench.main.js:28 Overwriting extension <<.jsx>> to now point to mime <<text/javascript>>
(anonymous) @ workbench.main.js:28
workbench.main.js:29 [Extension Host] (node:14806) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.```

**Comment by vladimir-kotikov** [comment] 2017-07-28 15:26
Hey @mark0978, thanks for letting us know about the problems! The issue with reinstalling packages has been fixed in 0.4.0 - we don't try to install Expo's flavor of react-native and just rely on version that is already installed. Could you please try upgrading extension to 0.4.0 - I hope this would resolve this problem.

As for problem, described in 2. - this is something that is out of our control. Looks like those messages are being printed by the packager and perhaps they might be caused by RN dependency reinstallation and possibly will be resolved after extension upgrade. If this won't help please let us know and we'll investigate.

> Is there some method to just act as the debug agent? Attach to packager doesn't do anything of note, it outputs this error message, which neglects to give the key and section this port would be placed in.

Acknowledged. We definitely need to make this message more descriptive.

**Comment by vladimir-kotikov** [comment] 2017-08-11 09:14
@mark0978 - just a friendly ping - have you had a chance to upgrade the extension to see if the problems with reinstalling node_modules are resolved?

**Comment by mark0978** [comment] 2017-08-11 13:12
No, but I'll do it today

**Comment by vladimir-kotikov** [comment] 2017-08-15 13:45
@mark0978 any updates?

**Comment by mark0978** [comment] 2017-08-16 17:42
So when I run it with expo, everything works.
```
Starting React Native packager...
12:39:15 PM
Scanning 713 folders for symlinks in /Users/markjones/projects/sublyjs/node_modules (6ms)
12:39:16 PM
Loading dependency graph.
12:39:16 PM
Running packager on port 19001.
12:39:16 PM
12:39:17 PM
Dependency graph loaded.
12:39:17 PM
Project opened! You can now use the "Share" or "Device" buttons to view your project.
```

When I run it with vscode I get this error:
```
Looking for JS files in
   /Users/markjones/projects/sublyjs 


React packager ready.

######### Packager started. ##########
Loading dependency graph, done.
Bundling `index.ios.js`  0.0% (0/1), failed.
error: bundling failed: "Cannot find entry file index.ios.js in any of the roots: [\"/Users/markjones/projects/sublyjs\"]"
```

**Comment by vladimir-kotikov** [comment] 2017-08-17 10:15
@mark0978 when you running app in VSCode, how exactly are you doing this? Are you using "React-native: " command from command pallette or starting a debugging? If second - which debug configuration are you using?

The error message you're seeing in "output" window is very similar to what people were seeing in #432 (see https://github.com/Microsoft/vscode-react-native/issues/432#issuecomment-321545063) and likely doesn't meant that there is a "real" error - it's there just because we failed to "prewarm" packager which is not critical for debugging. However we execute "prewarming" only when running react-native apps, not Exponent so it's likely that you just used wrong launch config for running your Expo app.

**Comment by vladimir-kotikov** [comment] 2017-09-07 11:25
@mark0978 just a friendly ping. Are you still having any issues? If not I'm going to close this in a couple of days.

**Closed** 2017-09-11 11:02 UTC
Labels: bug, known-issues, need-more-info, triaged
