### ISSUE TITLE
Breakpoints not hit in typescript files

### ISSUE THREAD

**Issue by seyaobey** [Microsoft/vscode-react-native#438] opened 2017-04-16 22:41 UTC
## Actual Behavior
1. I have created a fresh react-native project (react-native init my_project)
2. I have added a tsconfig.json and enable sourcemap (I have tried also inlineSourceMap:true with no solution)
3. I have added a simple .tsx file compiled into the output directory and referenced and rendered in the index.android.js entry file. Then I have set a breakpoint in the componentDidMount method. Breakpoint is never hit but appears grayed out with message: breakpoint ignored because generated code not found. (I have looked at several similar issues at stackoverflow as well as here at github).

## Expected Behavior
1. Breakpoints should be hit

## Software versions
- React-Native VS Code extension version: 0.3.2
- VSCode version: 1.9.1
- OS platform and version: windows 8.1 
- NodeJS version: v6.9.2
- React Native version: 0.41.2

**Comment by vladimir-kotikov** [comment] 2017-06-08 07:21
This is a duplicate of #328, please take a look at the conversation there to find a suitable workaround

**Closed by vladimir-kotikov** 2017-06-08 07:21 UTC
Labels: typescript
