### ISSUE TITLE
TypeError: exports.DOMException is not a constructor

### ISSUE THREAD

**Issue by shlaikov** [microsoft/vscode-react-native#1133] opened 2019-10-09 11:35 UTC
![image](https://user-images.githubusercontent.com/32372875/66645336-dacb0d80-ec2b-11e9-9183-f909033c0bfc.png)

## First ex.
```
TypeError: exports.DOMException is not a constructor
    at http://localhost:8081/src/index.tsx.bundle?platform=ios&dev=true&minify=false:30843:7
    at http://localhost:8081/src/index.tsx.bundle?platform=ios&dev=true&minify=false:30402:68
    at http://localhost:8081/src/index.tsx.bundle?platform=ios&dev=true&minify=false:30403:5
```
DOMException is undefined.

## Second ex. it's my issue.
```
Error: 400: An update check must include a valid deployment key - please check that your app has been configured correctly. To view available deployment keys, run 'code-push deployment ls <appName> -k'.
```

_Originally posted by @shlaikov in https://github.com/microsoft/vscode-react-native/issues/1131#issuecomment-539947615_

**Comment by RedMickey** [comment] 2019-10-11 10:37
Hi @shlaikov, we have investigated this issue and found out that `exports.DOMException is not a constructor` exception is expected behavior.
React Native Tools extension debugs React Native apps as a Node.js processes. There aren't `DOM` modules in Node.js global context, so such an exception is thrown. With respect to your situation the exception occurs because React Native fetch function is used in some project's dependencies or app code.
This exception is generated in [whatwg-fetch](https://github.com/github/fetch) package which is a polyfill for fetch function. However `exports.DOMException is not a constructor` exception is successfully handled by `whatwg-fetch` implementation and the corresponding `DOMException` object  is created.
We created [an issue](https://github.com/github/fetch/issues/724) in `whatwg-fetch` repo, so you can track it there.
Since this behavior is connected with external package I'm closing that issue, feel free to open new ones if needed.

**Closed** 2019-10-11 10:39 UTC
Labels: external-report, investigating
