### ISSUE TITLE
Can't use with existing projects

### ISSUE THREAD

**Issue by ferologics** [Microsoft/vscode-react-native#404] opened 2017-02-24 15:27 UTC
## Actual Behavior
1. Run `Debug iOS`
2. Build fails

## Expected Behavior
1. Run `Debug iOS`
2. Runs the app and connects to the debugger

## Software versions
- React-Native VS Code extension version: 0.3.1
- VSCode version: Version 1.9.1 (1.9.1)
- OS platform and version: macOS Sierra 10.12.2 (16C67)
- NodeJS version: v6.6.0
- React Native version: react-native-cli: 2.0.1, react-native: 0.41.0

## launch.json
```json
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug iOS",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios",
            "sourceMaps": true,
            "target": "device",
            "outDir": "${workspaceRoot}/.vscode/.react"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/start",
            "cwd": "${workspaceRoot}"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "port": 5858
        }
    ]
}
```

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
...    /Applications/Xcode-unsigned.app/....
1 error generated.

** BUILD FAILED **
The following build commands failed:
	CompileC /Users/master/Projects/App/build/Build/Intermediates/RNSVG.build/Debug-iphoneos/RNSVG.build/Objects-normal/armv7/RNSVGPercentageConverter.o Utils/RNSVGPercentageConverter.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/master/Projects/App/build/Build/Intermediates/RNSVG.build/Debug-iphoneos/RNSVG.build/Objects-normal/armv7/RNSVGRect.o Shapes/RNSVGRect.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/master/Projects/App/build/Build/Intermediates/RNSVG.build/Debug-iphoneos/RNSVG.build/Objects-normal/armv7/RNSVGEllipse.o Shapes/RNSVGEllipse.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/master/Projects/App/build/Build/Intermediates/RNSVG.build/Debug-iphoneos/RNSVG.build/Objects-normal/armv7/RNSVGImage.o Elements/RNSVGImage.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(4 failures)
[Error] "Could not debug. Error while executing command 'xcodebuild -project /Users/master/Projects/App.xcodeproj -scheme App -destination generic/platform=iOS -derivedDataPath /Users/master/Projects/App/ios/build': Error while executing command 'xcodebuild -project /Users/master/Projects/App/ios/App.xcodeproj -scheme App -destination generic/platform=iOS -derivedDataPath /Users/master/Projects/App/ios/build'"
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
Getting exponent dependecy.
######### Checking react native is correctly setup. This may take a while... ##########
Checking if the correct react native is installed..
######### Starting Packager ##########
######### Executing command: react-native start --port 8081 ##########
Scanning 490 folders for symlinks in /Users/master/Projects/App/node_modules (11ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/master/Projects/App 


React packager ready.

Loading dependency graph, done.
######### Packager started. ##########
Bundling `index.ios.js`
  Transforming modules  100.0% (505/505), done.
######### The Bundle Cache was prewarmed. ##########
######### Attaching to running React Native packager ##########
######### Checking react native is correctly setup. This may take a while... ##########
Checking if the correct react native is installed..
######### Packager is already running. ##########
Bundling `index.ios.js`
  No module changed.
######### The Bundle Cache was prewarmed. ##########
######### Attaching to running React Native packager ##########
######### Checking react native is correctly setup. This may take a while... ##########
Checking if the correct react native is installed..
######### Packager is already running. ##########
Bundling `index.ios.js`
  No module changed.
######### The Bundle Cache was prewarmed. ##########
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
nothing like this in my help tab.
```

- Culprit
```
PCH was compiled with module cache path '/Users/master/Projects/App/ios/build/ModuleCache/2PTX7EUZK1T93', but the path is currently '/Users/master/Projects/App/build/ModuleCache/2PTX7EUZK1T93'
```

## What I did

Because the plugin [expects it to be purely React Native project](http://imgur.com/a/JLRs6) I tried to hack a bit so [I symlinked the current dir as `ios`](http://imgur.com/a/Gdcfu) b/c launch.json script `"platform":"ios"` prop is looking for this directory. It doesn't expect to be in a previously non-react-native project.

VS Code also doesn't generate the `.launchReactNative` file for me even though the package.json has React Native as a dependency.

As I said, the problem is that the plugin only supports projects that are conforming to the classical React Native structure, not accounting for hybrid apps with a different structure that need custom CocoaPods, etc. The build is failing on a cocoapod but when compiled inside Xcode it works.

## What I'm doing now

[Moving the entire project](http://stackoverflow.com/questions/4414181/moving-files-into-a-real-folder-in-xcode) inside `./ios`

- output
```
** BUILD FAILED **
The following build commands failed:
	Ld build/Build/Intermediates/App.build/Debug-iphoneos/App.build/Objects-normal/arm64/App normal arm64
	Ld build/Build/Intermediates/App.build/Debug-iphoneos/App.build/Objects-normal/armv7/App normal armv7
(2 failures)
[Error] "Could not debug. Error while executing command 'xcodebuild -project /Users/master/Projects/App/ios/App.xcodeproj -scheme App -destination generic/platform=iOS -derivedDataPath /Users/master/Projects/App/ios/build': Error while executing command 'xcodebuild -project /Users/master/Projects/App/ios/App.xcodeproj -scheme App -destination generic/platform=iOS -derivedDataPath /Users/master/Projects/App/ios/build'"
```

But it does compile about 100x more code until it fails to a point that I can't find the exact place of failure.

**Comment by vladimir-kotikov** [comment] 2017-02-28 10:12
@ferologics, it's not very clear, what your project structure look like.
Is the issue is just about having ios project in directory other than 'ios'? If so, you could specify path to your ios project folder via  `iosRelativeProjectPath` property in launch configuration (see https://github.com/Microsoft/vscode-react-native/blob/master/package.json#L226-L230).

As for absence of `launchReactNative.js` file - this entry is just a dummy to satisfy debugging protocol - technically we wouldn't need this property at all, but VSCode requires `program` property to be defined in all debug configurations.

**Comment by vladimir-kotikov** [comment] 2017-03-03 13:13
@ferologics, any updates?

**Comment by ferologics** [comment] 2017-03-03 15:00
@vladimir-kotikov I see, the `iosRelativeProjextPath` would've is what I was looking for. I moved the whole project inside so it's no longer needed. Still not able to compile though:

```
The following build commands failed:
	Ld build/Build/Intermediates/App.build/Release-iphoneos/App.build/Objects-normal/armv7/App normal armv7
	Ld build/Build/Intermediates/App.build/Release-iphoneos/App.build/Objects-normal/arm64/App normal arm64
(2 failures)
[Error] "Could not debug. Error while executing command 'xcodebuild -project /Users/master/Projects/App/ios/App.xcodeproj -scheme App -destination generic/platform=iOS -derivedDataPath /Users/master/Projects/App/ios/build': Error while executing command 'xcodebuild -project /Users/master/Projects/App/ios/App.xcodeproj -scheme App -destination generic/platform=iOS -derivedDataPath /Users/master/Projects/App/ios/build'"
```

**Comment by vladimir-kotikov** [comment] 2017-03-06 15:25
@ferologics, what about the result of `react-native run-ios` command? I bet that it's failing a well, since the extension uses exactly the same command as react-native does. Unfortunately we can't support all possible project configurations, so you'd need to update you project to be buildable from command line first.

**Comment by vladimir-kotikov** [comment] 2017-03-14 13:26
Okay, I'm closing this. @ferologics, feel free to reopen if this still an issue for you.

**Closed by vladimir-kotikov** 2017-03-14 13:26 UTC
