### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by NafisianCastle** [microsoft/vscode-react-native#1585] opened 2021-06-05 12:33 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-react-native`
- Extension Version: `1.5.1`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.56.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\User\AppData\Local\Temp\msjsdiag.vscode-react-native-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by RedMickey** [comment] 2021-06-08 06:58
Hi @NafisianCastle and thanks for the report. Could you please add the CPU profile file as pointed in your issue? This file is crucial for understanding the reason of the performance issues.

**Comment by RedMickey** [comment] 2021-06-09 14:21
@NafisianCastle, thanks for the .cpuprofile file. As seen in your cpu profile, it seems functions for requiring and resolving additional dependencies for Expo debugging took most of the time. Have you faced this behavior only once? 
Also, it will be very helpful if you describe when and under what conditions high cpu load message has appeared.

**Comment by NafisianCastle** [comment] 2021-06-09 15:56
Yeah, I faced this issue only once ,when i started react native tool. It was taking too much time to get started and after some minutes, this message was appeared and i submitted it.

**Comment by RedMickey** [comment] 2021-06-09 16:09
@NafisianCastle, did this happen when debugging an Expo app via `Debug In Exponent` debugging scenario?

**Comment by NafisianCastle** [comment] 2021-06-09 16:47
yeah, I was running the project with expo.

**Comment by JiglioNero** [comment] 2021-06-25 13:05
Hi @NafisianCastle We found out that the notification about high CPU load occurs while requiring the `xdl` package. It might be because the `xdl` package is quite large. Also requiring only the necessary module instead of the entire package didn't help. The issue is about `xdl` package having all modules described in the [file](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/internal.ts) where export of all the modules into package `xdl` is happening. It is needed to control the loading order of modules, to avoid circular dependencies and other errors. Because of this, when any submodule of the `xdl` package is required, actually the entire `xdl` package is required. So we decided to add it to [known issues](https://github.com/microsoft/vscode-react-native#known-issues).
Thanks for letting us know about this issue. Feel free to contuct us in the future.

**Closed** 2021-06-25 13:05 UTC
Labels: known-issues
