### ISSUE TITLE
Error while working with workspace: Current workspace does not contain React Native projects. (error code 710)

### ISSUE THREAD

**Issue by tewleap** [microsoft/vscode-react-native#1197] opened 2020-02-13 07:35 UTC
## Actual Behavior
1. Does not detect my react-native project even though all commands work (in the terminal in vscode)

## Expected Behavior
1. If the commands work at the root of my project then the extension should work too

## Software versions
- React-Native VS Code extension version: 1.14.0
- VSCode version: 1.42.0
- OS platform and version: MacOs 10.15.3
- NodeJS version: 13.8.0
- React Native version: 0.61.4
- Expo SDK version (include if relevant):

- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
Stack: Error: Error while executing command 'React Native: Reload App' (error code 101): Error while working with workspace: Current workspace does not contain React Native projects. (error code 710)
    at Function.getWrappedError (/Users/joelhalvarsson/.vscode/extensions/msjsdiag.vscode-react-native-0.14.0/src/common/error/internalError.js:35:16)
    at Function.wrapError (/Users/joelhalvarsson/.vscode/extensions/msjsdiag.vscode-react-native-0.14.0/src/common/error/errorHelper.js:17:44)
    at /Users/joelhalvarsson/.vscode/extensions/msjsdiag.vscode-react-native-0.14.0/src/common/entryPointHandler.js:43:72
    at _rejected (/Users/joelhalvarsson/.vscode/extensions/msjsdiag.vscode-react-native-0.14.0/node_modules/q/q.js:844:24)
    at /Users/joelhalvarsson/.vscode/extensions/msjsdiag.vscode-react-native-0.14.0/node_modules/q/q.js:870:30
    at Promise.when (/Users/joelhalvarsson/.vscode/extensions/msjsdiag.vscode-react-native-0.14.0/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/Users/joelhalvarsson/.vscode/extensions/msjsdiag.vscode-react-native-0.14.0/node_modules/q/q.js:788:41)
    at /Users/joelhalvarsson/.vscode/extensions/msjsdiag.vscode-react-native-0.14.0/node_modules/q/q.js:604:44
    at runSingle (/Users/joelhalvarsson/.vscode/extensions/msjsdiag.vscode-react-native-0.14.0/node_modules/q/q.js:137:13)
    at flush (/Users/joelhalvarsson/.vscode/extensions/msjsdiag.vscode-react-native-0.14.0/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
[Error] Error while executing command 'React Native: Reload App' (error code 101)
```

**Comment by RedMickey** [comment] 2020-02-13 08:51
Hi, @tewleap and thanks for reaching us. This error arises in case none of the folders in the workspace contain a React Native project.
Could you please provide us an example of the structure of your project and your workspace content(a set of folders in it), so we can investigate this issue faster and try to reproduce problem behavior?
Could you please also describe the way you launch debugging?

**Comment by tewleap** [comment] 2020-02-13 12:30
![image](https://user-images.githubusercontent.com/44545840/74435382-9911d400-4e64-11ea-8939-9b0fc05c4744.png)
None of commands for the extension works, I try to launch the packager through the command palette. 

I've tried the different tips on https://github.com/microsoft/vscode-react-native/issues/1012 but it's still the same, double checked that the ENV variables are the same etc.

**Comment by tewleap** [comment] 2020-02-13 18:01
The issue was resolved by uninstalling some extensions. Not exactly sure which one. Are there any known extensions that clashes with this?

**Comment by RedMickey** [comment] 2020-02-14 07:40
@tewleap, could you please send us a list of the deleted extensions?
For now there isn't info about extensions that could break React Native extension work. So we can investigate the deleted extensions and try to figure out which one of them could be incompatible with React Native extension.

**Comment by tewleap** [comment] 2020-02-14 20:54
After trying to add the extensions one by one (from memory) I discovered that https://marketplace.visualstudio.com/items?itemName=ms-vscode.autorest is the one that causes the error. I don't know if it's caused in conjunction with any other extension I have installed.
Hope this helps.

**Comment by RedMickey** [comment] 2020-02-17 11:47
@tewleap, we installed AutoRest extension and figured out that it caused unexpected termination of VS Code extension host (tried on Node.js v10.16.3 and v13.8.0). If extension host is terminated, we cannot use debug scenarios of extensions and run their commands.

![Screen Shot 2020-02-17 at 13 34 28](https://user-images.githubusercontent.com/33267199/74647049-05a21100-518c-11ea-9bee-5bfc38a3d708.png)
![Screen Shot 2020-02-17 at 13 37 07](https://user-images.githubusercontent.com/33267199/74647054-08046b00-518c-11ea-97f8-1f609bbbe31b.png)

It seems that this extension affects the work of all other extensions the same way. So we reported AutoRest extension's team with this issue.

It seems that this behavior is not caused by the React Native extension, so I am closing this issue. Feel free to reopen this or open new ones if needed.

**Closed by RedMickey** 2020-02-17 11:47 UTC
Labels: need-repro
