### ISSUE TITLE
version 0.6.2 of React Developer tools debug support completely borken 

### ISSUE THREAD

**Issue by Gremlin80** [Microsoft/vscode-react-native#646] opened 2018-02-23 20:36 UTC
## Actual Behavior
1. Several issues: 
(A) After one debug session THERE IS NO WAY to make another session work even restarting the PC. Clicking "debug" a second time will make the function hang infinitely without no output on console. **the only way to restore** another session is to **clear the extensions folder then reinstall vscode-react native tools (!)**
(B) During a debug session placing breakpoints simply does not work. they are IGNORED! 
the only way to break the execution is to type a debugger; instruction. this force the breakpoint to stop
(!)

2. 

## Expected Behavior
1. (A) One can do more that one debug session without being forced to ERASE the .vscode/extensions folder
 (B) Breakpoint should work without the need to type a "debugger" instruction
2. 

## Software versions
- React-Native VS Code extension version: 
- VSCode version: Version 1.20.1
- OS platform and version:  win 7 pro
- NodeJS version: 7.9.0 - 64 bit
- React Native version: 
react-native-cli: 2.0.1
react-native: 0.53.3

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by annakocheshkova** [comment] 2018-02-26 11:12
Hi @Gremlin80, thank you for your request. I have installed the latest version of VSCode and react native extension, but my debug session works fine the second, the third, and all the subsequent tries. 
Let me see what the `React Native` and `React Native: Run android` output says. Click "Debug android", and when it hangs infinitely, go to the "Output" window and paste the contents there. Then choose `React Native: Run android` in the dropdown list at the top right corner and also place the output there.

**Comment by domialex** [comment] 2018-02-27 04:26
Probably the same problem here.
I added a dependency, had to restart debugging, never ever got it to work again.
I erased the .vscode folder.
I didn't try to reinstall the extension thought.
Nothing happens when I press F5:
https://i.imgur.com/08iBW78.png

**Comment by annakocheshkova** [comment] 2018-02-27 09:05
@domialex Do I get it right that your issue is resolved by reinstalling the extension? If not, please provide the information I requested above.
Thank you!

**Comment by domialex** [comment] 2018-02-27 17:44
Resolved by reinstalling the extension. It happened twice also.

**Comment by Gremlin80** [comment] 2018-02-27 20:47
@domialex removing/installing the extension solves partially the issue, next time you use the extension after the first successful use, you will need do remove / reintstall.
unfortunately i'm not able to reach the pc (for three years) where i've experiencied the issue. i will retry with the last version soon and let you know about.

**Comment by Gremlin80** [comment] 2018-02-28 18:18
Additional Info:
the issue that is reporting the "hang up" problem after the first successful use is most probably related to windows version. Checking more in depth on the output console there is a message like this:


Error: connect ENOENT /tmp/vscode-reactnative-<pipe number>.sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/tmp/vscode-reactnative-<pipe number>.sock' }

this is a failing attempt to connect (via pipe) from the extension.
Since removing the .vscode directory and reinstalling from scratch solve temporarily the problem allowing another successful run i suspect there is something that is persisted and not cleared or updated across multiple uses.

**Comment by domialex** [comment] 2018-02-28 18:24
In my case `.vscode\extensions\vsmobile.vscode-react-native-0.6.3\node_modules\xdl\binaries\windows\adb\adb.exe` was still running even when vscode was closed. Not sure if it helps.
The problem is totally reproducible and only started this week in my case. If you need more info, tell me what I need to do to help.

**Closed** 2018-06-08 13:17 UTC
Labels: bug, priority-high, triaged
