### ISSUE TITLE
DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

### ISSUE THREAD

**Issue by zuigzm** [microsoft/vscode-react-native#1005] opened 2019-05-15 13:27 UTC
## Actual Behavior
1.  [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

## Expected Behavior
1. remove warnings or add ignore items

## Software versions
- React-Native VS Code extension version:  0.9.3
- VSCode version: 1.33.1
- OS platform and version: macOS
- NodeJS version: v10.15.3
- React Native version: 0.59.8

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: darwin x64
Adapter node: v10.2.0 x64
vscode-chrome-debug-core: 6.7.46
启动调试器应用辅助进程。
已建立代理(包装工具)与 React Native 应用程序之间的连接
调试器辅助进程在端口 41822 上已加载运行时

(node:1715) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
```

**Comment by ruslan-bikkinin** [comment] 2019-05-17 13:09
Hi @zuigzm and thanks for reaching us. Extension debugger runs React Native debugging worker as Node JS process on your machine, so looks like something from your code or from the packages you use causes such warning to be appeared. Usually, this warning is harmless and you shouldn't worry about it. Please refer to Node JS documentation page for more info about this warning: https://nodejs.org/api/deprecations.html#deprecations_dep0079_custom_inspection_function_on_objects_via_inspect.
I don't think that removing such warnings would be a good idea, because in some specific cases it may obstruct finding the cause of other problems.
I am closing this for now, feel free to re-open if needed.

**Closed by ruslan-bikkinin** 2019-05-17 13:09 UTC
