### ISSUE TITLE
Debugging with Expo - tries to connect to wrong packager port

### ISSUE THREAD

**Issue by GrandPoohBear** [Microsoft/vscode-react-native#553] opened 2017-10-18 03:34 UTC
## Actual Behavior
1. Setup debugging for an Expo project ( as outlined here https://github.com/Microsoft/vscode-react-native/blob/master/doc/expo.md )
2. Run debugger, get this error:
`[Error] "Could not debug. Cannot attach to packager. Are you sure there is a packager and it is running in the port 8081? If your packager is configured to run in another port make sure to add that to the setting.json."`
3.  Debugging doesn't work

## Expected Behavior
1. Debugger attaches to packager on port 19001

## Software versions
- React-Native VS Code extension version: 0.4.2
- VSCode version: 1.17.1
- OS platform and version: Mac OS 10.13
- NodeJS version: 6.11.3
- React Native version: 0.47.1
- Expo version: 44.0.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
[vscode-react-native] Starting Exponent Packager.
[vscode-react-native] Prewarming bundle cache. This may take a while ...
[vscode-react-native] Building and running application.
[vscode-react-native] Application is running on Exponent. Open your exponent app at exp://192.168.1.108:19000 to see it.
[vscode-react-native] Application is running on Exponent. Please shake device and select 'Debug JS Remotely' to enable debugging.
[vscode-react-native] Starting debugger app worker.
[Error] "Could not debug. Cannot attach to packager. Are you sure there is a packager and it is running in the port 8081? If your packager is configured to run in another port make sure to add that to the setting.json."

```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
Getting exponent dependecy.
######### Making sure your project uses the correct dependencies for exponent. This may take a while... ##########
Checking if this is Expo app......
######### Starting Packager ##########
######### Executing command: react-native start --port 8081 --root .vscode --assetExts ttf ##########
Scanning 689 folders for symlinks in /Users/andy/git/starsnap/node_modules (11ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/andy/git/starsnap
   /Users/andy/git/starsnap/.vscode 


React packager ready.

######### Packager started. ##########
"Warning: You are using npm version 5.4.2. There may be bugs in this version, use it at your own risk. We recommend version 4.6.1."
"Warning: You are using npm version 5.4.2. There may be bugs in this version, use it at your own risk. We recommend version 4.6.1."
2017-10-17 22:31 node[8574] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-10-17 22:31 node[8574] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-10-17 22:31 node[8574] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1020:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1421:9)

```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
workbench.main.js:sourcemap:28 [Extension Host] (node:7879) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```

**Comment by iTOYS** [comment] 2017-10-23 15:25
Hi @GrandPoohBear 
I can't repro this issue. Could you please update vscode-react-native tools to 0.4.4 and trying again.
Thanks!

**Comment by GrandPoohBear** [comment] 2017-10-27 03:38
Updated to 0.4.4, but now I think I might be hitting a different issue:

Output:
```
[Info] Making sure your project uses the correct dependencies for exponent. This may take a while...

Checking if this is Expo app......
.........
[Info] Starting Packager

Scanning 689 folders for symlinks in /Users/andy/git/starsnap/node_modules (4ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/andy/git/starsnap
   /Users/andy/git/starsnap/.vscode 


React packager ready.

[Info] Packager started.

[Warning] Warning: You are using npm version 5.4.2. There may be bugs in this version, use it at your own risk. We recommend version 4.6.1.

[Warning] Warning: You are using npm version 5.4.2. There may be bugs in this version, use it at your own risk. We recommend version 4.6.1.

[Error] Error starting tunnel: XDLError: TypeError: Cannot read property 'toLowerCase' of undefined

[Error] Error starting tunnel: XDLError: TypeError: Cannot read property 'toLowerCase' of undefined

[Error] XDLError: TypeError: Cannot read property 'toLowerCase' of undefined

2017-10-26 22:31 node[47932] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-10-26 22:31 node[47932] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-10-26 22:31 node[47932] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-10-26 22:31 node[47932] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1020:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1421:9)
```

In the Debug Console:
```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.3
Could not debug. TypeError: Cannot read property 'toLowerCase' of undefined
Error processing "disconnect": TypeError: Cannot read property 'noDebug' of undefined
    at Object.terminateSession (/Users/andy/.vscode/extensions/ms-vscode.node-debug2-1.18.3/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:198:63)
    at Object.terminateSession (/Users/andy/.vscode/extensions/ms-vscode.node-debug2-1.18.3/out/src/nodeDebugAdapter.js:400:15)
    at Object.disconnect (/Users/andy/.vscode/extensions/ms-vscode.node-debug2-1.18.3/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:821:21)
    at Object.dispatchRequest (/Users/andy/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugSession.js:75:82)
    at Object.disconnect (/Users/andy/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/src/debugger/nodeDebugWrapper.js:83:23)
    at Object.dispatchRequest (/Users/andy/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/src/debugger/nodeDebugWrapper.js:44:29)
    at Object.ProtocolServer._handleData (/Users/andy/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/node_modules/vscode-debugadapter/lib/protocol.js:104:38)
    at Socket.<anonymous> (/Users/andy/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/node_modules/vscode-debugadapter/lib/protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
```
I saw a similar issue referenced here: https://github.com/Microsoft/vscode-node-debug2/issues/149 ... Happy to open a separate issue if you think this is something real and not just a misconfiguration.

**Comment by tiofabby** [comment] 2017-10-27 10:36
Same issue here when trying to debug react native code: 
<<vscode-chrome-debug-core: 3.17.3
Could not debug. Unknown error
Error processing "disconnect": TypeError: Cannot read property 'noDebug' of undefined
>>
Thank you

**Comment by jorgutdev** [comment] 2017-10-29 19:40
This is also happening to me, is anyone working on this? I love this extension

**Comment by iTOYS** [comment] 2017-10-30 10:16
OK, seems like two problems there:
1. Bug in [vscode-node-debug2](https://github.com/Microsoft/vscode-node-debug2/issues/149)
2. `react-native -v` has different outputs on windows and mac
windows:
```
$react-native -v
react-native-cli: 2.0.1
react-native: 0.49.3
```
mac:
```
$react-native -v
react-native-cli: 2.0.1
react-native: https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz
```
But we expected `semver` like version(like on windows).
Working on it!

**Comment by iTOYS** [comment] 2017-10-30 11:06
#https://github.com/expo/expo/issues/882

**Comment by iTOYS** [comment] 2017-11-22 12:20
Hi @GrandPoohBear 
Just a friendly ping, do you still have this problem?

**Comment by GrandPoohBear** [comment] 2017-11-26 03:20
Hi @iTOYS , it seems like I'm getting closer, but not quite there yet.  I got rid of the error watching the file by explicitly installing watchman via homebrew, so that's better.  It seems to cleanly get to the QR code, and when I scan it in expo on my device, it starts debugging mode and outputs a line like this to the Debug Console:
`Debugger worker loaded runtime on port 11091` (the port changes on subsequent scans)

However, I hit a redbox on the device as soon as it loads the js bundle:
![img_13d21c791eee-1](https://user-images.githubusercontent.com/1160174/33236851-383c1274-d226-11e7-8934-279dbb00bdaa.jpeg)

So, still hitting a bit of a wall!

Note that the redbox refers to port 8081, while the URL above the QR code mentions port 19000.  Not sure if that's relevant, but thought I'd point it out.  Any ideas?

**Comment by iTOYS** [comment] 2017-11-27 12:39
Well, it's correct. We've run react-native `packager` on `8081` port.
Could you please paste here your `app.json` config?

**Comment by jhalborg** [comment] 2017-12-01 11:03
I have a similar issue. After using remotedev.io as my redux inspector for a while, I got tired of it's inconsistancies, and have now switched to React Native Debugger. I'm running my app (Expo) on localhost:19001, and the React Native Debugger connects just fine. I miss being able to set breakpoints in VSCode though, so I thought I'd try attaching VSCode to the process for breakpoints and inspections. 

I configured the standard `launch.json` `Attatch to debugger` profile  from

```
{
      "name": "Attach to packager",
      "program": "${workspaceRoot}/.vscode/launchReactNative.js",
      "type": "reactnative",
      "request": "attach",
      "sourceMaps": true,
      "outDir": "${workspaceRoot}/.vscode/.react",
    },
```
to
```
{
      "name": "Attach to packager",
      "program": "${workspaceRoot}/.vscode/launchReactNative.js",
      "type": "reactnative",
      "request": "attach",
      "sourceMaps": true,
      "outDir": "${workspaceRoot}/.vscode/.react",
      "port": "19001"
    },
```
but I get the error mentioned in this issue, 
`Could not debug. Cannot attach to packager. Are you sure there is a packager and it is running in the port 8081? If your packager is configured to run in another port make sure to add that to the setting.json.`

What should I do to attach VSCode to the process?

**Comment by svekl** [comment] 2017-12-01 15:54
I see a bug in extension, looks like it doesn't respect port setting in `launch.json` for attach to packager case. I will create a PR with fix now.

Meanwhile, as a quick workaround, you can set `"react-native.packager.port": 19001` in `settings.json`

By the way, did you try to run packager from our extension directly? We have `Debug in Exponent` launch configuration, that runs packager, attaches to it and provides you a QR code for Expo.

**Comment by jhalborg** [comment] 2017-12-03 09:44
Until now, I've run the packager from the extension which has worked great. The reason I'm running into this problem is that I want to monitor my redux store, and have grown tired of the remote-redux-tools approach, as it only works some of the time. Therefore I've tried switchin to the full React Native Debugger, which works great - except that using that approach, I've lost the ability to inspect and breakpoint from VSC. 

The quickfix seems to work in that it respects the port. I now run into the problem, that the React Native Debugger seems to occupy the debug port, so VSC won't attach: 

```
Established a connection with the Proxy (Packager) to the React Native application
Disconnected from the Proxy (Packager) to the React Native application. Retrying reconnection soon...
Could not debug. Another debugger is already connected to packager. Please close it before trying to debug with VSCode.
```

This is not a bug, but a problem. I'm not sure how I can have a redux monitoring window open at the same time as using the RN extension to debug - is that even possible, without using a proxy such as remotedev.io?

**Comment by svekl** [comment] 2017-12-04 11:35
@jhalborg If I understand right, you need to attach two chrome debuggers to same packager? If yes - then it's not possible.

So, I think, you have to use some separate redux tools without debugger to be able to debug in VSCode and use redux tools at the same time.

**Comment by svekl** [comment] 2017-12-04 11:37
I googled a bit and found some extension, never used it and not sure if it even works, but did you try it?
https://marketplace.visualstudio.com/items?itemName=jingkaizhao.vscode-redux-devtools

**Comment by jhalborg** [comment] 2017-12-04 12:14
Yes, that's correct - so it is indeed impossible. I have to keep using remotedev.io (https://github.com/zalmoxisus/remote-redux-devtools) which the extension you link to wraps into a VSCode extension. 

Thanks for the help anyways :-) At least we discovered the port bug :-)

**Comment by svekl** [comment] 2017-12-04 12:45
Yeah, thanks for report! =)

**Comment by uri3000** [comment] 2018-01-18 08:32
Is there a way to set a fixed port on the Exp app on Android? it changes automatically to 19001 if 19000 is temporarily unavailable (which can naturally happen) and then it's impossible to change it back to 19000.

**Comment by iTOYS** [comment] 2018-01-18 10:11
Hi @uri3000, quick search haven't gave result(
I suppose that [Expo Github](https://github.com/expo/expo/) is better place for this question.

Thanks!

**Comment by ruslan-bikkinin** [comment] 2018-05-10 11:37
I am closing this due to original issue has been resolved. If you are struggling with similar problem during debugging with expo, please, submit separate issue.

**Closed by ruslan-bikkinin** 2018-05-10 11:37 UTC
Labels: bug, external, triaged
