### ISSUE TITLE
Breakpoint does not work if placed in render() methods, does work well when placed in (for example) the body of button event press handler

### ISSUE THREAD

**Issue by Gremlin80** [Microsoft/vscode-react-native#659] opened 2018-03-06 19:37 UTC
## Actual Behavior
1. If you set a break point on the render method ( for example) when the execution reach the method the debugger should be invoked and execution should stop.
Nothing happens.
If you remove the breakpoint and place instead a "debugger" instruction when the execution reach the statement the debugger pop ups and execution stops
2. 

## Expected Behavior
1.  Should stop on breakpoint
2. 

## Software versions
- React-Native VS Code extension version: 0.6.4
- VSCode version: Version 1.20.1 - Commit f88bbf9137d24d36d968ea6b2911786bfe103002 - Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
- Node 7.9.0

- OS platform and version: windows 7 - Architecture x64

- React Native version: react-native-cli: 2.0.1
react-native: 0.52.0

More detailed description:
https://github.com/Microsoft/vscode-react-native/issues/659#issuecomment-374182223

**Comment by WHATSAF** [comment] 2018-03-07 03:54
The same issue on `macOS 10.13.3`.

**Comment by ruslan-bikkinin** [comment] 2018-03-07 11:56
Hi @Gremlin80 and @WHATSAF and thanks for submitting the issue. Does this issue behave the same as in https://github.com/Microsoft/vscode-react-native/issues/625 or there is something more specific here? Was this issue reproduced on the older versions of `vscode-react-native` and `vsccode`?

**Comment by Gremlin80** [comment] 2018-03-07 19:14
Hi, ruslan-bikkinin. Not sure but it is probably related the #625 .
it is here from version 0.6.2, and  i faced it using expo but i also think it does appear with a standard react native app without expo.
It is easily reproducible, if you can't reproduce tell me please.
I think it is probably related to source maps because a debugger instruction correctly stop the execution bringing up the vs code ide window.

**Comment by ruslan-bikkinin** [comment] 2018-03-14 08:14
@Gremlin80 sorry for delay, I tried to reproduce it but with no success, so, yes, could you please share with me demo and repro steps?

**Comment by WHATSAF** [comment] 2018-03-14 08:26
Hi @ruslan-bikkinin .This is the issue that i commented in #625 .Wish it help.
[https://github.com/Microsoft/vscode-react-native/issues/625#issuecomment-371017546](url)

**Comment by ruslan-bikkinin** [comment] 2018-03-19 11:32
Reproduction steps (moved from #667)

## Actual Behavior
1. Add a button and define a event handler for onPress on 
2. Place a breakpoint into the render method, 
3. Place a breakpoint into the body of the handler body of (1)
4. the breakpoint on button event handler is working (when you press the button), the one into the render body does not work at all.

## Expected Behavior
1.  Breakpoint should work (as in chrome) into the render and onPress handler method

## Software versions
- React-Native VS Code extension version:  0.6.5 and previous 0.6.4 0.6.3
- VSCode version: latest
- OS platform and version: win7
- NodeJS version: does not matter
- React Native version: 0.54

**Comment by FRizzonelli** [comment] 2018-06-05 08:38
I'm getting a similar issue, breakpoints works perfectly in event and methods, but in render() or constructor are not placed correctly (sourceMap problem I think). I'm using TS with https://github.com/ds300/react-native-typescript-transformer

- React-Native VS Code extension version: latest
- VSCode version: latest
- OS platform and version: macOs
- Typescript 2.8.3

To point out that the breakpoints works perfectly if I use react-native <= 0.51.1.
It starts with this strange behaviour only when I upgrade to 0.52 or greater.

Hope it helps to figure it out

**Comment by ruslan-bikkinin** [comment] 2018-06-07 12:11
Hi guys. Seems to be that current issue is a duplicate of https://github.com/Microsoft/vscode-react-native/issues/667, because I tried to reproduce it again with VS Code 1.24 but it has worked without any problem. @FRizzonelli could you please try to update VS Code to 1.24 and reproduce your issue in there? I am closing this one for now, but if your problem will be still persist, feel free to submit another one so we could discuss your specific case.

**Closed by ruslan-bikkinin** 2018-06-07 12:11 UTC
Labels: bug, priority-high, triaged
