### ISSUE TITLE
Breakpoint does not work if placed in render() methods, does work well when placed in (for example) the body of button event press  handler

### ISSUE THREAD

**Issue by Gremlin80** [Microsoft/vscode-react-native#667] opened 2018-03-18 15:40 UTC
## Actual Behavior
1. Add a button and define a event handler for onPress on 
2. Place a breakpoint into the render method, 
3. Place a breakpoint into the body of the handler body of (1)
4. the breakpoint on button event handler is working (when you press the button), the one into the render body does not work at all.

## Expected Behavior
1.  Breakpoint should work (as in chrome) into the render and onPress handler method

## Software versions
- React-Native VS Code extension version:  0.6.5 and previous 0.6.4 0.6.3
- VSCode version: latest
- OS platform and version: win7
- NodeJS version: does not matter
- React Native version: 0.54

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by ruslan-bikkinin** [comment] 2018-03-19 11:35
Hi @Gremlin80 I am closing this as duplicate of #659. Also I moved repro steps there too: https://github.com/Microsoft/vscode-react-native/issues/659#issuecomment-374182223.

**Closed by ruslan-bikkinin** 2018-03-19 11:35 UTC
Labels: duplicate
