### ISSUE TITLE
[Bug] Loading Environment variables in app config is broken

### ISSUE THREAD

**Issue by superandrew** [microsoft/vscode-react-native#1302] opened 2020-05-29 08:05 UTC
It seems that the debugger is unable to load environment variables in app config

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. Step 1
put an app configuration in (e.g. `./tenant_configs/tenant1.app.json`)

2. Step 2
using https://github.com/tusbar/babel-plugin-dotenv-import import an environment variable from an .env file
3. Step 3
try to read values from those variables

```
import { ConfigContext, ExpoConfig } from "@expo/config/build";
import { mergeDeep } from "./utils/objectUtils";
import { TENANCY_NAME } from "@env";

export default ({ config }: ConfigContext): ExpoConfig => {

  let customConfig = require(`./tenant_configs/${TENANCY_NAME}.app.json`);

  return customConfig;

};
```
4. Step 4 
Launch the debugger

## Expected behavior
The application should launch normally, as it does while running `expo r`

## Debug output
Could not debug
<details>
<summary>Debug Console</summary>

```text

OS: darwin x64
Adapter node: v12.8.1 x64
vscode-chrome-debug-core: 6.8.8
Could not debug. Failed to read config at: /Users/superandrew/code/<appname>/app.config.ts

```
</details>

<details>
<summary>React Native output channel</summary>

```text

ConfigError: Failed to read config at: /Users/superandrew/code/<appname>/app.config.ts


```
</details>

<details>
<summary>Developer Tools console</summary>

```text

console.ts:137 [Extension Host] (node:26677) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166

```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text
Didn't find any issues with your project!
```

* `envinfo`:

```text
 System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Xeon(R) CPU E5-1680 v2 @ 3.00GHz
    Memory: 9.05 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.8.1 - ~/.nvm/versions/node/v12.8.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.8.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
    Gradle: 6.3 - /usr/local/bin/gradle
    Homebrew: 2.2.14 - /usr/local/bin/brew
    pip3: 20.0.2 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.24.3 - /usr/bin/git
    Clang: 1103.0.32.62 - /usr/bin/clang
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
  Virtualization:
    Docker: 19.03.8 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.1 - /usr/bin/vim
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_251 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.11 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.7.7 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    PostgreSQL: 12.3 - /Applications/Postgres.app/Contents/Versions/latest/bin/postgres
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 83.0.4103.61
    Safari: 13.1
```

 
* React Native Tools extension version: latest
* Expo SDK version (if applicable): 37

**Comment by superandrew** [comment] 2020-05-29 09:45
Adding some more information. I tried debugging the extension, unfortunately I wasn't able to see where it halts, but it logs no error on the debug console, expo connects in the host window (the qr code is generated), but it remain stuck at loading at 99.75%

**Comment by RedMickey** [comment] 2020-06-03 11:20
Hi @superandrew and thanks for reaching us. The extension uses `@expo/xdl` package to start Expo server.  We found out that the problem is in incorrect CWD parameter in the [`evalConfig`](https://github.com/expo/expo-cli/blob/master/packages/config/src/getConfig.ts#L52) method. This method spawns a child process to get dynamic configurations. We proposed [the PR](https://github.com/expo/expo-cli/pull/2220) to Expo to fix this issue.
But until it is merged, you can try to fix it manually:
1. Open `~/.vscode/extensions/msjsdiag.vscode-react-native-0.16.0/node_modules/@expo/config/build/getConfig.js` file. If it doesn't exist, try to start `Debug in Exponent` debug scenario and the extension will download `@expo/xdl` package.
1. In the `getConfig.js` file find [`evalConfig`](https://github.com/expo/expo-cli/blob/master/packages/config/src/getConfig.ts#L52) method and add the following code [here](https://github.com/expo/expo-cli/blob/master/packages/config/src/getConfig.ts#L61):
    ```
    cwd: request.projectRoot
    ```
    It should look something like this:
    ![image](https://user-images.githubusercontent.com/33267199/83630288-3e7fbd80-a5a4-11ea-9f70-3933d86b7890.png)
1. Reopen VS Code editor

Please let us know about your results.

**Comment by molant** [comment] 2020-06-03 12:59
@RedMickey it looks like your PR in Expo [fails one of the tests](https://github.com/expo/expo-cli/pull/2220/checks?check_run_id=734301117). You might want to take a look.

**Comment by SounD120** [comment] 2020-06-03 13:14
@molant Looks like a random failure. Not sure if we should do anything about it.

**Comment by superandrew** [comment] 2020-06-04 22:30
super! I can confirm that it works with the updated setting.

**Comment by RedMickey** [comment] 2020-06-05 07:18
@superandrew, yes, I think this fix will be available in new release of `@expo/config` package. After that you just need to reinstall the extension in order to the extension can download a new version of `@expo/xdl` package.

**Comment by RedMickey** [comment] 2020-06-25 11:07
@superandrew, a new version of the `@expo/xdl` package with the fix https://github.com/expo/expo-cli/pull/2220  has been released. But it contains the bugs https://github.com/expo/expo-cli/issues/2270, https://github.com/expo/expo-cli/issues/2257, so for now it can work incorrectly. I don't recommend to reinstall the extension to update the `@expo/xdl` package until these bugs have fixed. I'm closing this issue, please, feel free to open new ones if needed.

**Closed by RedMickey** 2020-06-25 11:07 UTC
Labels: bug, external-report

**Comment by superandrew** [comment] 2020-06-26 14:32
terrific news, glad that this has been fixed! I'll wait, thank you @RedMickey

**Comment by superandrew** [comment] 2020-10-08 13:25
I am not sure if I update something but I'm back to where I standed with this problem. I noticed that expo/cli might have broken again https://github.com/expo/expo-cli/pull/2220. @RedMickey are you aware of this?

right now my configuration is:

```
import { ConfigContext, ExpoConfig } from "@expo/config/build";
import { mergeDeep } from "./utils/objectUtils";
import { TENANCY_NAME } from "react-native-dotenv";

export default ({ config }: ConfigContext): ExpoConfig => {
  try {
    let customConfig = require(`./tenant_configs/${TENANCY_NAME}.app.json`);
    if (!customConfig) {
      customConfig = {};
    }
    return mergeDeep({}, config, customConfig);
    //return customConfig;
  } catch (e) {
    throw new Error(`Missing app configuration for tenant ${TENANCY_NAME}`);
  }
};
```

```
$ expo start
Starting project at /Users/superandrew/code/irideweb2-iridewebapp
Failed to read config at: /Users/superandrew/code/irideweb2-iridewebapp/app.config.ts
ConfigError: Failed to read config at: /Users/superandrew/code/irideweb2-iridewebapp/app.config.ts
```

**Comment by SounD120** [comment] 2020-10-09 13:25
@superandrew I think that it is better to open new one, since it might be connected to other issues.
