### ISSUE TITLE
Extension Debugging not working after Update SDK tools

### ISSUE THREAD

**Issue by banihasan** [microsoft/vscode-react-native#1027] opened 2019-06-13 10:40 UTC
## Actual Behavior
- Before UPDATE SDK Tools Android, Extension Debugging console working, just fine!

## Expected Behavior
- After UPDATE SDK Android Tools, Extension Debugging not working 

Without Extension, manual command debug running normally and use Chrome Debugging http://localhost:8081/debugger-ui/ 
## Software versions
- Android SDK version: 26.1.1
- Android SDK Platform-Tools: 29.0.1
- React-Native VS Code extension version: 0.9.3
- OS platform and version: [Devices] Android 9.0 (API-28)
- NodeJS version: 10.2.0
- React Native version: 0.59.9
- React Native Cli: 2.0.1
- VSCode version: 1.35.1

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
Could not debug. Error while executing command 'D:\Android\tools\sdk\platform-tools\adb -s "10.9.27.25:5555" shell getprop ro.build.version.sdk': Command failed: D:\Android\tools\sdk\platform-tools\adb -s "10.9.27.25:5555" shell getprop ro.build.version.sdk
```
- Output of the NPM start output :
```
[Error] Error: Error while executing command 'D:\Android\tools\sdk\platform-tools\adb -s "10.9.27.25:5555" shell getprop ro.build.version.sdk': Command failed: D:\Android\tools\sdk\platform-tools\adb -s "10.9.27.25:5555" shell getprop ro.build.version.sdk
```

**Comment by SounD120** [comment] 2019-06-13 12:47
Hi @banihasan . This issue is a duplicate of #1026 . I'd recommend you to downgrage platform-tools to version 28. To do that please do the following:
* Open Android Studio
* Click `Configure`
* Choose `SDK Manager`
* Open `SDK Tools`
* Uncheck `Android SDK Platform Tools` and click `Apply`
* Download `Android SDK Platform Tools 28` using this link : https://dl.google.com/android/repository/platform-tools_r28.0.0-windows.zip
* Unzip this folder into `Android SDK Location` folder that is indicated at SDK Manager

This issue will be resolved as soon as Google will release updated SDK with the fix.

**Closed by SounD120** 2019-06-13 12:47 UTC
Labels: android, duplicate, external

**Comment by banihasan** [comment] 2019-06-14 02:08
@SounD120 Okay, thanks dude
