### ISSUE TITLE
Debugging issue with Haul

### ISSUE THREAD

**Issue by CrazzzyDev** [Microsoft/vscode-react-native#875] opened 2018-12-25 07:05 UTC
## Actual Behavior

1. "Attach to Packager" does not connect to debugger using Haul
- We have multi root projects. Each project has its own .vscode directory inside project folder.
- Haul debugger with Chrome is working fine. But when try to debug with VSCode debugger it gives below error.

## Expected Behavior
"Attach to Packager" should connect to debugger and allow debugging in VS Code

## Software versions
-React Native Tools VS Code extension version: 0.7.0
- VSCode version:  1.30.1
- OS platform and version: Mac OS 10.13.1
- NodeJS version: v8.12.0
- React Native version: 0.57.7
- Expo SDK version (include if relevant): - NA

## Outputs (Include if relevant)

Issue: Reference Error: fetch not found
file path : /.vscode/.react/debuggerWorker.js

**Comment by CrazzzyDev** [comment] 2018-12-28 17:33
@ruslan-bikkinin can you please help in this issue.

**Comment by SounD120** [comment] 2018-12-29 11:15
Hi @CrazzzyDev and thanks for contacting us. Could you please give us a minimal demo application where this issue is reproduces, and also describe your workflow with that multiroot project? This would be helpful for better understanding of the situation from our side.

**Comment by CrazzzyDev** [comment] 2018-12-29 15:49
@SounD120 Here are some more detail on issue:

--- RootProject
	- .vscode
	- package.json - common dependency 
	- common - sharing by all project
         * Project1
		- .vscode
		- package.json
		- index.js
	 * Project2
		- .vscode
		- package.json
		- index.js
	
I  am using Haul as package manager and my haul.config.js has some other loader as well.
Project has custom script to start normal app with haul. 

My Observation:
	- when I start vscode debugger it start default packager Metro and my app uses Haul packager. Does vscode debugger support debugging with Haul?
	- Open project 1, start debugger,  gives error fetch not found <project1>/.vscode/.react/debuggerWorker.js
	- Created new demo project(single root only, no multiroot) with Haul & trying to debug it. It gives below error.

Demo project: Debug Console error

Adapter node: v8.9.3 x64
vscode-chrome-debug-core: 3.17.3
Starting debugger app worker.
Could not debug. <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /debuggerWorker.js</pre>
</body>
</html>

**Comment by CrazzzyDev** [comment] 2019-01-02 13:54
@SounD120 Do you want me to send demo project(single root only, no multiroot) that's not working with Haul?

**Comment by ruslan-bikkinin** [comment] 2019-01-04 08:35
Hi @CrazzzyDev, I think multiroot demo project would be better.

**Comment by CrazzzyDev** [comment] 2019-01-09 06:31
@ruslan-bikkinin here is the demo https://github.com/CrazzzyDev/monorepoEx.
Integrated Haul with it and debugger is not working.

**Comment by SounD120** [comment] 2019-01-09 13:48
Hi @CrazzzyDev . We have found the core of the problem connected with `Cannot GET /debuggerWorker.js` error and it will be fixed in the new version of the extension. With respect to your question about debugging with Haul, yes extension support Haul debugging, but only via `Attach to packager` debug scenario, that means you must run packager and the application outside the VS Code.  In other cases the React Native Metro bundler will be used for debugging.

**Comment by SounD120** [comment] 2019-01-10 08:59
@CrazzzyDev We are performing prerelease testing right now, so as soon as we finish it a new version will be released. This issue were caused by the extension tried get `debuggerWorker.js` file from incorrect URL for projects with Haul, so you can try manually apply fix proposed in PR #880 to your installed extension at this path if you need to.
```
~/.vscode/extensions/vsmobile.vscode-react-native-0.7.0/src/debugger/scriptImporter.js
```
If you try, please let us know how it will work for you.

**Closed** 2019-01-10 14:58 UTC
Labels: bug, haul

**Comment by CrazzzyDev** [comment] 2019-01-10 18:21
@SounD120 I have tried the fix, seems it not working.
Steps I followed:
1) Applied #880 in my local scriptImporter.js file
2) Open monorepoEx/nativeB project to vscode
3) Start haul packager in terminal
4) Run ios app 
5) Vscode -> Debugger -> Attach to Package
6) It gives below error:

OS: darwin x64
Adapter node: v8.9.3 x64
vscode-chrome-debug-core: 3.17.3
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Disconnected from the Proxy (Packager) to the React Native application. Retrying reconnection soon...

Could not debug. Another debugger is already connected to packager. Please close it before trying to debug with VSCode.

**Comment by SounD120** [comment] 2019-01-11 10:16
@CrazzzyDev Please make sure that when you starting `Attach to packager` debug configuration no any other debugger is running on background. For example, Haul opens browser tab with its own debugger automatically when you start your application via Haul packager, so maybe you need to close it before you start `Attach to packager` and then reload your app.
