### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by geneus** [Microsoft/vscode-react-native#628] opened 2018-02-10 03:48 UTC
## Actual Behaviour
1. Launch VS Code
2. Throws error

## Expected Behaviour
1. Launch VS Code
2. **PROFIT**, _obviously_

## Software versions
- React-Native VS Code extension version: 0.5.7
- VSCode version: 1.20.0
- OS platform and version: Windows 10 Pro 64-Bit 1709
- NodeJS version: 9.3.0
- React Native version: 0.52

After [a whole lotta hair pulling](https://github.com/Microsoft/vscode/search?q=Extension+host+terminated+unexpectedly&type=Issues&utf8=✓), and removing/adding extensions, this is the only one that throws the error.

**Comment by annakocheshkova** [comment] 2018-02-20 13:13
Hi @geneus, can't reproduce your issue

**Comment by annakocheshkova** [comment] 2018-02-26 11:26
@geneus, closing this for now, please feel free to reopen if you find more info.

**Closed by annakocheshkova** 2018-02-26 11:26 UTC
Labels: need-repro, waiting-for-clarification, windows

**Comment by geneus** [comment] 2018-03-08 18:05
Hi @annakocheshkova. 

It stopped for a while, for 2 days I think, then it started again. Uninstalled, reinstalled then a different extension started throwing the error. I'm kinda lost why this behaviour persists and unfortunately, I am not currently developing. Working on something else design related so I can't provide any further info as yet. I'm also experiencing issues with my network so I have limited (**and slow**) access to the net. 

I will reopen if the issue persists when I do get around to looking into the issue again. 

Thanks for the help.
