### ISSUE TITLE
Package.json gives a warning for "name"

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode-react-native#151] opened 2016-03-15 00:14 UTC
Intellisense for package.json is showing a warning for the name of my project that it does not match some Regex pattern that is required.

![reactjson](https://cloud.githubusercontent.com/assets/12900364/13764004/150d5fa4-ea08-11e5-98e1-74380438d2ca.JPG)

Expected:
The package name should not have warnings

**Comment by MSLaguana** [comment] 2016-03-15 00:26
By default, vscode uses the json schema from http://json.schemastore.org/package for validating package.json files. The validation specified there states that package names must not include capital letters, which is why it is complaining.

If you want to override the schema that vscode uses for validation, you can refer to https://code.visualstudio.com/Docs/languages/json#_json-schemas-settings for how to override the default schema.

**Comment by digeff** [comment] 2016-03-15 17:07
@MSLaguana Maybe we should have the extension override the schema. A lot of users are going to run into this behavior, if we want to support React-Native inside VS Code we shouldn't show an error on that file if there isn't one. What do you think?

**Comment by hamiltonia** [comment] 2016-03-15 18:01
Closing as this is an external issue related to the schema - it can be ignored or renamed as appropriate.

**Closed by hamiltonia** 2016-03-15 18:01 UTC
Labels: external

**Comment by Dragan994** [comment] 2022-01-31 02:23
In tsconfig.json add this line or set its value to false. 
This worked for me.

"forceConsistentCasingInFileNames": false,  // Fix for name regex pattern

**Comment by Nearga** [comment] 2022-08-20 18:20
Greetings grom 2022. The issue is still there. 
Originally i've named the package "ZohoSender-v2.0" (it was named automatically by the folder), now i've changed name to "ZohoSender" and it still highlights it as an issue. 
Not sure it is the schema issue.

![image](https://user-images.githubusercontent.com/1726848/185761099-d5e8addc-9ad1-40b7-9a31-4c169f4c6bd2.png)
