### ISSUE TITLE
Under certain conditions, placing a break point into a method called when an onPress event fire in a button, causes the vscode debugger to apparently hang when the method breakpoint is reached.

### ISSUE THREAD

**Issue by bgiavotto** [Microsoft/vscode-react-native#368] opened 2016-12-20 13:44 UTC
## Actual Behavior
1) Create a new project and use copy-paste the source code below.
2) on the emulator enable the debugging, click on the button. the code in method buttonclick execute correctly
3) Now, place a breakpoint on the line "console.error" in method buttonclick()
4) Click the button. Apparently the emulator device does not respond to clicks. this happens because on the emulator the process is stopped because of the break point, but vscode does not catch up the breakpoint reached.
5) Now switch to vscode and press the "||" (pause) button on the debug toolbar. You will notice that execution is paused at the line with breakpoint but VSCode never noticed this.
6) Hit F10 and execution will continue.

please notice that changing the onPress handler from
onPress={ this.buttonclick }
to
onPress={ ()=> { this.buttonclick() } }
make the problem disappear.
## Expected Behavior

Instead on hanging up the vscode should catch up the breakpoint and show in the source code the current execution line

## Software versions
- React-Native VS Code extension version: 0.2.4
- VSCode version: 1.8.1
- OS platform and version: win
- NodeJS version: 6.9.1
- React Native version: 1.3.x

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by bgiavotto** [comment] 2016-12-20 13:46
the chrome debugger works fine.

**Comment by vladimir-kotikov** [comment] 2016-12-20 14:10
@bgiavotto, this souds like a dupe of https://github.com/Microsoft/vscode-react-native/issues/273 and appears to be a node@6.x issue

**Comment by bgiavotto** [comment] 2016-12-20 14:46
I got also problems with node 7.x

**Comment by MSLaguana** [comment] 2016-12-20 19:28
I still suspect that it is the same issue, which we've reported at https://github.com/nodejs/node/issues/8347

Node is currently going through a change of how debugging works. Unfortunately for us, the new system (which I believe works in this case) is still experimental and changing, while the old system is essentially deprecated and doesn't seem likely to have much more done on it.

**Comment by bgiavotto** [comment] 2016-12-21 09:27
maybe getting a quick view on how the chrome debugger does the interaction with debugger can help?
the chrome debugger handles correctly the issue, no malfunctions.

**Comment by bgiavotto** [comment] 2016-12-21 09:28
however i agree about your suspect, it's probably the same problem

**Comment by vladimir-kotikov** [comment] 2017-02-14 14:30
This issue has been fixed by switching to `node2` debugging engine in #390. @MSLaguana, can we close this?

**Closed** 2017-02-14 16:53 UTC
