### ISSUE TITLE
Stack trace symbolication fails when vscode is the remote debugger

### ISSUE THREAD

**Issue by jeanregisser** [Microsoft/vscode-react-native#292] opened 2016-08-29 08:59 UTC
## Actual Behavior
1. Create a React Native app: `react-native init MyProject`
2. Open the project in vscode: `code MyProject`
3. Start a debug session from debug tab.
4. Add a typo somewhere which result in a red box in the app with the stack trace
5. The red box stack trace is shown
6. Notice that you see `index.ios.bundle` items 

![image](https://cloud.githubusercontent.com/assets/57791/18045914/95edd22e-6dd5-11e6-9013-c0dc9b4ba9e1.png)
## Expected Behavior

It should show the actual origin files.
## Software versions
- React-Native VS Code extension version: 0.1.5
- VSCode version: 1.4.0
- OS platform and version: OSX
- React Native version: 0.32.0
## Outputs
- Output of the Debug Console (View -> Toggle Debug Console): 

```
=== BUILD TARGET MyProjectTests OF PROJECT MyProject WITH CONFIGURATION Debug ===
Check dependencies
** BUILD SUCCEEDED **
Installing build/Build/Products/Debug-iphonesimulator/MyProject.app
Launching org.reactjs.native.example.MyProject
org.reactjs.native.example.MyProject: 72879
[vscode-react-native] Finished executing: react-native run-ios --simulator iPhone 5s --project-path ios
[vscode-react-native] Starting debugger app worker.
[vscode-react-native] Established a connection with the Proxy (Packager) to the React Native application
[vscode-react-native] Debugging session started successfully.
StyleShee is not defined
Module AppRegistry is not a registered callable module.
Unhandled JS Exception: StyleShee is not defined
Unhandled JS Exception: Module AppRegistry is not a registered callable module.
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox): 

```
######### Starting Packager ##########
######### Executing command: react-native start --port 8081 ##########
Scanning 582 folders for symlinks in /Users/jean/src/MyProject/node_modules (6ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/jean/src/MyProject 

[10:39:46 AM] <START> Building Dependency Graph
[10:39:46 AM] <START> Crawling File System
[Hot Module Replacement] Server listening on /hot

React packager ready.

[10:39:46 AM] <END>   Crawling File System (195ms)
[10:39:46 AM] <START> Building in-memory fs for JavaScript
[10:39:46 AM] <END>   Building in-memory fs for JavaScript (150ms)
[10:39:46 AM] <START> Building in-memory fs for Assets
[10:39:47 AM] <END>   Building in-memory fs for Assets (114ms)
[10:39:47 AM] <START> Building Haste Map
[10:39:47 AM] <START> Building (deprecated) Asset Map
[10:39:47 AM] <END>   Building (deprecated) Asset Map (37ms)
[10:39:47 AM] <END>   Building Haste Map (113ms)
[10:39:47 AM] <END>   Building Dependency Graph (594ms)
######### Packager started. ##########
[10:39:47 AM] <START> request:/index.ios.bundle
[10:39:47 AM] <START> find dependencies
[10:39:47 AM] <END>   find dependencies (456ms)
######### The Bundle Cache was prewarmed. ##########
[10:39:47 AM] <END>   request:/index.ios.bundle (525ms)
[10:39:55 AM] <START> request:/index.ios.bundle?platform=ios&dev=true&minify=false
[10:39:55 AM] <START> find dependencies
[10:39:56 AM] <END>   find dependencies (465ms)
Starting custom debugger by executing: echo A debugger is not needed:  "/Users/jean/src/MyProject"
[10:39:56 AM] <START> request:/index.ios.bundle?platform=ios&dev=true&minify=false
[10:39:56 AM] <END>   request:/index.ios.bundle?platform=ios&dev=true&minify=false (548ms)
[10:39:56 AM] <END>   request:/index.ios.bundle?platform=ios&dev=true&minify=false (66ms)
[10:39:56 AM] <START> request:/index.ios.bundle?platform=ios&dev=true&minify=false
[10:39:56 AM] <END>   request:/index.ios.bundle?platform=ios&dev=true&minify=false (14ms)
[10:39:56 AM] <START> request:/index.ios.map?platform=ios&dev=true&minify=false
[10:39:56 AM] <END>   request:/index.ios.map?platform=ios&dev=true&minify=false (100ms)
[10:39:56 AM] <START> symbolicate
[10:39:56 AM] <END>   symbolicate (1ms)
[10:39:56 AM] <START> symbolicate
[10:39:56 AM] <END>   symbolicate (2ms)
[10:39:56 AM] <START> symbolicate
[10:39:56 AM] <END>   symbolicate (0ms)
[10:39:56 AM] <START> symbolicate
[10:39:56 AM] <END>   symbolicate (0ms)
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab): 

None
# Additional notes

If I manually stop remote debugging from within the device/simulator (CMD + D, Stop remote JS debugging), symbolication then succeeds (I see actually original js files) and I don't see references to `vm.js`, `appWorker.js` or `q.js` which were part of the debugger.

I initially talked about this when I reported https://github.com/Microsoft/vscode-react-native/issues/289 and I'm now opening this separate issue to better detail it.

**Comment by MSLaguana** [comment] 2016-08-29 17:26
It looks like this is related to some change in a recent version of react-native. The (fairly outdated now) 0.19.0 sample project we have in the repo works fine, but I do see this issue with 0.31.0 and 0.32.0. We'll have to work out what makes symbolication different when operating on a vscode project, since I believe it is all done in the packager and we don't do anything different there.

**Comment by MSLaguana** [comment] 2016-08-29 18:11
Hmm, I wonder if this is the cause: https://github.com/facebook/react-native/commit/46e880a3a7bd9c6a9d15b6ad17adfdbc23cdcb24

Might be to do with the restriction that it starts with `http` possibly, since we aren't running in chrome and we act as though it is on-disk?

**Comment by jeanregisser** [comment] 2016-09-20 07:23
Looks like you fixed it: https://github.com/facebook/react-native/commit/7dbc8051e5eec12db4d98fe658167c522c6d8275
Right? 🎉

**Comment by MSLaguana** [comment] 2016-09-20 15:19
Yeah, so hopefully in the next release of react native symbolication should work regardless of whether it is debugging in chrome or in vscode or nucleide.

**Comment by MSLaguana** [comment] 2016-09-20 17:54
Looks like I might have jumped the gun slightly, I think it hasn't made it into the 0.34 release (at least not their RC branch) but it should be in the release after that I think.

**Comment by vladimir-kotikov** [comment] 2016-10-28 14:10
Looks like the fix has landed in react-native@0.35, but after additional testing this seems to be still an issue. Using rn@0.35 and rn@0.36 while debugging I see the following error in debug console:

    Unable to symbolicate stack trace: You attempted to set the key `file` with the value `"http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false"` on an object that is meant to be immutable and has been frozen.

and stack frames on device's screen are pointing to bundle file rather than actual file on disk.

Looks like `stack` array that comes to `symbolicateStackTrace` is deeply frozen so we can't just change `file` field there - we need to copy frames into new array. I'm going to test the fix and sent another PR to react-native.

**Comment by vladimir-kotikov** [comment] 2016-11-02 14:07
The PR has been merged in https://github.com/facebook/react-native/commit/0fe1c7a9ff84bb0d49a0fbe3de3d09d89bf1a785 so hopefully will be available in next version of react-native (0.37 is RC already so it might be in next after 0.37)

**Comment by vladimir-kotikov** [comment] 2016-11-02 14:17
@MSLaguana, can we close this. Looks like there is nothing required from our side anymore.

**Closed** 2016-11-02 14:38 UTC
Labels: bug, copiedtobacklog, external-report, triaged

**Comment by ramintagizade** [comment] 2017-08-09 18:06
same problem

**Comment by wprater** [comment] 2017-11-21 02:18
Im seeing this crop up again in RN 0.50.3
