### ISSUE TITLE
Reload not working for vscode 1.78(latest version)

### ISSUE THREAD

**Issue by weinixuehao** [microsoft/vscode-react-native#1965] opened 2023-06-03 13:29 UTC
# 🐛 What is the bug? How can we reproduce it?
Reload is not working in vscode 1.78
if downgrade to the old version it works e.g: February 2023 (version 1.76)
react-native tools extension version is v1.11.0(latest)
and find out this code has an error
```
  runtime_->evaluateJavaScript(
      std::make_unique<BigStringBuffer>(std::move(script)), sourceURL);
```

## Expected behavior

Reload works in 1.78

## Debug output

<details>
<summary>Debug Console</summary>

```text

PASTE OUTPUT OF DEBUG CONSOLE (View -> Toggle Debug Console)

```
</details>

<details>
<summary>React Native output channel</summary>

```text

PASTE OUTPUT OF REACT-NATIVE OUTPUT CHANNEL (View -> Toggle Output -> Select React-Native in ListBox)

```
</details>

<details>
<summary>Developer Tools console</summary>

```text

PASTE OUTPUT OF DEVELOPER TOOLS CONSOLE (Help -> Toggle Developer Tools -> Select Console tab)

```
</details>

## Environment

Please tell us about your system and your project:

warn Package @ant-design/icons-react-native contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package @ant-design/react-native contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
⠴ Running diagnostics...warn Package @ant-design/icons-react-native contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package @ant-design/react-native contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
Common
 ✓ Node.js
 ✓ npm
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI
 ✖ .xcode.env - File to customize Xcode environment

PASTE OUTPUT OF `npx react-native doctor` or `npx expo doctor`
```

* `envinfo`:

```text
PASTE OUTPUT OF `npx envinfo`
```

* React Native Tools extension version: v1.11.0
* Expo SDK version (if applicable): VERSION

**Comment by EzioLi01** [comment] 2023-06-05 02:05
Hey @weinixuehao , thanks for reaching us, I saw that you're using MacOS for debugging, could you please let me know which type of Mac you used(Intel chip or Apple chip like M1, M2)? Also please let me know about your Xcode version, thanks!

**Comment by EzioLi01** [comment] 2023-06-05 04:20
I have checked reload issue is not repro on my local, is it possible to provide some repro steps and the demo application for the investigation?

**Comment by gvsboy** [comment] 2023-06-05 04:33
Heya 👋 It sounds like I'm running into the same issue. When I "Run and Debug" using an iOS simulator and manually reload (either CMD+D -> "Reload" or closing the app and launching it again in the simulator), I am stuck on a black screen with "Downloading 100%". The only thing I can do at this point is "Stop" and then "Run and Debug" again.

Notes:
- Using `npx react-native run-ios` (outside of VSCode) works fine (e.g. I am able to reload successfully)
- Disabling the debugger (i.e. pressing "Stop Debugging") allows me to reload, but then I cannot debug 😁 This feels like an issue attempting to connect to the debugger after reloading/relaunching
- Once I am in the "stuck" state, I need to press "Stop" in VSCode twice to actually stop (very strange...)

VSCode: 1.78.2
React Native Tools: 1.11.0
Xcode: 14.1

Thanks for your help!

**Comment by EzioLi01** [comment] 2023-06-05 04:44
Thanks @gvsboy for the details, could you please also confirm this on android platform?

**Comment by gvsboy** [comment] 2023-06-05 04:53
Unfortunately, I am not currently configured to develop on Android. (One platform at a time for me 🙂)

**Comment by EzioLi01** [comment] 2023-06-05 04:59
> Unfortunately, I am not currently configured to develop on Android. (One platform at a time for me 🙂)

NP @gvsboy ,thank you! Since Android platform is working well on my local, I will start to investigate on iOS firstly. Since this extension is depended on vscode-js-debug, I will check it both on RNT and js-debug. Any update will comment here.

**Comment by EzioLi01** [comment] 2023-06-05 09:33
Hey guys, could you please let me know which version of rn is used in application?

**Comment by weinixuehao** [comment] 2023-06-05 13:05
> Hey @weinixuehao , thanks for reaching us, I saw that you're using MacOS for debugging, could you please let me know which type of Mac you used(Intel chip or Apple chip like M1, M2)? Also please let me know about your Xcode version, thanks!
> 
> BTW, the debugging is failed on all platforms or just iOS?

```
System:
    OS: macOS 13.0.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 738.90 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
    Watchman: 2023.02.27.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 27, 28, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.3, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      Android NDK: 21.1.6352462
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.2 => 0.70.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

**Comment by weinixuehao** [comment] 2023-06-05 13:09
> Hey guys, could you please let me know which version of rn is used in the application?

It does not seem to relate to the RN version
I have tried the RN 0.62 and 0.70.2 of the RN version that seems not to work.

**Comment by gvsboy** [comment] 2023-06-05 14:09
I'm using RN 0.67.4 if it helps.

**Comment by EzioLi01** [comment] 2023-06-06 02:01
Thanks for the details, investigating.

**Comment by EzioLi01** [comment] 2023-06-07 06:51
It may had the same root cause with #1968.

**Comment by EzioLi01** [comment] 2023-06-15 02:34
Update: this issue will be fixed on next js-debug release. Here is a temporary workaround for the reference - using js-debug nightly version. Please get details in above issue.

**Comment by EzioLi01** [comment] 2023-06-25 08:06
Close this issue, please comment or discuss the related issue on above issue, thank you!

**Closed by EzioLi01** 2023-06-25 08:06 UTC
Labels: bug, triaged, js-debug-related

**Comment by weinixuehao** [comment] 2023-09-27 02:12
It`s still not working 
my vscode and js-debug both are 1.82

**Comment by EzioLi01** [comment] 2023-09-28 09:12
I think it should be related to js-debug updates, I will check it and sync with js-debug team. Could you please check if reload is working with react-native-tools 1.12.1 and vscode 1.76?

**Comment by doublethefish** [comment] 2023-10-07 12:25
> Could you please check if reload is working with react-native-tools 1.12.1 and vscode 1.76

With [React Native Tools 1.12.1](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/msjsdiag/vsextensions/vscode-react-native/1.12.1/vspackage) (released last week) and [vscode 1.76.2](https://code.visualstudio.com/updates/v1_76) it seems to work for me.

**Comment by weinixuehao** [comment] 2023-10-09 07:04
> I think it should be related to js-debug updates, I will check it and sync with js-debug team. Could you please check if reload is working with react-native-tools 1.12.1 and vscode 1.76?
```
Version: 1.77.3 (Universal)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:19:37.325Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No
```
React Native version is v1.12.1
though it worked but I need the latest version of vs code to work

**Comment by weinixuehao** [comment] 2023-10-12 02:28
This issue needs to be reopened.

**Comment by EzioLi01** [comment] 2023-10-13 12:38
> > Could you please check if reload is working with react-native-tools 1.12.1 and vscode 1.76
> 
> With [React Native Tools 1.12.1](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/msjsdiag/vsextensions/vscode-react-native/1.12.1/vspackage) (released last week) and [vscode 1.76.2](https://code.visualstudio.com/updates/v1_76) it seems to work for me.

So this issue should be related to the vscode built-in extension vscode-js-debug, but I will try to get some workarounds for this by refactoring logic for reload process.

**Comment by EzioLi01** [comment] 2023-10-30 02:15
@weinixuehao Could you please provide some details of repro steps or a demo for this, since I have tried on the latest vscode and rnt, but cannot repro this issue so far.

https://github.com/microsoft/vscode-react-native/assets/19662219/019dc078-a56b-4605-8e6d-025ac560fa88

**Comment by doublethefish** [comment] 2023-10-30 13:29
### Repro env
1. M1 MBP
2. running a fresh app created `npx react-native@latest init basic_app`
4. using react-native 0.72.6

### Working reload 😁
1. Ensure App is deleted off of phone/simulator
5. Start the App
6. Wait for App to load (might take two loads)
7. With the Simulator in context
   1. press CMD+CTR+Z
   2. tap the "Reload" option
8. Notice that the App reloads properly 👍👍
   1. Also notice that the DEBUG CONSOLE says:
      "Established a connection with the Proxy (Packager) to the React Native application"

### Non-working mode 😢
1. Stop debugging
2. Kill the App
3. Leave the App installed this time
4. Start the debugger
5. Wait for the App to Load
9. With the Simulator in context
   1. press CMD+CTR+Z
   2. tap the "Reload" option
10. Notice that the App doesn't reload 👎👎
   1. Also notice that the DEBUG CONSOLE contains "Could not read source map [...]"


https://github.com/microsoft/vscode-react-native/assets/2162172/b2eff715-435f-47af-853e-12a628b19e87

**Comment by sleeper-luke** [comment] 2024-01-24 22:06
Just chiming in to say I'm in the same boat - reload does not work on the latest version of vscode (1.85.2). Downgrading to `1.76.2` fixes the issue.

I'm also on an M1 mac, React Native 0.72.7, vscode-react-native 1.12.2.

**Comment by doublethefish** [comment] 2024-05-27 12:17
This is still happening in 1.89.0.

Any tips on how to debug the issue are greatly welcome.

**Comment by biaji** [comment] 2024-12-04 07:55
Same here.

x86 mac.

React Native 0.70.0
